/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  fittedViewBox: "1.81 2.89 16.38 15.08",
  svg: (
    <path d="M10.44 2.907c4.513.182 7.747 3.144 7.748 6.947 0 3.802-3.235 6.765-7.748 6.947l-.44.009c-.88 0-1.711-.106-2.484-.3-1.35 1.023-2.986 1.62-4.827 1.428a.625.625 0 0 1-.406-1.033c.713-.817 1.096-1.737 1.284-2.641-1.115-1.198-1.755-2.734-1.755-4.41 0-3.926 3.447-6.956 8.188-6.956zM10 6.375A.625.625 0 0 0 9.375 7v2.375H7a.625.625 0 1 0 0 1.25h2.375V13a.625.625 0 1 0 1.25 0v-2.375H13a.625.625 0 1 0 0-1.25h-2.375V7A.625.625 0 0 0 10 6.375" />
  ),
};

export const chatBubblePlusFillIcon: LoadedIconFunction = createIcon(
  "chatBubblePlusFill",
  iconDefinition,
);
