/* =============================================================================

	THIS FILE IS GENERATED BY `notion figma import-icons` (src/cli/commands/figma/import-icons.ts).
	DO NOT MANUALLY EDIT THIS FILE.

============================================================================= */

import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  fittedViewBox: "1.31 2.2 13.37 12.26",
  svg: (
    <>
      <path d="M8 5c.345 0 .625.28.625.625V7.25h1.625a.625.625 0 1 1 0 1.25H8.625v1.625a.625.625 0 1 1-1.25 0V8.5H5.75a.625.625 0 1 1 0-1.25h1.625V5.625C7.375 5.28 7.655 5 8 5" />
      <path d="M8.357 2.202c3.661.148 6.318 2.557 6.318 5.683l-.008.3c-.164 2.978-2.767 5.24-6.31 5.382L8 13.574a8.3 8.3 0 0 1-1.962-.23c-1.09.812-2.412 1.287-3.9 1.133a.625.625 0 0 1-.406-1.033 4.44 4.44 0 0 0 .987-1.996 5.26 5.26 0 0 1-1.388-3.29l-.007-.273c0-3.227 2.832-5.69 6.676-5.69zM8 3.445c-3.335 0-5.426 2.072-5.426 4.44l.005.208c.053 1.033.497 1.975 1.251 2.709a.63.63 0 0 1 .18.547 6 6 0 0 1-.602 1.84c.763-.138 1.466-.494 2.095-1.01l.062-.044a.63.63 0 0 1 .506-.072A7 7 0 0 0 8 12.324l.309-.006c3.154-.123 5.116-2.14 5.116-4.433 0-2.294-1.962-4.31-5.116-4.434z" />
    </>
  ),
};

export const chatBubblePlusIcon: LoadedIconFunction = createIcon(
  "chatBubblePlus",
  iconDefinition,
);
