// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M5.393 6.022a.625.625 0 0 1 0 .884L2.925 9.375h5.66a.625.625 0 0 1 0 1.25h-5.66l2.468 2.469a.625.625 0 0 1-.884.883L.974 10.442a.625.625 0 0 1 0-.884l3.535-3.536a.625.625 0 0 1 .884 0m6.026 3.353a.625.625 0 0 0 0 1.25h5.648l-2.469 2.469a.625.625 0 1 0 .884.883l3.536-3.535a.625.625 0 0 0 0-.884l-3.536-3.536a.625.625 0 0 0-.884.884l2.469 2.469z" />
  ),
};

export const arrowExpandHorizontalIcon: LoadedIconFunction = createIcon(
  "arrowExpandHorizontal",
  iconDefinition,
);
