// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.491 4.641a.75.75 0 0 1 0 1.061L2.943 7.25H6.87a.75.75 0 0 1 0 1.5H2.943l1.548 1.548a.75.75 0 1 1-1.06 1.06L.602 8.53a.75.75 0 0 1 0-1.06l2.829-2.83a.75.75 0 0 1 1.06 0m4.644 2.61a.75.75 0 0 0 0 1.5h3.915l-1.548 1.548a.75.75 0 1 0 1.06 1.06l2.829-2.828a.75.75 0 0 0 0-1.06l-2.829-2.83a.75.75 0 1 0-1.06 1.061L13.05 7.25z" />
  ),
};

export const arrowExpandHorizontalFillSmallIcon: LoadedIconFunction =
  createIcon("arrowExpandHorizontalFillSmall", iconDefinition);
