// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M5.57 5.846a.875.875 0 0 1 0 1.237L3.528 9.125h5.058a.875.875 0 0 1 0 1.75H3.528l2.042 2.042a.875.875 0 1 1-1.237 1.237L.797 10.62a.875.875 0 0 1 0-1.238l3.536-3.535a.875.875 0 0 1 1.237 0m5.849 3.278a.875.875 0 0 0 0 1.75h5.044l-2.042 2.042a.875.875 0 1 0 1.238 1.237l3.535-3.535a.875.875 0 0 0 0-1.238L15.66 5.846a.875.875 0 0 0-1.238 1.237l2.042 2.042z" />
  ),
};

export const arrowExpandHorizontalFillIcon: LoadedIconFunction = createIcon(
  "arrowExpandHorizontalFill",
  iconDefinition,
);
