// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.2 9.325a1.325 1.325 0 1 0 0-2.65 1.325 1.325 0 0 0 0 2.65m4.8 0a1.325 1.325 0 1 0 0-2.65 1.325 1.325 0 0 0 0 2.65m4.8 0a1.325 1.325 0 1 0 0-2.65 1.325 1.325 0 0 0 0 2.65" />
  ),
};

export const ellipsisFillSmallIcon: LoadedIconFunction = createIcon(
  "ellipsisFillSmall",
  iconDefinition,
);
