// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4 11.75a1.75 1.75 0 1 0 0-3.5 1.75 1.75 0 0 0 0 3.5m6 0a1.75 1.75 0 1 0 0-3.5 1.75 1.75 0 0 0 0 3.5m6 0a1.75 1.75 0 1 0 0-3.5 1.75 1.75 0 0 0 0 3.5" />
  ),
};

export const ellipsisFillIcon: LoadedIconFunction = createIcon(
  "ellipsisFill",
  iconDefinition,
);
