// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const envelopeBadgeIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "envelopeBadge",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-envelopeBadge" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-envelopeBadge" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-envelopeBadge" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-envelopeBadge" */
          "./fillSmall.icon"
        ),
    },
  },
  ["envelope", "notification", "dot", "mail", "message"],
);
