// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M7 4.375a.625.625 0 1 0 0 1.25h10.1a.625.625 0 1 0 0-1.25zm0 5a.625.625 0 1 0 0 1.25h10.1a.625.625 0 1 0 0-1.25zM6.375 15c0-.345.28-.625.625-.625h10.1a.625.625 0 1 1 0 1.25H7A.625.625 0 0 1 6.375 15M2.9 9.375a.625.625 0 1 0 0 1.25h1.5a.625.625 0 1 0 0-1.25zM2.275 5c0-.345.28-.625.625-.625h1.5a.625.625 0 1 1 0 1.25H2.9A.625.625 0 0 1 2.275 5m.625 9.375a.625.625 0 1 0 0 1.25h1.5a.625.625 0 1 0 0-1.25z" />
  ),
};

export const listDashIcon: LoadedIconFunction = createIcon(
  "listDash",
  iconDefinition,
);
