// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.6 7.26a.75.75 0 1 0 0 1.5h7.8a.75.75 0 1 0 0-1.5zm0-4a.75.75 0 0 0 0 1.5h7.8a.75.75 0 0 0 0-1.5zm-.75 8.73a.75.75 0 0 1 .75-.75h7.8a.75.75 0 1 1 0 1.5H5.6a.75.75 0 0 1-.75-.75M2.6 7.26a.75.75 0 1 0 0 1.5h1a.75.75 0 1 0 0-1.5zm-.75-3.25a.75.75 0 0 1 .75-.75h1a.75.75 0 0 1 0 1.5h-1a.75.75 0 0 1-.75-.75m.75 7.23a.75.75 0 0 0 0 1.5h1a.75.75 0 0 0 0-1.5z" />
  ),
};

export const listDashFillSmallIcon: LoadedIconFunction = createIcon(
  "listDashFillSmall",
  iconDefinition,
);
