// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M9.875 6.75c.345 0 .625.28.625.625v3.5a.625.625 0 1 1-1.25 0v-3.5c0-.345.28-.625.625-.625m0 7.375a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5" />
      <path d="M8.16 3.563c.818-1.417 2.863-1.417 3.68 0l5.846 10.125c.818 1.416-.204 3.187-1.84 3.187H4.155c-1.636 0-2.659-1.77-1.84-3.187zm2.598.624a.875.875 0 0 0-1.516 0L3.397 14.313a.875.875 0 0 0 .758 1.313h11.69a.875.875 0 0 0 .759-1.312z" />
    </>
  ),
};

export const exclamationMarkTriangleIcon: LoadedIconFunction = createIcon(
  "exclamationMarkTriangle",
  iconDefinition,
);
