// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M1.375 6.5c0-1.174.951-2.125 2.125-2.125h9c1.077 0 1.967.802 2.106 1.841v7.568a2.125 2.125 0 0 1-2.106 1.841h-9A2.125 2.125 0 0 1 1.375 13.5zm14.331 6.571 2.158 1.307a.625.625 0 0 0 .948-.534V6.156a.625.625 0 0 0-.948-.534l-2.158 1.307z" />
  ),
};

export const videoCameraFillIcon: LoadedIconFunction = createIcon(
  "videoCameraFill",
  iconDefinition,
);
