// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4 2.975c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h3.676l2.84 2.307a.625.625 0 0 0 1.018-.485v-1.822H12c1.036 0 1.875-.84 1.875-1.875v-5.5c0-1.035-.84-1.875-1.875-1.875zM3.375 4.85c0-.345.28-.625.625-.625h8c.345 0 .625.28.625.625v5.5c0 .345-.28.625-.625.625h-1.09a.625.625 0 0 0-.626.625v1.134l-1.992-1.619a.63.63 0 0 0-.394-.14H4a.625.625 0 0 1-.625-.625z" />
  ),
};

export const bubbleRightSmallIcon: LoadedIconFunction = createIcon(
  "bubbleRightSmall",
  iconDefinition,
);
