// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path
        fillRule="evenodd"
        d="M3.8 2.425c-.76 0-1.375.616-1.375 1.375v1.256c0 .554.328 1.032.8 1.25V12.2c0 .76.616 1.375 1.375 1.375h3.53l-.038-.043a1.87 1.87 0 0 1-.448-1.107H4.6a.225.225 0 0 1-.225-.225V6.431h7.25v3.99l.932-1.554q.096-.161.218-.295V6.305c.472-.217.8-.695.8-1.249V3.8c0-.76-.616-1.375-1.375-1.375zM3.575 3.8c0-.124.1-.225.225-.225h8.4c.124 0 .225.1.225.225v1.256a.225.225 0 0 1-.22.225h-8.41a.225.225 0 0 1-.22-.225z"
        clipRule="evenodd"
      />
      <path d="M6.4 7.925a.575.575 0 1 0 0 1.15h3.2a.575.575 0 1 0 0-1.15zm8.301 2.228a.625.625 0 1 0-1.072-.643l-2.344 3.906-1.295-1.511a.625.625 0 0 0-.95.813l1.86 2.17a.625.625 0 0 0 1.011-.085z" />
    </>
  ),
};

export const archiveBoxCheckSmallIcon: LoadedIconFunction = createIcon(
  "archiveBoxCheckSmall",
  iconDefinition,
);
