// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10.619 2.381a.875.875 0 0 0-1.238 0l-5.4 5.4A.875.875 0 1 0 5.22 9.02l3.906-3.907V17.05c0 .456.392.826.875.826s.875-.37.875-.826V5.112l3.906 3.907A.875.875 0 1 0 16.02 7.78z" />
  ),
};

export const arrowStraightUpFillIcon: LoadedIconFunction = createIcon(
  "arrowStraightUpFill",
  iconDefinition,
);
