// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const calendarBadgeClockIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "calendarBadgeClock",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-calendarBadgeClock" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-calendarBadgeClock" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-calendarBadgeClock" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-calendarBadgeClock" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "annually",
    "badge",
    "calendar",
    "clock",
    "date",
    "daily",
    "monthly",
    "recurring",
    "schedule",
    "time",
  ],
);
