// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.417 5.467c.23-.23.219-.615-.025-.859s-.629-.255-.86-.025l-8.857 8.858V7.313a.625.625 0 0 0-1.25 0v7.637c0 .345.28.625.625.625h7.637a.625.625 0 1 0 0-1.25H6.559z" />
  ),
};

export const arrowDiagonalDownLeftIcon: LoadedIconFunction = createIcon(
  "arrowDiagonalDownLeft",
  iconDefinition,
);
