// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.604 5.634c.322-.323.306-.86-.036-1.203-.341-.341-.88-.357-1.202-.035l-8.44 8.441V7.313a.875.875 0 1 0-1.75 0v7.637c0 .483.391.875.874.875h7.637a.875.875 0 1 0 0-1.75H7.163z" />
  ),
};

export const arrowDiagonalDownLeftFillIcon: LoadedIconFunction = createIcon(
  "arrowDiagonalDownLeftFill",
  iconDefinition,
);
