// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowDiagonalDownLeftIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowDiagonalDownLeft",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeft" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeft" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeft" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeft" */
          "./fillSmall.icon"
        ),
    },
  },
  ["arrow", "down", "left", "direction", "navigation"],
);
