// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.154 3.846a.614.614 0 0 0-.867-.017l-6.374 6.374v-4.6a.625.625 0 1 0-1.25 0v6.11c0 .345.28.624.625.624h6.109a.625.625 0 1 0 0-1.25h-4.6l6.374-6.374a.614.614 0 0 0-.017-.867" />
  ),
};

export const arrowDiagonalDownLeftSmallIcon: LoadedIconFunction = createIcon(
  "arrowDiagonalDownLeftSmall",
  iconDefinition,
);
