// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M7.45 3.45H4a1.8 1.8 0 0 0-1.8 1.8v.867h5.25zM2.2 8.783V7.217h5.25v1.566zm0 1.1v.867a1.8 1.8 0 0 0 1.8 1.8h3.45V9.883zm6.35 0v2.667H12a1.8 1.8 0 0 0 1.8-1.8v-.867zm5.25-1.1V7.217H8.55v1.566zm0-3.533v.867H8.55V3.45H12a1.8 1.8 0 0 1 1.8 1.8" />
  ),
};

export const viewTableFillSmallIcon: LoadedIconFunction = createIcon(
  "viewTableFillSmall",
  iconDefinition,
);
