// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.125 10c0-.483.392-.875.875-.875h12a.875.875 0 0 1 0 1.75H4A.875.875 0 0 1 3.125 10" />
  ),
};

export const dividerFillIcon: LoadedIconFunction = createIcon(
  "dividerFill",
  iconDefinition,
);
