// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M16.975 3.275c.483 0 .875.392.875.875v11.7a.875.875 0 1 1-1.75 0V4.15c0-.483.392-.875.875-.875M9.48 4.98a.875.875 0 0 1 1.238 0l4.4 4.4a.875.875 0 0 1 0 1.238l-4.4 4.4A.875.875 0 0 1 9.48 13.78l2.906-2.906H3.025a.875.875 0 1 1 0-1.75h9.362L9.481 6.219a.875.875 0 0 1 0-1.238" />
  ),
};

export const arrowLineRightFillIcon: LoadedIconFunction = createIcon(
  "arrowLineRightFill",
  iconDefinition,
);
