// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M13.58 2.57a.75.75 0 0 1 .75.75v9.36a.75.75 0 0 1-1.5 0V3.32a.75.75 0 0 1 .75-.75M7.55 3.95a.75.75 0 0 1 1.06 0l3.52 3.52a.75.75 0 0 1 0 1.06l-3.52 3.52a.75.75 0 0 1-1.06-1.06l2.24-2.24H2.42a.75.75 0 0 1 0-1.5h7.37L7.55 5.01a.75.75 0 0 1 0-1.06" />
  ),
};

export const arrowLineRightFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowLineRightFillSmall",
  iconDefinition,
);
