// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M5.2 5.425a.575.575 0 0 0 0 1.15h5.6a.575.575 0 1 0 0-1.15zm0 2.4a.575.575 0 1 0 0 1.15h4a.575.575 0 1 0 0-1.15z" />
      <path d="M4 2.575c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h.466v1.822a.625.625 0 0 0 1.019.485l2.84-2.307H12c1.036 0 1.875-.84 1.875-1.875v-5.5c0-1.035-.84-1.875-1.875-1.875zM3.375 4.45c0-.345.28-.625.625-.625h8c.345 0 .625.28.625.625v5.5c0 .345-.28.625-.625.625H8.102a.63.63 0 0 0-.394.14l-1.992 1.619V11.2a.625.625 0 0 0-.625-.625H4a.625.625 0 0 1-.625-.625z" />
    </>
  ),
};

export const commentFilledSmallIcon: LoadedIconFunction = createIcon(
  "commentFilledSmall",
  iconDefinition,
);
