// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const tableHeaderColumnIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "tableHeaderColumn",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-tableHeaderColumn" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-tableHeaderColumn" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-tableHeaderColumn" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-tableHeaderColumn" */
          "./fillSmall.icon"
        ),
    },
  },
  ["title", "header", "fixed", "column", "th", "primary key"],
);
