// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.125 5.833a2.708 2.708 0 1 1 5.417 0v1.459h2.916V5.833a2.708 2.708 0 1 1 2.709 2.709h-1.459v2.916h1.459a2.708 2.708 0 1 1-2.709 2.709v-1.459H8.542v1.459a2.708 2.708 0 1 1-2.709-2.709h1.459V8.542H5.833a2.71 2.71 0 0 1-2.708-2.709m5.417 5.625h2.916V8.542H8.542zm-1.25 1.25H5.833a1.458 1.458 0 1 0 1.459 1.459zM5.833 4.375a1.458 1.458 0 0 0 0 2.917h1.459V5.833c0-.805-.653-1.458-1.459-1.458m6.875 1.458v1.459h1.459a1.458 1.458 0 1 0-1.459-1.459m0 6.875v1.459a1.458 1.458 0 1 0 1.459-1.459z" />
  ),
};

export const commandIcon: LoadedIconFunction = createIcon(
  "command",
  iconDefinition,
);
