// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.25 4.667a2.417 2.417 0 0 1 4.834 0v.916h1.833v-.916a2.417 2.417 0 1 1 2.416 2.416h-.916v1.834h.916a2.417 2.417 0 1 1-2.416 2.416v-.916H7.084v.916a2.417 2.417 0 1 1-2.417-2.416h.917V7.083h-.917A2.417 2.417 0 0 1 2.25 4.667m8.167 5.75v.916a.917.917 0 1 0 .916-.916zm-1.5-3.334H7.084v1.834h1.833zM4.667 3.75a.917.917 0 0 0 0 1.833h.917v-.916a.917.917 0 0 0-.917-.917m5.75.917v.916h.916a.917.917 0 1 0-.916-.916M3.75 11.333a.917.917 0 0 0 1.834 0v-.916h-.917a.917.917 0 0 0-.917.916" />
  ),
};

export const commandFillSmallIcon: LoadedIconFunction = createIcon(
  "commandFillSmall",
  iconDefinition,
);
