// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M7.078 9.673a2.06 2.06 0 0 0 1.844 0l5.596-2.797a.93.93 0 0 0 .518-.839.93.93 0 0 0-.518-.839L8.922 2.401a2.07 2.07 0 0 0-1.844 0L1.482 5.198a.93.93 0 0 0-.518.839c0 .358.198.679.518.839l.07.035v3.246a.75.75 0 0 0-.281.585v2a.75.75 0 0 0 1.5 0v-2a.75.75 0 0 0-.281-.585V7.38z" />
      <path d="M6.575 10.68a3.2 3.2 0 0 0 2.85 0l3.262-1.631v1.637c0 .588-.287 1.14-.768 1.48A6.8 6.8 0 0 1 8 13.406a6.8 6.8 0 0 1-3.92-1.24 1.81 1.81 0 0 1-.768-1.48V9.049z" />
    </>
  ),
};

export const graduationCapFillSmallIcon: LoadedIconFunction = createIcon(
  "graduationCapFillSmall",
  iconDefinition,
);
