// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const squareGrid2X2IconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "squareGrid2X2",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareGrid2X2" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareGrid2X2" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareGrid2X2" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareGrid2X2" */
          "./fillSmall.icon"
        ),
    },
  },
  ["grid", "layout", "tiles", "matrix", "dashboard"],
);
