// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M15.549 8.06a.55.55 0 0 1 0 1.079l-.111.01h-1.25a.55.55 0 1 1 0-1.1h1.25zm0-2.1a.55.55 0 0 1 0 1.08l-.111.01h-1.25a.55.55 0 1 1 0-1.1h1.25z" />
      <path d="M16.25 3.625c1.174 0 2.125.951 2.125 2.125v8.5a2.125 2.125 0 0 1-2.125 2.125H3.75a2.125 2.125 0 0 1-2.125-2.125v-8.5c0-1.174.951-2.125 2.125-2.125zm-12.5 1.25a.875.875 0 0 0-.875.875v8.5c0 .483.392.875.875.875h7.7V4.875zm8.8 10.25h3.7a.875.875 0 0 0 .875-.875v-8.5a.875.875 0 0 0-.875-.875h-3.7z" />
    </>
  ),
};

export const sidebarRightIcon: LoadedIconFunction = createIcon(
  "sidebarRight",
  iconDefinition,
);
