// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.45 16.375h-7.7a2.125 2.125 0 0 1-2.125-2.125v-8.5c0-1.174.951-2.125 2.125-2.125h7.7zm4.8-12.75c1.174 0 2.125.951 2.125 2.125v8.5a2.125 2.125 0 0 1-2.125 2.125h-3.7V3.625zm-1.437 4.426a.55.55 0 1 0 0 1.1h1.25l.11-.011a.55.55 0 0 0 0-1.078l-.11-.011zm0-2.1a.55.55 0 1 0 0 1.099h1.25l.11-.01a.55.55 0 0 0 0-1.08l-.11-.01z" />
  ),
};

export const sidebarRightFillIcon: LoadedIconFunction = createIcon(
  "sidebarRightFill",
  iconDefinition,
);
