// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.2 3.625v.825H3.125a.55.55 0 0 0 0 1.1h.6l.294 6.472a1.863 1.863 0 0 0 1.86 1.778h4.242c.996 0 1.815-.783 1.86-1.778l.295-6.472h.6a.55.55 0 1 0 0-1.1H10.8v-.825c0-.787-.638-1.425-1.425-1.425h-2.75c-.787 0-1.425.638-1.425 1.425M6.625 3.3h2.75c.18 0 .325.145.325.325v.825H6.3v-.825c0-.18.146-.325.325-.325m.563 3.575v4.5a.5.5 0 1 1-1 0v-4.5a.5.5 0 1 1 1 0m2.625 0v4.5a.5.5 0 1 1-1 0v-4.5a.5.5 0 1 1 1 0" />
  ),
};

export const trashFillSmallIcon: LoadedIconFunction = createIcon(
  "trashFillSmall",
  iconDefinition,
);
