// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M2.238 14.331a.75.75 0 0 0 .895-.57c.018-.083 1.862-8.002 8.886-9.942-.227.506-.55 1.129-.992 1.784l-1.459-.064a.75.75 0 0 0-.774.86l.215 1.449A10 10 0 0 1 5.82 9.652a.75.75 0 1 0 .486 1.418 11.5 11.5 0 0 0 4.007-2.37.75.75 0 0 0 .239-.666l-.142-.957.962.042a.76.76 0 0 0 .639-.308c1.418-1.953 1.894-3.747 1.914-3.823a.75.75 0 0 0-.841-.93c-9.12 1.418-11.396 11.28-11.418 11.38a.75.75 0 0 0 .57.893" />
      <path d="M4.8 14.35h8a.75.75 0 0 0 0-1.5h-8a.75.75 0 0 0 0 1.5" />
    </>
  ),
};

export const quillFillSmallIcon: LoadedIconFunction = createIcon(
  "quillFillSmall",
  iconDefinition,
);
