// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.265 14.21a.626.626 0 0 0 .746-.476c.018-.085 1.921-8.264 9.226-10.102-.237.562-.607 1.31-1.146 2.099l-1.528-.067a.61.61 0 0 0-.49.206.62.62 0 0 0-.155.51l.224 1.519c-.976.83-2.079 1.46-3.28 1.872a.625.625 0 1 0 .405 1.181 11.35 11.35 0 0 0 3.963-2.345.63.63 0 0 0 .199-.555l-.164-1.107 1.113.05c.214.01.41-.088.533-.258 1.403-1.933 1.875-3.706 1.894-3.78a.624.624 0 0 0-.7-.775C4.066 3.587 1.81 13.366 1.788 13.465a.626.626 0 0 0 .476.745m2.536.015h8a.626.626 0 0 0 0-1.25h-8a.625.625 0 0 0 0 1.25" />
  ),
};

export const quillSmallIcon: LoadedIconFunction = createIcon(
  "quillSmall",
  iconDefinition,
);
