// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.848 9.95a1.25 1.25 0 1 1-.001 2.501 1.25 1.25 0 0 1 0-2.5m9.03.503a.75.75 0 0 1 0 1.492l-.077.004h-6a.75.75 0 0 1 0-1.5h6zM3.848 3.55a1.25 1.25 0 1 1-.001 2.5 1.25 1.25 0 0 1 0-2.5m9.03.504a.75.75 0 0 1 0 1.492l-.077.004h-6a.75.75 0 0 1 0-1.5h6z" />
  ),
};

export const listBulletFillSmallIcon: LoadedIconFunction = createIcon(
  "listBulletFillSmall",
  iconDefinition,
);
