// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.809 12.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3M16 13.125a.875.875 0 0 1 0 1.75H8.5a.875.875 0 0 1 0-1.75zM4.809 4.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3M16 5.125a.875.875 0 0 1 0 1.75H8.5a.875.875 0 0 1 0-1.75z" />
  ),
};

export const listBulletFillIcon: LoadedIconFunction = createIcon(
  "listBulletFill",
  iconDefinition,
);
