// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M13.13 4.186a1.5 1.5 0 1 1-2.984-.313 1.5 1.5 0 0 1 2.983.313M7.527 11.73l-.651 2.59-2.288 2.06a.75.75 0 1 0 1.004 1.115l2.627-2.367.608-2.414-.803-.546a2.7 2.7 0 0 1-.497-.438" />
      <path d="m8.549 7.38-.611 2.209a1.65 1.65 0 0 0 .587 1.75l2.838 2.172L9.5 14.863a.75.75 0 0 0 .882 1.214l2.578-1.873a.84.84 0 0 0 .017-1.347l-2.057-1.574.797-2.556.55 1.618a.75.75 0 0 0 .899.484l2.033-.528a.75.75 0 1 0-.377-1.452l-1.36.353-.342-1.01a3.496 3.496 0 0 0-3.478-2.366l-3.02.145a.75.75 0 0 0-.698.596l-.502 2.42a.75.75 0 0 0 1.469.304l.383-1.85z" />
    </>
  ),
};

export const figureRunFillIcon: LoadedIconFunction = createIcon(
  "figureRunFill",
  iconDefinition,
);
