// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const dotWavesRightIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "dotWavesRight",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-dotWavesRight" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-dotWavesRight" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-dotWavesRight" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-dotWavesRight" */
          "./fillSmall.icon"
        ),
    },
  },
  ["sound", "audio", "volume", "signal", "broadcast"],
);
