// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M8.002 3.238a.625.625 0 0 0-.884 0l-4.32 4.32a.625.625 0 0 0 0 .884l4.32 4.32a.625.625 0 0 0 .884-.884L4.124 8l3.878-3.878a.625.625 0 0 0 0-.884" />
      <path d="M12.402 3.238a.625.625 0 0 0-.884 0l-4.32 4.32a.625.625 0 0 0 0 .884l4.32 4.32a.625.625 0 0 0 .884-.884L8.524 8l3.878-3.878a.625.625 0 0 0 0-.884" />
    </>
  ),
};

export const arrowChevronDoubleBackwardSmallIcon: LoadedIconFunction =
  createIcon("arrowChevronDoubleBackwardSmall", iconDefinition);
