// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M9.772 1.8a.625.625 0 0 0-.773.428l-3.2 11.2a.625.625 0 1 0 1.202.344l3.2-11.2a.625.625 0 0 0-.43-.773M4.762 4.038a.625.625 0 0 0-.884 0l-3.52 3.52a.625.625 0 0 0 0 .884l3.52 3.52a.625.625 0 1 0 .884-.884L1.684 8l3.078-3.078a.625.625 0 0 0 0-.884m7.36 0a.625.625 0 0 0-.884.884L14.316 8l-3.078 3.078a.625.625 0 0 0 .884.884l3.52-3.52a.625.625 0 0 0 0-.884z" />
  ),
};

export const codeSmallIcon: LoadedIconFunction = createIcon(
  "codeSmall",
  iconDefinition,
);
