// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5 2.375A.625.625 0 0 0 4.375 3v1.375H3a.625.625 0 1 0 0 1.25h1.375V7a.625.625 0 1 0 1.25 0V5.625H7a.625.625 0 1 0 0-1.25H5.625V3A.625.625 0 0 0 5 2.375m7.642.983a.625.625 0 0 0-.884 0l-8.4 8.4a.625.625 0 0 0 .884.884l8.4-8.4a.625.625 0 0 0 0-.884M9 10.375a.625.625 0 1 0 0 1.25h4a.625.625 0 1 0 0-1.25z" />
  ),
};

export const plusForwardSlashMinusSmallIcon: LoadedIconFunction = createIcon(
  "plusForwardSlashMinusSmall",
  iconDefinition,
);
