// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M8.498 2.222c.83-.83 2.175-.83 3.005 0l6.275 6.276c.83.83.83 2.175 0 3.005l-6.275 6.275c-.83.83-2.175.83-3.005 0l-6.276-6.275a2.125 2.125 0 0 1 0-3.005zM10 12.125a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5m0-5.875a.625.625 0 0 0-.625.625v3.5a.625.625 0 1 0 1.25 0v-3.5A.625.625 0 0 0 10 6.25" />
  ),
};

export const exclamationDiamondFillIcon: LoadedIconFunction = createIcon(
  "exclamationDiamondFill",
  iconDefinition,
);
