// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const exclamationDiamondIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "exclamationDiamond",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationDiamond" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationDiamond" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationDiamond" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationDiamond" */
          "./fillSmall.icon"
        ),
    },
  },
  ["rule", "create", "new", "automation", "error", "warning"],
);
