// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.78 3.524a.63.63 0 0 1 .583-.399h9.274a.625.625 0 0 1 0 1.25h-7.66l5.662 5.163a.625.625 0 0 1 0 .924l-5.663 5.163h7.661a.625.625 0 0 1 0 1.25H5.363a.625.625 0 0 1-.421-1.087L11.29 10 4.942 4.212a.625.625 0 0 1-.162-.688" />
  ),
};

export const formulaIcon: LoadedIconFunction = createIcon(
  "formula",
  iconDefinition,
);
