// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.547 3.434a.875.875 0 0 1 .816-.559h9.274a.875.875 0 1 1 0 1.75H7.621l5.186 4.728a.875.875 0 0 1 0 1.294l-5.186 4.728h7.016a.875.875 0 1 1 0 1.75H5.363a.875.875 0 0 1-.59-1.522L10.92 10 4.773 4.397a.875.875 0 0 1-.226-.963" />
  ),
};

export const formulaFillIcon: LoadedIconFunction = createIcon(
  "formulaFill",
  iconDefinition,
);
