// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.32 5.917a.75.75 0 1 0 0 1.5h11.36a.75.75 0 0 0 0-1.5zm0 2.666a.75.75 0 0 0 0 1.5h7.566a.75.75 0 0 0 0-1.5z" />
  ),
};

export const textShortFillSmallIcon: LoadedIconFunction = createIcon(
  "textShortFillSmall",
  iconDefinition,
);
