// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const textShortIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "textShort",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textShort" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textShort" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textShort" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textShort" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "text",
    "shorten",
    "edit",
    "summarize",
    "make shorter",
    "truncate",
    "summary",
    "ai",
  ],
);
