// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.32 6.042a.625.625 0 1 0 0 1.25h11.36a.625.625 0 0 0 0-1.25zm0 2.666a.625.625 0 0 0 0 1.25h7.566a.625.625 0 0 0 0-1.25z" />
  ),
};

export const textShortSmallIcon: LoadedIconFunction = createIcon(
  "textShortSmall",
  iconDefinition,
);
