// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.756 2.655a.875.875 0 0 0-1.512 0L2.079 11.51a.875.875 0 0 0 .756 1.316h10.33a.875.875 0 0 0 .755-1.316zm3.756 8.92H3.488L8 3.84z" />
  ),
};

export const arrowCaretUpSmallIcon: LoadedIconFunction = createIcon(
  "arrowCaretUpSmall",
  iconDefinition,
);
