// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M9.382.408a.625.625 0 0 0-.884.884l.583.583H8a6.125 6.125 0 1 0 4.468 1.936.625.625 0 1 0-.911.855A4.875 4.875 0 1 1 8 3.126h1.08l-.582.582a.625.625 0 0 0 .884.884l1.649-1.65a.625.625 0 0 0 0-.884z" />
      <path d="M8 5.375A.625.625 0 0 0 7.375 6v1.375H6a.625.625 0 1 0 0 1.25h1.375V10a.625.625 0 1 0 1.25 0V8.625H10a.625.625 0 1 0 0-1.25H8.625V6A.625.625 0 0 0 8 5.375" />
    </>
  ),
};

export const goForwardPlusSmallIcon: LoadedIconFunction = createIcon(
  "goForwardPlusSmall",
  iconDefinition,
);
