// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M1.85 8.01a.75.75 0 0 1 .75-.75h10.8a.75.75 0 0 1 0 1.5H2.6a.75.75 0 0 1-.75-.75m0-4a.75.75 0 0 1 .75-.75h10.8a.75.75 0 0 1 0 1.5H2.6a.75.75 0 0 1-.75-.75m.75 7.23a.75.75 0 0 0 0 1.5h10.8a.75.75 0 0 0 0-1.5z" />
  ),
};

export const menuFillSmallIcon: LoadedIconFunction = createIcon(
  "menuFillSmall",
  iconDefinition,
);
