// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.75 2.875a.625.625 0 1 0 0 1.25h9.5a.625.625 0 1 0 0-1.25zm0 7.8a.625.625 0 1 0 0 1.25h9.5a.625.625 0 1 0 0-1.25zm-.625-3.883c0-.727.59-1.317 1.317-1.317h11.116c.727 0 1.317.59 1.317 1.317v1.216c0 .727-.59 1.317-1.317 1.317H4.442c-.727 0-1.317-.59-1.317-1.317zm1.317-.067a.067.067 0 0 0-.067.067v1.216c0 .037.03.067.067.067h11.116c.037 0 .067-.03.067-.067V6.792a.067.067 0 0 0-.067-.067zm0 6.55c-.727 0-1.317.59-1.317 1.317v1.216c0 .727.59 1.317 1.317 1.317h6.689c.727 0 1.317-.59 1.317-1.317v-1.216c0-.727-.59-1.317-1.317-1.317zm-.067 1.317c0-.037.03-.067.067-.067h6.689c.037 0 .067.03.067.067v1.216c0 .037-.03.067-.067.067H4.442a.067.067 0 0 1-.067-.067z" />
  ),
};

export const inlineBlockDoubleIcon: LoadedIconFunction = createIcon(
  "inlineBlockDouble",
  iconDefinition,
);
