// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3 2.175a.625.625 0 1 0 0 1.25h7.6a.625.625 0 1 0 0-1.25zm.5 2.08c-.621 0-1.125.504-1.125 1.125v1.08c0 .621.504 1.125 1.125 1.125h9c.621 0 1.125-.504 1.125-1.125V5.38c0-.621-.504-1.125-1.125-1.125zm.125 2.08v-.83h8.75v.83zM3 8.415a.625.625 0 1 0 0 1.25h7.6a.625.625 0 1 0 0-1.25zm.5 2.08c-.621 0-1.125.504-1.125 1.125v1.08c0 .621.504 1.125 1.125 1.125h5.459c.62 0 1.125-.504 1.125-1.125v-1.08c0-.621-.504-1.125-1.125-1.125zm.125 2.08v-.83h5.209v.83z" />
  ),
};

export const inlineBlockDoubleSmallIcon: LoadedIconFunction = createIcon(
  "inlineBlockDoubleSmall",
  iconDefinition,
);
