// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4 3.375c-1.036 0-1.875.84-1.875 1.875v6.175H1a.075.075 0 0 0-.075.075v.25c0 .594.481 1.075 1.075 1.075h12c.594 0 1.075-.481 1.075-1.075v-.25a.075.075 0 0 0-.075-.075h-1.125V5.25c0-1.036-.84-1.875-1.875-1.875zM3.375 5.25c0-.345.28-.625.625-.625h8c.345 0 .625.28.625.625v6.125h-9.25z" />
  ),
};

export const laptopComputerSmallIcon: LoadedIconFunction = createIcon(
  "laptopComputerSmall",
  iconDefinition,
);
