// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.4 3.235a.625.625 0 0 0-.625.625V5.3a.625.625 0 0 0 1.25 0v-.815h2.35v7.03H6.92a.625.625 0 1 0 0 1.25h2.16a.625.625 0 0 0 0-1.25h-.455v-7.03h2.35V5.3a.625.625 0 1 0 1.25 0V3.86a.625.625 0 0 0-.625-.625z" />
  ),
};

export const textNormalSmallIcon: LoadedIconFunction = createIcon(
  "textNormalSmall",
  iconDefinition,
);
