// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M6 6.625a.875.875 0 1 0 0 1.75h8a.875.875 0 0 0 0-1.75zm0 5a.875.875 0 0 0 0 1.75h8a.875.875 0 0 0 0-1.75z" />
  ),
};

export const equalFillIcon: LoadedIconFunction = createIcon(
  "equalFill",
  iconDefinition,
);
