// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5 5.625a.625.625 0 1 0 0 1.25h6a.625.625 0 1 0 0-1.25zm0 3.5a.625.625 0 1 0 0 1.25h6a.625.625 0 1 0 0-1.25z" />
  ),
};

export const equalSmallIcon: LoadedIconFunction = createIcon(
  "equalSmall",
  iconDefinition,
);
