// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const cloudExclamationIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "cloudExclamation",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-cloudExclamation" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-cloudExclamation" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-cloudExclamation" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-cloudExclamation" */
          "./fillSmall.icon"
        ),
    },
  },
  ["offline", "mode", "internet", "wifi", "sync"],
);
