// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.9 13.226H3A1.826 1.826 0 0 1 1.175 11.4V4.6c0-1.007.817-1.824 1.825-1.825h2.9zM2.925 6.39a.5.5 0 0 0 0 .98l.1.01h1a.5.5 0 0 0 0-1h-1zm0-1.68a.5.5 0 0 0 0 .98l.1.01h1a.5.5 0 0 0 0-1h-1zM13 2.775c1.008 0 1.825.818 1.825 1.826v6.8A1.826 1.826 0 0 1 13 13.225H6.9V2.776z" />
  ),
};

export const sidebarLeftFillSmallIcon: LoadedIconFunction = createIcon(
  "sidebarLeftFillSmall",
  iconDefinition,
);
