// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M7.45 16.375h-3.7a2.125 2.125 0 0 1-2.125-2.125v-8.5c0-1.174.951-2.125 2.125-2.125h3.7zM3.826 8.062a.55.55 0 0 0 0 1.078l.111.01h1.25a.55.55 0 0 0 0-1.1h-1.25zm0-2.101a.55.55 0 0 0 0 1.078l.111.01h1.25a.55.55 0 1 0 0-1.099h-1.25zM16.25 3.625c1.174 0 2.125.951 2.125 2.125v8.5a2.125 2.125 0 0 1-2.125 2.125h-7.7V3.625z" />
  ),
};

export const sidebarLeftFillIcon: LoadedIconFunction = createIcon(
  "sidebarLeftFill",
  iconDefinition,
);
