// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m6.953 12.502 1.76 1.876c.293.375.576.938.846 1.475.179.356.352.7.519.972l.36.741c.322.527.976.741 1.551.527.624-.244.955-.917.77-1.56l-.507-1.775a5.3 5.3 0 0 0-.384-.917c-.138-.278-.276-.556-.376-.887a.404.404 0 0 1 .39-.517h4.095a1.22 1.22 0 0 0 1.218-1.218c0-.42-.224-.78-.555-.995.4-.195.672-.594.672-1.072a1.2 1.2 0 0 0-.819-1.141 1.21 1.21 0 0 0 .459-.936 1.21 1.21 0 0 0-1.21-1.219 1.22 1.22 0 0 0-.868-2.077h-4.308c-.722 0-1.424.166-2.068.488v.01l-1.423.487h-.122zM5.734 4.764v7.088H3.663a.975.975 0 0 1-.975-.975V5.74c0-.538.436-.975.974-.975z" />
  ),
};

export const handThumbsDownFillIcon: LoadedIconFunction = createIcon(
  "handThumbsDownFill",
  iconDefinition,
);
