// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="m5.578 10.183 1.399 1.49c.233.299.458.746.672 1.173.143.283.28.557.413.773l.287.589c.255.418.775.589 1.232.418.496-.194.76-.728.612-1.24l-.403-1.41c-.079-.273-.192-.5-.305-.73-.11-.22-.22-.441-.3-.704a.32.32 0 0 1 .31-.41h3.256a.97.97 0 0 0 .969-.97.94.94 0 0 0-.442-.79.94.94 0 0 0 .534-.852.955.955 0 0 0-.65-.907.96.96 0 0 0 .364-.744.963.963 0 0 0-.961-.969.97.97 0 0 0-.69-1.65H8.45c-.574 0-1.132.131-1.643.387v.008l-1.132.387h-.097zm-.968-.517V4.032H2.913a.727.727 0 0 0-.727.727v4.18c0 .402.326.727.727.727z" />
  ),
};

export const handThumbsDownFillSmallIcon: LoadedIconFunction = createIcon(
  "handThumbsDownFillSmall",
  iconDefinition,
);
