// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M11.762 3.338a2.657 2.657 0 0 0-3.758 0L4.172 7.17a3.673 3.673 0 0 0 5.195 5.195l3.353-3.353a.625.625 0 0 0-.884-.884L8.484 11.48a2.423 2.423 0 1 1-3.427-3.427l3.832-3.832a1.407 1.407 0 0 1 1.99 1.99l-3.832 3.832a.391.391 0 0 1-.553-.553L8.41 7.575a.625.625 0 1 0-.884-.884L5.61 8.607a1.641 1.641 0 1 0 2.321 2.32l3.832-3.831a2.657 2.657 0 0 0 0-3.758" />
  ),
};

export const paperClipSmallIcon: LoadedIconFunction = createIcon(
  "paperClipSmall",
  iconDefinition,
);
