// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.35 4.825a.875.875 0 1 0-1.75 0v10.35a.875.875 0 0 0 1.75 0V10.65h5.9v4.525a.875.875 0 1 0 1.75 0V4.825a.875.875 0 0 0-1.75 0V8.9h-5.9zM17.293 8.33c.084.153.117.32.105.482l.002.063v6.3a.875.875 0 1 1-1.75 0v-4.952l-1.181.644a.875.875 0 1 1-.838-1.536l2.475-1.35a.875.875 0 0 1 1.187.349" />
  ),
};

export const textH1FillIcon: LoadedIconFunction = createIcon(
  "textH1Fill",
  iconDefinition,
);
