// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.53 3.86a.75.75 0 1 0-1.5 0v8.28a.75.75 0 0 0 1.5 0V8.57h4.62v3.57a.75.75 0 0 0 1.5 0V3.86a.75.75 0 1 0-1.5 0v3.21H3.53zm10.348 2.78c.07.13.1.27.09.407l.002.053v5.04a.75.75 0 0 1-1.5 0V8.262l-.871.476a.75.75 0 0 1-.718-1.317l1.98-1.08a.75.75 0 0 1 1.017.299" />
  ),
};

export const textH1FillSmallIcon: LoadedIconFunction = createIcon(
  "textH1FillSmall",
  iconDefinition,
);
