// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.956 15.019a.875.875 0 0 1 0-1.238l2.907-2.906H5.875a.875.875 0 0 1 0-1.75h8.988l-2.907-2.906a.875.875 0 1 1 1.238-1.238l4.4 4.4a.875.875 0 0 1 0 1.238l-4.4 4.4a.875.875 0 0 1-1.238 0m-9.801.831a.875.875 0 1 0 1.75 0V4.15a.875.875 0 1 0-1.75 0z" />
  ),
};

export const arrowFromLineRightFillIcon: LoadedIconFunction = createIcon(
  "arrowFromLineRightFill",
  iconDefinition,
);
