// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M9.618 11.962a.625.625 0 0 1 0-.884l2.453-2.453H4.7a.625.625 0 1 1 0-1.25h7.371L9.618 4.922a.625.625 0 0 1 .884-.884l3.52 3.52a.625.625 0 0 1 0 .884l-3.52 3.52a.625.625 0 0 1-.884 0M1.8 12.68a.625.625 0 0 0 1.25 0V3.32a.625.625 0 1 0-1.25 0z" />
  ),
};

export const arrowFromLineRightSmallIcon: LoadedIconFunction = createIcon(
  "arrowFromLineRightSmall",
  iconDefinition,
);
