// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <g clipPath="url(#clip0_9660_12830)">
        <path d="M12.25.425a.325.325 0 0 0-.325.325v7a.325.325 0 0 0 .325.325h7c.18 0 .325-.145.325-.325A7.325 7.325 0 0 0 12.25.425" />
        <path d="M10 2.675A7.325 7.325 0 1 0 17.325 10 .325.325 0 0 0 17 9.675h-6.675V3A.325.325 0 0 0 10 2.675" />
      </g>
      <defs>
        <clipPath id="clip0_9660_12830">
          <path d="M0 0h20v20H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const chartPieCutoutFillIcon: LoadedIconFunction = createIcon(
  "chartPieCutoutFill",
  iconDefinition,
);
