// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9660_12829)">
        <path d="M9.8.35a.25.25 0 0 0-.25.25v5.6a.25.25 0 0 0 .25.25h5.6a.25.25 0 0 0 .25-.25A5.85 5.85 0 0 0 9.8.35" />
        <path d="M8 2.15A5.85 5.85 0 1 0 13.85 8a.25.25 0 0 0-.25-.25H8.25V2.4A.25.25 0 0 0 8 2.15" />
      </g>
      <defs>
        <clipPath id="clip0_9660_12829">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const chartPieCutoutFillSmallIcon: LoadedIconFunction = createIcon(
  "chartPieCutoutFillSmall",
  iconDefinition,
);
