// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M5.875 4a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0m5 0a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0m1.625 7.625a1.625 1.625 0 1 1 0-3.25 1.625 1.625 0 0 1 0 3.25M5.875 10a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0m6.625 7.625a1.625 1.625 0 1 1 0-3.25 1.625 1.625 0 0 1 0 3.25M5.875 16a1.625 1.625 0 1 0 3.25 0 1.625 1.625 0 0 0-3.25 0" />
  ),
};

export const dragHandleFillIcon: LoadedIconFunction = createIcon(
  "dragHandleFill",
  iconDefinition,
);
