// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M6 4.2a1 1 0 1 1 0-2 1 1 0 0 1 0 2m4 0a1 1 0 1 1 0-2 1 1 0 0 1 0 2M10 9a1 1 0 1 1 0-2 1 1 0 0 1 0 2M6 9a1 1 0 1 1 0-2 1 1 0 0 1 0 2m4 4.8a1 1 0 1 1 0-2 1 1 0 0 1 0 2m-4 0a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
  ),
};

export const dragHandleSmallIcon: LoadedIconFunction = createIcon(
  "dragHandleSmall",
  iconDefinition,
);
