// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M10 8.075a.55.55 0 0 1 .55.55v3.664a1.65 1.65 0 1 1-1.1 0V8.625a.55.55 0 0 1 .55-.55" />
      <path d="M10 2.406a2.9 2.9 0 0 1 2.9 2.9v5.785a4 4 0 1 1-5.8 0V5.307a2.9 2.9 0 0 1 2.9-2.9m0 1.25c-.911 0-1.65.74-1.65 1.65v6.284l-.344.361a2.75 2.75 0 1 0 3.988 0l-.344-.361V5.307A1.65 1.65 0 0 0 10 3.657m5.895 5.679a.55.55 0 0 1 0 1.078l-.11.01h-1.191a.55.55 0 1 1 0-1.099h1.19zm0-2a.55.55 0 0 1 0 1.078l-.11.01h-1.191a.55.55 0 1 1 0-1.099h1.19zm0-2a.55.55 0 0 1 0 1.078l-.11.01h-1.191a.55.55 0 1 1 0-1.099h1.19z" />
    </>
  ),
};

export const thermometerIcon: LoadedIconFunction = createIcon(
  "thermometer",
  iconDefinition,
);
