import type { Template } from "../types";

export const templates: Template[] = [
  {
    id: "flowchart",
    name: "Flowchart",
    description: "Process diagram with decision points",
    preview: "🔄",
    elements: [
      {
        type: "shape",
        shapeType: "rectangle",
        x: 100,
        y: 100,
        width: 150,
        height: 80,
        color: "#e3f2fd",
        content: "Start",
      },
      {
        type: "shape",
        shapeType: "diamond",
        x: 100,
        y: 250,
        width: 150,
        height: 100,
        color: "#fff9c4",
        content: "Decision?",
      },
      {
        type: "shape",
        shapeType: "rectangle",
        x: 300,
        y: 250,
        width: 150,
        height: 80,
        color: "#c8e6c9",
        content: "Yes path",
      },
      {
        type: "shape",
        shapeType: "rectangle",
        x: -100,
        y: 250,
        width: 150,
        height: 80,
        color: "#ffcdd2",
        content: "No path",
      },
    ],
  },
  {
    id: "brainstorm",
    name: "Brainstorm",
    description: "Mind map with sticky notes",
    preview: "💡",
    elements: [
      {
        type: "sticky",
        x: 200,
        y: 200,
        width: 200,
        height: 150,
        color: "#fff9c4",
        text: "Main Idea",
      },
      {
        type: "sticky",
        x: 450,
        y: 100,
        width: 180,
        height: 120,
        color: "#ffccbc",
        text: "Sub-idea 1",
      },
      {
        type: "sticky",
        x: 450,
        y: 250,
        width: 180,
        height: 120,
        color: "#c8e6c9",
        text: "Sub-idea 2",
      },
      {
        type: "sticky",
        x: 450,
        y: 400,
        width: 180,
        height: 120,
        color: "#e1bee7",
        text: "Sub-idea 3",
      },
    ],
  },
  {
    id: "kanban",
    name: "Kanban Board",
    description: "Task management board",
    preview: "📋",
    elements: [
      {
        type: "shape",
        shapeType: "rectangle",
        x: 50,
        y: 50,
        width: 200,
        height: 400,
        color: "#e3f2fd",
        content: "To Do",
      },
      {
        type: "shape",
        shapeType: "rectangle",
        x: 300,
        y: 50,
        width: 200,
        height: 400,
        color: "#fff9c4",
        content: "In Progress",
      },
      {
        type: "shape",
        shapeType: "rectangle",
        x: 550,
        y: 50,
        width: 200,
        height: 400,
        color: "#c8e6c9",
        content: "Done",
      },
    ],
  },
  {
    id: "wireframe",
    name: "Wireframe",
    description: "UI layout mockup",
    preview: "📱",
    elements: [
      {
        type: "shape",
        shapeType: "rectangle",
        x: 100,
        y: 50,
        width: 500,
        height: 60,
        color: "#e3f2fd",
        content: "Header",
      },
      {
        type: "shape",
        shapeType: "rectangle",
        x: 100,
        y: 140,
        width: 150,
        height: 300,
        color: "#f5f5f5",
        content: "Sidebar",
      },
      {
        type: "shape",
        shapeType: "rectangle",
        x: 280,
        y: 140,
        width: 320,
        height: 300,
        color: "#ffffff",
        content: "Main Content",
      },
    ],
  },
];
