import type { Template } from '../types';

export const templates: Template[] = [
  {
    id: 'flowchart',
    name: 'Flowchart',
    description: 'Process diagram with decision points',
    preview: '🔄',
    elements: [
      {
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 100,
        width: 150,
        height: 80,
        color: '#e3f2fd',
        content: 'Start',
      },
      {
        type: 'shape',
        shapeType: 'diamond',
        x: 100,
        y: 220,
        width: 150,
        height: 100,
        color: '#fff3e0',
        content: 'Decision?',
      },
      {
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: 360,
        width: 120,
        height: 70,
        color: '#e8f5e9',
        content: 'Yes',
      },
      {
        type: 'shape',
        shapeType: 'rectangle',
        x: 180,
        y: 360,
        width: 120,
        height: 70,
        color: '#ffebee',
        content: 'No',
      },
      {
        type: 'connector',
        x: 175,
        y: 180,
        width: 0,
        height: 40,
        connectorPoints: [
          { x: 175, y: 180 },
          { x: 175, y: 220 },
        ],
      },
      {
        type: 'connector',
        x: 120,
        y: 320,
        width: 0,
        height: 40,
        connectorPoints: [
          { x: 120, y: 320 },
          { x: 80, y: 360 },
        ],
      },
      {
        type: 'connector',
        x: 230,
        y: 320,
        width: 0,
        height: 40,
        connectorPoints: [
          { x: 230, y: 320 },
          { x: 240, y: 360 },
        ],
      },
    ],
  },
  {
    id: 'mind-map',
    name: 'Mind Map',
    description: 'Central idea with branches',
    preview: '🧠',
    elements: [
      {
        type: 'shape',
        shapeType: 'circle',
        x: 300,
        y: 250,
        width: 120,
        height: 120,
        color: '#f3e5f5',
        content: 'Main Idea',
      },
      {
        type: 'sticky',
        x: 120,
        y: 150,
        width: 120,
        height: 120,
        color: '#fff9c4',
        content: 'Branch 1',
      },
      {
        type: 'sticky',
        x: 500,
        y: 150,
        width: 120,
        height: 120,
        color: '#b2dfdb',
        content: 'Branch 2',
      },
      {
        type: 'sticky',
        x: 120,
        y: 350,
        width: 120,
        height: 120,
        color: '#ffccbc',
        content: 'Branch 3',
      },
      {
        type: 'sticky',
        x: 500,
        y: 350,
        width: 120,
        height: 120,
        color: '#d1c4e9',
        content: 'Branch 4',
      },
      {
        type: 'connector',
        x: 240,
        y: 210,
        width: 120,
        height: 100,
        connectorPoints: [
          { x: 300, y: 290 },
          { x: 240, y: 210 },
        ],
      },
      {
        type: 'connector',
        x: 420,
        y: 210,
        width: 80,
        height: 100,
        connectorPoints: [
          { x: 420, y: 290 },
          { x: 500, y: 210 },
        ],
      },
      {
        type: 'connector',
        x: 240,
        y: 350,
        width: 60,
        height: 60,
        connectorPoints: [
          { x: 300, y: 350 },
          { x: 240, y: 350 },
        ],
      },
      {
        type: 'connector',
        x: 420,
        y: 350,
        width: 80,
        height: 0,
        connectorPoints: [
          { x: 420, y: 350 },
          { x: 500, y: 350 },
        ],
      },
    ],
  },
  {
    id: 'retrospective',
    name: 'Retrospective',
    description: 'What went well, what to improve',
    preview: '📋',
    elements: [
      {
        type: 'text',
        x: 100,
        y: 50,
        width: 200,
        height: 40,
        content: 'What Went Well ✅',
      },
      {
        type: 'sticky',
        x: 100,
        y: 110,
        width: 180,
        height: 100,
        color: '#e8f5e9',
        content: 'Great teamwork',
      },
      {
        type: 'sticky',
        x: 100,
        y: 230,
        width: 180,
        height: 100,
        color: '#e8f5e9',
        content: 'Met deadlines',
      },
      {
        type: 'text',
        x: 350,
        y: 50,
        width: 200,
        height: 40,
        content: 'To Improve 🎯',
      },
      {
        type: 'sticky',
        x: 350,
        y: 110,
        width: 180,
        height: 100,
        color: '#fff9c4',
        content: 'Communication',
      },
      {
        type: 'sticky',
        x: 350,
        y: 230,
        width: 180,
        height: 100,
        color: '#fff9c4',
        content: 'Documentation',
      },
      {
        type: 'text',
        x: 600,
        y: 50,
        width: 200,
        height: 40,
        content: 'Action Items 🚀',
      },
      {
        type: 'sticky',
        x: 600,
        y: 110,
        width: 180,
        height: 100,
        color: '#ffccbc',
        content: 'Weekly sync',
      },
      {
        type: 'sticky',
        x: 600,
        y: 230,
        width: 180,
        height: 100,
        color: '#ffccbc',
        content: 'Setup wiki',
      },
    ],
  },
  {
    id: 'kanban',
    name: 'Kanban Board',
    description: 'Task tracking board',
    preview: '📊',
    elements: [
      {
        type: 'text',
        x: 50,
        y: 50,
        width: 150,
        height: 40,
        content: 'To Do',
      },
      {
        type: 'sticky',
        x: 50,
        y: 110,
        width: 150,
        height: 80,
        color: '#ffebee',
        content: 'Task 1',
      },
      {
        type: 'sticky',
        x: 50,
        y: 210,
        width: 150,
        height: 80,
        color: '#ffebee',
        content: 'Task 2',
      },
      {
        type: 'text',
        x: 250,
        y: 50,
        width: 150,
        height: 40,
        content: 'In Progress',
      },
      {
        type: 'sticky',
        x: 250,
        y: 110,
        width: 150,
        height: 80,
        color: '#fff9c4',
        content: 'Task 3',
      },
      {
        type: 'text',
        x: 450,
        y: 50,
        width: 150,
        height: 40,
        content: 'Done',
      },
      {
        type: 'sticky',
        x: 450,
        y: 110,
        width: 150,
        height: 80,
        color: '#e8f5e9',
        content: 'Task 4',
      },
      {
        type: 'sticky',
        x: 450,
        y: 210,
        width: 150,
        height: 80,
        color: '#e8f5e9',
        content: 'Task 5',
      },
    ],
  },
];
