// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M13.68 3.25a.75.75 0 0 1 0 1.5H6.32a.75.75 0 0 1 0-1.5zm0 2.667a.75.75 0 0 1 0 1.5H6.32a.75.75 0 0 1 0-1.5zM10.35 12a.75.75 0 0 0-.75-.75H6.32a.75.75 0 0 0 0 1.5H9.6a.75.75 0 0 0 .75-.75m3.33-3.417a.75.75 0 0 1 0 1.5H6.32a.75.75 0 1 1 0-1.5zM1.72 6.154l2.306 1.35a.575.575 0 0 1 0 .992L1.72 9.846a.572.572 0 0 1-.86-.496v-2.7c0-.442.478-.72.86-.496" />
  ),
};

export const textIndentFillSmallIcon: LoadedIconFunction = createIcon(
  "textIndentFillSmall",
  iconDefinition,
);
