// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M17.1 4.125a.875.875 0 0 1 0 1.75H7.9a.875.875 0 1 1 0-1.75zm0 3.333a.875.875 0 0 1 0 1.75H7.9a.875.875 0 1 1 0-1.75zM12.875 15a.875.875 0 0 0-.875-.875H7.9a.875.875 0 0 0 0 1.75H12a.875.875 0 0 0 .875-.875m4.225-4.208a.875.875 0 0 1 0 1.75H7.9a.875.875 0 1 1 0-1.75zM1.106 8.312c0-.529.572-.86 1.029-.592l2.881 1.687a.688.688 0 0 1 0 1.186l-2.881 1.688a.684.684 0 0 1-1.03-.593z" />
  ),
};

export const textIndentFillIcon: LoadedIconFunction = createIcon(
  "textIndentFill",
  iconDefinition,
);
