// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.696 3.775a.625.625 0 0 0 0 1.25h7.68a.625.625 0 1 0 0-1.25zm0 3.6a.625.625 0 0 0 0 1.25h7.68a.625.625 0 1 0 0-1.25zM5.071 11.6c0-.345.28-.625.625-.625h7.68a.625.625 0 1 1 0 1.25h-7.68a.625.625 0 0 1-.625-.625M2.896 5.2a.8.8 0 1 0 0-1.6.8.8 0 0 0 0 1.6m.8 2.8a.8.8 0 1 1-1.6 0 .8.8 0 0 1 1.6 0m-.8 4.4a.8.8 0 1 0 0-1.6.8.8 0 0 0 0 1.6" />
  ),
};

export const bulletedListSmallIcon: LoadedIconFunction = createIcon(
  "bulletedListSmall",
  iconDefinition,
);
