// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.87 4.125c-.868 0-1.409.942-.971 1.692l6.13 10.508a1.125 1.125 0 0 0 1.943 0l6.13-10.508a1.125 1.125 0 0 0-.972-1.692z" />
  ),
};

export const arrowCaretDownFillIcon: LoadedIconFunction = createIcon(
  "arrowCaretDownFill",
  iconDefinition,
);
