// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.125 16.13c0 .868.942 1.409 1.692.971l10.508-6.13a1.125 1.125 0 0 0 0-1.943L5.817 2.898a1.125 1.125 0 0 0-1.692.972z" />
  ),
};

export const arrowCaretRightFillIcon: LoadedIconFunction = createIcon(
  "arrowCaretRightFill",
  iconDefinition,
);
