// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.49 2.08a.875.875 0 0 0-1.315.755v10.33a.875.875 0 0 0 1.316.756l8.854-5.165a.875.875 0 0 0 0-1.512zm-.065 10.432V3.488L12.16 8z" />
  ),
};

export const arrowCaretRightSmallIcon: LoadedIconFunction = createIcon(
  "arrowCaretRightSmall",
  iconDefinition,
);
