// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.109 4.61 6.34 11.39H5.12a.75.75 0 0 0 0 1.5h3.6a.75.75 0 0 0 0-1.5h-.83l1.77-6.78h1.22a.75.75 0 0 0 0-1.5h-3.6a.75.75 0 0 0 0 1.5z" />
  ),
};

export const textItalicFillSmallIcon: LoadedIconFunction = createIcon(
  "textItalicFillSmall",
  iconDefinition,
);
