// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m10.218 5.7-2.244 8.6H6.4a.875.875 0 1 0 0 1.75h4.5a.875.875 0 1 0 0-1.75H9.783l2.243-8.6H13.6a.875.875 0 0 0 0-1.75H9.1a.875.875 0 1 0 0 1.75z" />
  ),
};

export const textItalicFillIcon: LoadedIconFunction = createIcon(
  "textItalicFill",
  iconDefinition,
);
