// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M10.88 3.235h-3.6a.625.625 0 0 0 0 1.25h.99l-1.833 7.03H5.12a.625.625 0 1 0 0 1.25h3.6a.625.625 0 0 0 0-1.25h-.991l1.834-7.03h1.317a.625.625 0 1 0 0-1.25" />
  ),
};

export const textItalicSmallIcon: LoadedIconFunction = createIcon(
  "textItalicSmall",
  iconDefinition,
);
