// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.5 4.125A2.125 2.125 0 0 0 2.375 6.25v7.5c0 1.174.951 2.125 2.125 2.125h11a2.125 2.125 0 0 0 2.125-2.125v-7.5A2.125 2.125 0 0 0 15.5 4.125zM3.625 6.25c0-.483.392-.875.875-.875h4.875v9.25H4.5a.875.875 0 0 1-.875-.875zm7 8.375v-9.25H15.5c.483 0 .875.392.875.875v7.5a.875.875 0 0 1-.875.875z" />
  ),
};

export const rectangleSplit2Icon: LoadedIconFunction = createIcon(
  "rectangleSplit2",
  iconDefinition,
);
