// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3 2.193a.75.75 0 0 1 .75.75v5.575l1.626-1.423a.75.75 0 0 1 1.025.034L8.38 9.11l2.784-2.783H10.2a.75.75 0 1 1 0-1.5H13a.75.75 0 0 1 .75.75v2.8a.75.75 0 0 1-1.5 0V7.363l-3.338 3.338a.75.75 0 0 1-1.06 0L5.835 8.686 3.75 10.511v1.239a.5.5 0 0 0 .5.5H13a.75.75 0 0 1 0 1.5H4.25a2 2 0 0 1-2-2V2.943a.75.75 0 0 1 .75-.75" />
  ),
};

export const chartLineUptrendFillSmallIcon: LoadedIconFunction = createIcon(
  "chartLineUptrendFillSmall",
  iconDefinition,
);
