// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3 2.318a.625.625 0 0 0-.625.625v8.807c0 1.036.84 1.875 1.875 1.875H13a.625.625 0 1 0 0-1.25H4.25a.625.625 0 0 1-.625-.625v-1.295l2.217-1.94 2.098 2.098a.625.625 0 0 0 .884 0l3.551-3.551v1.315a.625.625 0 0 0 1.25 0v-2.8A.625.625 0 0 0 13 4.952h-2.8a.625.625 0 0 0 0 1.25h1.267L8.382 9.287l-2.07-2.07a.625.625 0 0 0-.853-.028L3.625 8.794V2.943A.625.625 0 0 0 3 2.318" />
  ),
};

export const chartLineUptrendSmallIcon: LoadedIconFunction = createIcon(
  "chartLineUptrendSmall",
  iconDefinition,
);
