// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10.442 6.558a.625.625 0 0 0-.884 0l-5.4 5.4a.625.625 0 1 0 .884.884L10 7.884l4.958 4.958a.625.625 0 1 0 .884-.884z" />
  ),
};

export const arrowChevronSingleUpIcon: LoadedIconFunction = createIcon(
  "arrowChevronSingleUp",
  iconDefinition,
);
