// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.53 5.07a.75.75 0 0 0-1.06 0L3.15 9.39a.75.75 0 0 0 1.06 1.06L8 6.66l3.79 3.79a.75.75 0 0 0 1.06-1.06z" />
  ),
};

export const arrowChevronSingleUpFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowChevronSingleUpFillSmall",
  iconDefinition,
);
