// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const checkmarkCircleIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "checkmarkCircle",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-checkmarkCircle" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-checkmarkCircle" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-checkmarkCircle" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-checkmarkCircle" */
          "./fillSmall.icon"
        ),
    },
  },
  ["check", "mark", "tick", "confirm", "approve"],
);
