// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M2.2 5.25A1.8 1.8 0 0 1 4 3.45h8a1.8 1.8 0 0 1 1.8 1.8v5.5a1.8 1.8 0 0 1-1.8 1.8H7.343a4 4 0 0 0-.17-1.1H12a.7.7 0 0 0 .7-.7v-5.5a.7.7 0 0 0-.7-.7H4a.7.7 0 0 0-.7.7v3.408q-.576.017-1.1.185z" />
      <path d="M3.4 15.6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-1.666-3.5H2.9v-1.167a.5.5 0 0 1 1 0V12.1h1.167a.5.5 0 0 1 0 1H3.9v1.166a.5.5 0 1 1-1 0V13.1H1.734a.5.5 0 1 1 0-1" />
    </>
  ),
};

export const rectanglePlusSmallIcon: LoadedIconFunction = createIcon(
  "rectanglePlusSmall",
  iconDefinition,
);
