// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="m9.89 10.705 7.985-7.986v-.013a.77.77 0 0 0 0-1.084.77.77 0 0 0-1.083 0L8.793 9.608a1 1 0 0 0-.228.377l-.004.01-.284.916c-.044.166.082.322.232.323a.2.2 0 0 0 .078-.013l.916-.284a.87.87 0 0 0 .387-.232" />
      <path d="M4.825 3.25h8.567L7.91 8.724a2.3 2.3 0 0 0-.523.844l-.01.029-.3.968-.007.024c-.27 1.014.655 2.24 1.906 1.82l.882-.273c.364-.104.67-.301.917-.547l6.697-6.697c.083.245.129.509.129.783v6.75a2.425 2.425 0 0 1-2.425 2.425h-1.231v2.187a.625.625 0 0 1-1.006.496L9.45 14.85H4.825A2.425 2.425 0 0 1 2.4 12.425v-6.75A2.425 2.425 0 0 1 4.825 3.25" />
    </>
  ),
};

export const commentPencilFillIcon: LoadedIconFunction = createIcon(
  "commentPencilFill",
  iconDefinition,
);
