// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M13.978 1.434a.67.67 0 0 0-.946 0l-6.2 6.19a.9.9 0 0 0-.198.328l-.22.713-.001.003c-.054.2.131.402.336.33l.707-.218a.75.75 0 0 0 .332-.2l6.19-6.19a.1.1 0 0 0 .018-.028.673.673 0 0 0-.018-.928" />
      <path d="M4.063 2.869a1.89 1.89 0 0 0-1.888 1.887v5.25c0 1.043.845 1.888 1.888 1.888h3.569l2.551 2.073a.575.575 0 0 0 .938-.447v-1.626h.816a1.887 1.887 0 0 0 1.888-1.888v-5.25c0-.255-.05-.499-.143-.721a.075.075 0 0 0-.122-.024l-.863.863a.08.08 0 0 0-.022.053v5.08c0 .407-.33.737-.738.737h-1.391a.575.575 0 0 0-.575.575v.993l-1.772-1.44a.57.57 0 0 0-.363-.128H4.063a.74.74 0 0 1-.738-.738v-5.25c0-.407.33-.737.738-.737h5.146q.032 0 .053-.022l1.002-1a.075.075 0 0 0-.053-.128z" />
    </>
  ),
};

export const commentPencilSmallIcon: LoadedIconFunction = createIcon(
  "commentPencilSmall",
  iconDefinition,
);
