// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const linkBadgePlusIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "linkBadgePlus",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-linkBadgePlus" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-linkBadgePlus" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-linkBadgePlus" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-linkBadgePlus" */
          "./fillSmall.icon"
        ),
    },
  },
  ["link", "add", "plus", "create", "new"],
);
