// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: <path d="M10 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />,
};

export const dotFillIcon: LoadedIconFunction = createIcon(
  "dotFill",
  iconDefinition,
);
