// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: <path d="M8 6.425a1.575 1.575 0 1 0 0 3.15 1.575 1.575 0 0 0 0-3.15" />,
};

export const dotSmallIcon: LoadedIconFunction = createIcon(
  "dotSmall",
  iconDefinition,
);
