// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.5 3.625c1.174 0 2.125.951 2.125 2.125v7.5a2.125 2.125 0 0 1-2.125 2.125h-4.935l-3.871 2.978a.625.625 0 0 1-1.006-.496v-2.482H4.5a2.125 2.125 0 0 1-2.125-2.125v-7.5c0-1.174.951-2.125 2.125-2.125zM8.913 8.188a.625.625 0 1 0 0 1.25h.462v2.374h-.463a.625.625 0 1 0 0 1.25h2.175a.625.625 0 0 0 0-1.25h-.462v-3A.625.625 0 0 0 10 8.188zM10.8 6.675a.8.8 0 1 0-1.6 0 .8.8 0 0 0 1.6 0" />
  ),
};

export const commentInfoFillIcon: LoadedIconFunction = createIcon(
  "commentInfoFill",
  iconDefinition,
);
