// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m14.16 3.305-2.504 1.537a8 8 0 0 1-1.912.856v6.609c.668.2 1.312.486 1.912.855l2.504 1.537zm1.1 11.808q.072.006.145.006c1.098 0 1.988-.89 1.988-1.989V4.874A1.99 1.99 0 0 0 15.26 2.89zM8.644 5.944q-.6.091-1.213.092H4.226a1.9 1.9 0 0 0-1.9 1.9v2.133a1.9 1.9 0 0 0 1.633 1.881h4.685zM5.79 16.136l-.93-3.086h3.776v2.69c0 .759-.616 1.374-1.375 1.374h-.155a1.375 1.375 0 0 1-1.316-.978" />
  ),
};

export const megaphoneFillIcon: LoadedIconFunction = createIcon(
  "megaphoneFill",
  iconDefinition,
);
