// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 10a7.625 7.625 0 1 1 15.25 0 7.625 7.625 0 0 1-15.25 0m5.975 2.274a.625.625 0 0 0 0 1.25h3.3a.625.625 0 1 0 0-1.25zM13 9.844H7a.625.625 0 0 0 0 1.25h6a.625.625 0 1 0 0-1.25m-7-2.43a.625.625 0 1 0 0 1.25h8a.625.625 0 1 0 0-1.25z" />
  ),
};

export const filterCircleFillIcon: LoadedIconFunction = createIcon(
  "filterCircleFill",
  iconDefinition,
);
