// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 2.125a.625.625 0 0 0-.625.625v7.128L5.378 7.881a.625.625 0 1 0-.884.884l3.064 3.064c.244.244.64.244.884 0l3.065-3.064a.625.625 0 0 0-.884-.884L8.625 9.878V2.75A.625.625 0 0 0 8 2.125m-4.403 10.5a.625.625 0 1 0 0 1.25h8.806a.625.625 0 1 0 0-1.25z" />
  ),
};

export const arrowLineDownSmallIcon: LoadedIconFunction = createIcon(
  "arrowLineDownSmall",
  iconDefinition,
);
