// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const questionMarkSquareDashedIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "questionMarkSquareDashed",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-questionMarkSquareDashed" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-questionMarkSquareDashed" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-questionMarkSquareDashed" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-questionMarkSquareDashed" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "question",
    "query",
    "inquiry",
    "uncertain",
    "unknown",
    "help",
    "circle",
    "empty",
    "missing",
  ],
);
