// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m14.859 6.786.933-.933V5.83a1.16 1.16 0 0 0-.073-1.553 1.16 1.16 0 0 0-1.634 0l-.868.867zm-8.573 8.573 8.091-8.091-1.642-1.643-8.098 8.085c-.156.156-.264.36-.333.548l-.339 1.094-.002.01c-.105.392.257.815.686.667l1.073-.333q.319-.09.564-.337" />
  ),
};

export const pencilFillIcon: LoadedIconFunction = createIcon(
  "pencilFill",
  iconDefinition,
);
