// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.487 3.457a.804.804 0 0 0-1.13 0l-.553.552a.075.075 0 0 0 0 .106l1.03 1.03a.075.075 0 0 0 .106 0l.547-.546a.1.1 0 0 0 .019-.032.804.804 0 0 0-.019-1.11m-2.247 1.22a.075.075 0 0 0-.105 0l-6.337 6.326a1.1 1.1 0 0 0-.237.393l-.269.87v.002c-.063.232.153.466.388.383l.863-.267q.222-.061.398-.239l6.331-6.331a.075.075 0 0 0 0-.106z" />
  ),
};

export const pencilSmallIcon: LoadedIconFunction = createIcon(
  "pencilSmall",
  iconDefinition,
);
