// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M6.337 3.05a.625.625 0 0 0-.003.885L8.828 6.44a.625.625 0 1 0 .886-.882L8.287 4.125H10A5.875 5.875 0 1 1 4.125 10a.625.625 0 1 0-1.25 0A7.125 7.125 0 1 0 10 2.875H8.285l1.44-1.432a.625.625 0 0 0-.882-.886z" />
  ),
};

export const arrowCircleSpinCounterClockwiseIcon: LoadedIconFunction =
  createIcon("arrowCircleSpinCounterClockwise", iconDefinition);
