// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const clockArrow2CirclePathIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "clockArrow2CirclePath",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-clockArrow2CirclePath" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-clockArrow2CirclePath" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-clockArrow2CirclePath" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-clockArrow2CirclePath" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "again",
    "annually",
    "daily",
    "monthly",
    "recur",
    "recurring",
    "repeat",
    "repeating",
    "weekly",
    "yearly",
  ],
);
