// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.45 4a1.8 1.8 0 0 1 1.8-1.8h5.5a1.8 1.8 0 0 1 1.8 1.8v8a1.8 1.8 0 0 1-1.8 1.8h-5.5a1.8 1.8 0 0 1-1.8-1.8zm2.3.25a.5.5 0 0 0 0 1h4.5a.5.5 0 0 0 0-1zm-.5 2.5a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 0-1h-4.5a.5.5 0 0 0-.5.5m.5 1.5a.5.5 0 0 0 0 1H8a.5.5 0 0 0 0-1z" />
  ),
};

export const docPlainTextFillSmallIcon: LoadedIconFunction = createIcon(
  "docPlainTextFillSmall",
  iconDefinition,
);
