// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.343 11.075v-7.96a.75.75 0 1 1 1.5 0v7.96l1.518-1.518a.75.75 0 1 1 1.06 1.06l-2.797 2.799a.75.75 0 0 1-1.061 0l-2.798-2.798a.75.75 0 0 1 1.06-1.06zm7.094-8.491a.75.75 0 0 0-1.06 0l-2.8 2.798a.75.75 0 0 0 1.06 1.06l1.519-1.517v7.96a.75.75 0 0 0 1.5 0v-7.96l1.518 1.518a.75.75 0 1 0 1.06-1.06z" />
  ),
};

export const arrowUpDownFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowUpDownFillSmall",
  iconDefinition,
);
