// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M13 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4" />
      <path d="M4.25 2.45h5.699a3.1 3.1 0 0 0 3.601 3.601v5.699a1.8 1.8 0 0 1-1.8 1.8h-7.5a1.8 1.8 0 0 1-1.8-1.8v-7.5a1.8 1.8 0 0 1 1.8-1.8" />
    </>
  ),
};

export const markUnreadFillSmallIcon: LoadedIconFunction = createIcon(
  "markUnreadFillSmall",
  iconDefinition,
);
