// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const aiCoinIconGroup: IconGroup<"default"> = createIconGroup(
  "aiCoin",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-aiCoin" */
          "./default.icon"
        ),
    },
  },
  ["ai", "coin", "currency", "token", "crypto"],
);
