// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowUpRightSquareIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowUpRightSquare",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpRightSquare" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpRightSquare" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpRightSquare" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpRightSquare" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "arrow",
    "upright",
    "northeast",
    "direction",
    "diagonal",
    "link",
    "external",
  ],
);
