// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M4.535 4.571a2.13 2.13 0 0 1 1.768-.946h7.394c.71 0 1.374.355 1.768.946l2.303 3.454c.171.257.284.547.331.85h-5.99a.625.625 0 0 0-.625.625v.476a1.484 1.484 0 1 1-2.968 0V9.5a.625.625 0 0 0-.625-.625H1.9c.047-.303.16-.593.33-.85z" />
      <path d="M1.875 10.125v4.125c0 1.174.951 2.125 2.125 2.125h12a2.125 2.125 0 0 0 2.125-2.125v-4.125H12.73a2.735 2.735 0 0 1-5.46 0z" />
    </>
  ),
};

export const inboxFillIcon: LoadedIconFunction = createIcon(
  "inboxFill",
  iconDefinition,
);
