// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M13.664 3.05a.625.625 0 0 1 .002.885L11.172 6.44a.625.625 0 1 1-.886-.882l1.427-1.434H10A5.875 5.875 0 1 0 15.875 10a.625.625 0 1 1 1.25 0A7.125 7.125 0 1 1 10 2.875h1.715l-1.44-1.432a.625.625 0 1 1 .882-.886z" />
  ),
};

export const arrowCircleSpinClockwiseIcon: LoadedIconFunction = createIcon(
  "arrowCircleSpinClockwise",
  iconDefinition,
);
