// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M13.84 2.874a.875.875 0 0 1 .003 1.237l-2.494 2.506a.875.875 0 1 1-1.24-1.234l1.002-1.008H10A5.625 5.625 0 1 0 15.625 10a.875.875 0 0 1 1.75 0A7.375 7.375 0 1 1 10 2.625h1.109l-1.01-1.005A.875.875 0 1 1 11.334.38z" />
  ),
};

export const arrowCircleSpinClockwiseFillIcon: LoadedIconFunction = createIcon(
  "arrowCircleSpinClockwiseFill",
  iconDefinition,
);
