// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M11.37 2.22a.75.75 0 0 1 0 1.06L9.495 5.155a.75.75 0 1 1-1.061-1.06l.628-.629H8A4.534 4.534 0 1 0 12.534 8a.716.716 0 1 1 1.432 0A5.966 5.966 0 1 1 8 2.034h1.063l-.628-.629a.75.75 0 0 1 1.06-1.06z" />
  ),
};

export const arrowCircleSpinClockwiseFillSmallIcon: LoadedIconFunction =
  createIcon("arrowCircleSpinClockwiseFillSmall", iconDefinition);
