// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M11.228 2.361a.55.55 0 0 1 0 .778L9.354 5.014a.55.55 0 0 1-.778-.778l.89-.89H8A4.653 4.653 0 1 0 12.653 8a.597.597 0 0 1 1.194 0A5.847 5.847 0 1 1 8 2.153h1.465l-.889-.89a.55.55 0 1 1 .778-.777z" />
  ),
};

export const arrowCircleSpinClockwiseSmallIcon: LoadedIconFunction = createIcon(
  "arrowCircleSpinClockwiseSmall",
  iconDefinition,
);
