// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M6.236 2.382a.75.75 0 0 1 .257 1.029l-2.4 4a.75.75 0 0 1-1.213.102l-1.6-1.867a.75.75 0 0 1 1.14-.976l.922 1.077 1.865-3.108a.75.75 0 0 1 1.029-.257M7.05 5.3a.75.75 0 0 1 .75-.75h6a.75.75 0 0 1 0 1.5h-6a.75.75 0 0 1-.75-.75m.75 4.65a.75.75 0 1 0 0 1.5h6a.75.75 0 0 0 0-1.5zm-4-1.5a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5" />
  ),
};

export const checklistFillSmallIcon: LoadedIconFunction = createIcon(
  "checklistFillSmall",
  iconDefinition,
);
