// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="m4.158 5.492 5.4 5.4c.244.244.64.244.884 0l5.4-5.4a.625.625 0 1 0-.884-.884L10 9.566 5.042 4.608a.625.625 0 0 0-.884.884" />
      <path d="m9.558 16.392-5.4-5.4a.625.625 0 0 1 .884-.884L10 15.066l4.958-4.958a.625.625 0 0 1 .884.884l-5.4 5.4a.625.625 0 0 1-.884 0" />
    </>
  ),
};

export const arrowChevronDoubleDownwardIcon: LoadedIconFunction = createIcon(
  "arrowChevronDoubleDownward",
  iconDefinition,
);
