// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M8.795 3.124a.9.9 0 0 0-1.515-.657L4.498 5.066H2.17a.625.625 0 0 0-.625.625v4.8c0 .345.28.625.625.625h2.328l2.782 2.6a.9.9 0 0 0 1.515-.658zM5.17 6.148 7.545 3.93v8.322L5.17 10.034a.63.63 0 0 0-.426-.168h-1.95v-3.55h1.95c.158 0 .31-.06.426-.168m7.912-2.415a.625.625 0 1 0-1.024.716 6.35 6.35 0 0 1 0 7.284.625.625 0 1 0 1.024.716 7.6 7.6 0 0 0 0-8.716" />
      <path d="M11.05 5.29a.625.625 0 1 0-.961.801 3.124 3.124 0 0 1 0 4 .625.625 0 1 0 .96.8 4.374 4.374 0 0 0 0-5.6" />
    </>
  ),
};

export const volumeOnSmallIcon: LoadedIconFunction = createIcon(
  "volumeOnSmall",
  iconDefinition,
);
