// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M7.268 1.823a3.6 3.6 0 0 0-4.244.403.75.75 0 1 0 1 1.119 2.097 2.097 0 0 1 2.982.19.75.75 0 1 0 1.133-.982 3.6 3.6 0 0 0-.87-.73m1.086 2.213a3.596 3.596 0 0 1 6.19.033.75.75 0 1 1-1.296.756 2.096 2.096 0 0 0-3.607-.018l-4.508 7.527 3.319.537a.75.75 0 1 1-.24 1.481l-4.41-.715a.75.75 0 0 1-.524-1.125zm-3.33 3.248a1.209 1.209 0 1 0 .386-2.386 1.209 1.209 0 0 0-.386 2.386" />
      <path d="M10.393 8.154a1.209 1.209 0 1 0 .387-2.386 1.209 1.209 0 0 0-.387 2.386" />
    </>
  ),
};

export const aiFaceFillSmallIcon: LoadedIconFunction = createIcon(
  "aiFaceFillSmall",
  iconDefinition,
);
