// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M8.652 8.831a.474.474 0 0 1 .713-.462l.064.045 4.99 4.207a.474.474 0 0 1-.251.833l-1.457.165 1.66 2.983a.92.92 0 1 1-1.611.894l-1.608-2.888-.842 1.242a.474.474 0 0 1-.864-.212L8.652 8.83ZM6.2 12.563a.875.875 0 1 1 1.237 1.238l-1.768 1.767a.875.875 0 1 1-1.237-1.237l1.767-1.768Zm-.7-3.438a.875.875 0 1 1 0 1.75H3a.875.875 0 0 1 0-1.75h2.5Zm11.5 0a.875.875 0 0 1 0 1.75h-2.5a.875.875 0 0 1 0-1.75H17ZM4.432 4.432a.875.875 0 0 1 1.237 0l1.768 1.767a.875.875 0 1 1-1.238 1.238L4.432 5.669a.875.875 0 0 1 0-1.237Zm9.899 0a.875.875 0 1 1 1.237 1.237l-1.767 1.768a.875.875 0 1 1-1.238-1.238l1.768-1.767ZM10 2.125c.483 0 .875.392.875.875v2.5a.875.875 0 0 1-1.75 0V3c0-.483.392-.875.875-.875Z" />
    </>
  ),
};

export const cursorClickFillIcon: LoadedIconFunction = createIcon(
  "cursorClickFill",
  iconDefinition,
);
