// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const wifiExclamationMarkIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "wifiExclamationMark",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-wifiExclamationMark" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-wifiExclamationMark" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-wifiExclamationMark" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-wifiExclamationMark" */
          "./fillSmall.icon"
        ),
    },
  },
  ["wifi", "exclamation", "alert", "warning", "connection"],
);
