// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3 2.875a.625.625 0 1 0 0 1.25h14a.625.625 0 1 0 0-1.25zM5.125 7.5c0-1.174.951-2.125 2.125-2.125h5.5c1.174 0 2.125.951 2.125 2.125v5a2.125 2.125 0 0 1-2.125 2.125h-5.5A2.125 2.125 0 0 1 5.125 12.5zm2.125-.875a.875.875 0 0 0-.875.875v5c0 .483.392.875.875.875h5.5a.875.875 0 0 0 .875-.875v-5a.875.875 0 0 0-.875-.875zM2.375 16.5c0-.345.28-.625.625-.625h14a.625.625 0 1 1 0 1.25H3a.625.625 0 0 1-.625-.625" />
  ),
};

export const alignCenterIcon: LoadedIconFunction = createIcon(
  "alignCenter",
  iconDefinition,
);
