// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9869_14385)">
        <path d="M5 2.45a2.55 2.55 0 1 0 0 5.1 2.55 2.55 0 0 0 0-5.1m0 6a2.55 2.55 0 1 0 0 5.1 2.55 2.55 0 0 0 0-5.1m6-6a2.55 2.55 0 1 0 0 5.1 2.55 2.55 0 0 0 0-5.1m0 6a2.55 2.55 0 1 0 0 5.1 2.55 2.55 0 0 0 0-5.1" />
      </g>
      <defs>
        <clipPath id="clip0_9869_14385">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const circleGrid2X2FillSmallIcon: LoadedIconFunction = createIcon(
  "circleGrid2X2FillSmall",
  iconDefinition,
);
