// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.2 5.25A1.8 1.8 0 0 1 4 3.45h8a1.8 1.8 0 0 1 1.8 1.8v5.5a1.8 1.8 0 0 1-1.8 1.8H4a1.8 1.8 0 0 1-1.8-1.8zm2.388.213a.437.437 0 1 0 0 .875h2.625a.437.437 0 1 0 0-.875zM4.15 7.475c0 .241.196.437.438.437H5.9a.437.437 0 1 0 0-.875H4.588a.437.437 0 0 0-.438.438m6.475.434a1.225 1.225 0 1 0 0-2.45 1.225 1.225 0 0 0 0 2.45" />
  ),
};

export const mailFillSmallIcon: LoadedIconFunction = createIcon(
  "mailFillSmall",
  iconDefinition,
);
