// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M14.15 5.26c0-1.381-1.67-2.073-2.646-1.096l-3.34 3.34a.45.45 0 0 1-.637 0l-.999-.999a1.55 1.55 0 0 0-2.192 0L2.304 8.537a1.55 1.55 0 0 0-.454 1.096V11.2c0 .856.694 1.55 1.55 1.55h9.2a1.55 1.55 0 0 0 1.55-1.55z" />
  ),
};

export const graphAreaFillSmallIcon: LoadedIconFunction = createIcon(
  "graphAreaFillSmall",
  iconDefinition,
);
