// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10 2.375a7.625 7.625 0 1 0 0 15.25 7.625 7.625 0 0 0 0-15.25M6.375 8.333c0-.345.28-.625.625-.625h6a.625.625 0 1 1 0 1.25H7a.625.625 0 0 1-.625-.625M7 11.042h6a.625.625 0 0 1 0 1.25H7a.625.625 0 1 1 0-1.25" />
  ),
};

export const equalCircleFillIcon: LoadedIconFunction = createIcon(
  "equalCircleFill",
  iconDefinition,
);
