// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M8.954 12.856a.718.718 0 0 1-1.079-.62V7.764c0-.554.6-.9 1.08-.62l3.833 2.236a.718.718 0 0 1 0 1.24z" />
      <path d="M2.375 10a7.625 7.625 0 1 0 15.25 0 7.625 7.625 0 0 0-15.25 0M10 16.375a6.375 6.375 0 1 1 0-12.75 6.375 6.375 0 0 1 0 12.75" />
    </>
  ),
};

export const arrowTriangleRightCircleIcon: LoadedIconFunction = createIcon(
  "arrowTriangleRightCircle",
  iconDefinition,
);
