// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 14.05a6.05 6.05 0 1 1 0-12.1 6.05 6.05 0 0 1 0 12.1m-.837-3.765 3.067-1.79a.574.574 0 0 0 0-.99l-3.067-1.79a.574.574 0 0 0-.863.496v3.578c0 .443.48.719.863.496" />
  ),
};

export const arrowTriangleRightCircleFillSmallIcon: LoadedIconFunction =
  createIcon("arrowTriangleRightCircleFillSmall", iconDefinition);
