// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M7.201 5.65a.649.649 0 0 0-.976.561v3.578c0 .5.543.813.976.56l3.067-1.788a.65.65 0 0 0 0-1.122z" />
      <path
        fillRule="evenodd"
        d="M8 1.875a6.125 6.125 0 1 1 0 12.25 6.125 6.125 0 0 1 0-12.25M3.125 8a4.875 4.875 0 1 1 9.75 0 4.875 4.875 0 0 1-9.75 0"
        clipRule="evenodd"
      />
    </>
  ),
};

export const arrowTriangleRightCircleSmallIcon: LoadedIconFunction = createIcon(
  "arrowTriangleRightCircleSmall",
  iconDefinition,
);
