// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.25 8A.75.75 0 0 1 5 7.25h6a.75.75 0 0 1 0 1.5H5A.75.75 0 0 1 4.25 8" />
  ),
};

export const dashFillSmallIcon: LoadedIconFunction = createIcon(
  "dashFillSmall",
  iconDefinition,
);
