// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m4.897 3.086-.122-.143a.625.625 0 0 0-.95.814l1.347 1.57c-1.762.91-3.195 2.304-4.083 3.997a1.47 1.47 0 0 0 0 1.362c1.61 3.07 5.011 5.155 8.911 5.155 1.282 0 2.51-.225 3.637-.637l1.588 1.853a.625.625 0 0 0 1.042-.67L4.989 3.229a.6.6 0 0 1-.093-.143m1.778 6.916c0-.784.272-1.505.726-2.074l1.291 1.507a1.426 1.426 0 0 0 1.67 1.948l1.291 1.506a3.326 3.326 0 0 1-4.978-2.887m9.228 4.038a9.4 9.4 0 0 0 3.01-3.354 1.47 1.47 0 0 0 0-1.362C17.302 6.254 13.9 4.169 10 4.169c-.805 0-1.588.089-2.339.257L9.61 6.699a3.326 3.326 0 0 1 3.595 4.194z" />
  ),
};

export const eyeSlashFillIcon: LoadedIconFunction = createIcon(
  "eyeSlashFill",
  iconDefinition,
);
