// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="m4.148 2.661-.23-.269a.55.55 0 1 0-.836.716L4.1 4.294C2.727 5.017 1.61 6.113.914 7.44a1.21 1.21 0 0 0 0 1.128c1.282 2.443 3.987 4.1 7.086 4.1a8.4 8.4 0 0 0 2.854-.493l1.228 1.433a.55.55 0 0 0 .84-.71L4.152 2.666zm1.227 5.34c0-.598.2-1.15.537-1.591l.963 1.123q-.092.218-.094.469a1.22 1.22 0 0 0 1.511 1.184l.963 1.123a2.626 2.626 0 0 1-3.88-2.307m7.475 3.122a7.4 7.4 0 0 0 2.236-2.556 1.21 1.21 0 0 0 0-1.128C13.804 4.997 11.099 3.34 8 3.34a8.5 8.5 0 0 0-1.68.166l1.605 1.87H8a2.626 2.626 0 0 1 2.582 3.101z" />
  ),
};

export const eyeSlashFillSmallIcon: LoadedIconFunction = createIcon(
  "eyeSlashFillSmall",
  iconDefinition,
);
