// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10.619 1.731a.875.875 0 0 0-1.238 0L6.906 4.206a.875.875 0 0 0 1.238 1.238l.98-.982v4.663H4.463l.982-.981a.875.875 0 0 0-1.238-1.238L1.731 9.381a.875.875 0 0 0 0 1.238l2.475 2.475a.875.875 0 0 0 1.238-1.238l-.982-.981h4.663v4.663l-.981-.982a.875.875 0 0 0-1.238 1.238l2.475 2.475a.875.875 0 0 0 1.238 0l2.475-2.475a.875.875 0 1 0-1.238-1.238l-.981.981v-4.662h4.663l-.982.981a.875.875 0 1 0 1.238 1.238l2.475-2.475a.875.875 0 0 0 0-1.238l-2.475-2.475a.875.875 0 1 0-1.238 1.238l.981.98h-4.662V4.463l.981.982a.875.875 0 0 0 1.238-1.238z" />
  ),
};

export const arrowUpDownLeftRightFillIcon: LoadedIconFunction = createIcon(
  "arrowUpDownLeftRightFill",
  iconDefinition,
);
