// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.375 12A2.625 2.625 0 0 0 6 14.625h1.42a.625.625 0 1 1 0 1.25H6a3.875 3.875 0 0 1 0-7.75h9.741l-3.333-3.333a.625.625 0 0 1 .884-.884l4.4 4.4a.625.625 0 0 1 0 .884l-4.4 4.4a.625.625 0 0 1-.884-.884l3.333-3.333H6A2.625 2.625 0 0 0 3.375 12" />
  ),
};

export const arrowUTurnUpRightIcon: LoadedIconFunction = createIcon(
  "arrowUTurnUpRight",
  iconDefinition,
);
