// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M9.75 4.01a.75.75 0 1 1 1.06-1.06l3.52 3.52a.75.75 0 0 1 0 1.06l-3.52 3.52a.75.75 0 0 1-1.06-1.06l2.24-2.24H4.8a1.85 1.85 0 0 0 0 3.7h1.136a.75.75 0 1 1 0 1.5H4.8a3.35 3.35 0 0 1 0-6.7h7.19z" />
  ),
};

export const arrowUTurnUpRightFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowUTurnUpRightFillSmall",
  iconDefinition,
);
