// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M11.8 2.375c1.008 0 1.825.817 1.825 1.825v7.6a1.825 1.825 0 0 1-1.825 1.825H4.2A1.825 1.825 0 0 1 2.375 11.8V4.2c0-1.008.817-1.825 1.825-1.825zm-6.026 2a.626.626 0 0 0-.42 1.087L8.137 8l-2.783 2.538a.625.625 0 0 0 .42 1.087h4.452l.126-.013a.625.625 0 0 0 0-1.224l-.126-.013H7.388l2.097-1.913a.626.626 0 0 0 0-.924L7.388 5.625h2.838l.126-.013a.625.625 0 0 0 0-1.224l-.126-.013z" />
  ),
};

export const inlineEquationFillSmallIcon: LoadedIconFunction = createIcon(
  "inlineEquationFillSmall",
  iconDefinition,
);
