// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const inlineEquationIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "inlineEquation",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-inlineEquation" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-inlineEquation" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-inlineEquation" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-inlineEquation" */
          "./fillSmall.icon"
        ),
    },
  },
  ["formula", "equation", "calculation", "math", "algorithm"],
);
