// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.922 6.652a5.077 5.077 0 1 1 10.155 0v.103a5.18 5.18 0 0 1-1.088 3.177l-3.496 4.501a.625.625 0 0 1-.987 0l-3.495-4.5a5.18 5.18 0 0 1-1.089-3.178zM8 8.502a1.72 1.72 0 1 0 0-3.44 1.72 1.72 0 0 0 0 3.44" />
  ),
};

export const mapPinFillSmallIcon: LoadedIconFunction = createIcon(
  "mapPinFillSmall",
  iconDefinition,
);
