// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.5 1.875a.625.625 0 0 0-.625.625v3c0 .345.28.625.625.625h.875v.42c0 .768.537 1.43 1.289 1.59l4.414.934c.173.036.297.19.297.367v.439H9.5a.625.625 0 0 0-.625.625v3c0 .345.28.625.625.625h3c.345 0 .625-.28.625-.625v-3a.625.625 0 0 0-.625-.625h-.875v-.44c0-.767-.537-1.43-1.289-1.59l-4.414-.933a.375.375 0 0 1-.297-.367v-.42H6.5c.345 0 .625-.28.625-.625v-3a.625.625 0 0 0-.625-.625zm.625 3v-1.75h1.75v1.75zm6 8v-1.75h1.75v1.75z" />
  ),
};

export const connectionsSmallIcon: LoadedIconFunction = createIcon(
  "connectionsSmall",
  iconDefinition,
);
