// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.25 15.375a.875.875 0 1 1 0 1.75h-5a2.375 2.375 0 0 1-2.375-2.375V4.862L4.969 7.77A.875.875 0 1 1 3.73 6.53l4.4-4.4a.875.875 0 0 1 1.238 0l4.4 4.4a.875.875 0 0 1-1.238 1.24L9.625 4.862v9.888c0 .345.28.625.625.625z" />
  ),
};

export const arrowTurnLeftUpFillIcon: LoadedIconFunction = createIcon(
  "arrowTurnLeftUpFill",
  iconDefinition,
);
