// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M7.442 1.758a.625.625 0 0 0-.884 0l-3.52 3.52a.625.625 0 1 0 .884.884l2.453-2.453V11.8c0 1.008.817 1.825 1.825 1.825h4a.625.625 0 1 0 0-1.25h-4a.575.575 0 0 1-.575-.575V3.709l2.453 2.453a.625.625 0 0 0 .884-.884z" />
  ),
};

export const arrowTurnLeftUpSmallIcon: LoadedIconFunction = createIcon(
  "arrowTurnLeftUpSmall",
  iconDefinition,
);
