// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const alarmVibratingIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "alarmVibrating",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-alarmVibrating" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-alarmVibrating" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-alarmVibrating" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-alarmVibrating" */
          "./fillSmall.icon"
        ),
    },
  },
  ["alarm", "clock", "timepiece", "wakeup", "reminder"],
);
