// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M9.45 4.233C7.16 3 4.393 3.2 2.258 4.834a.63.63 0 0 0-.246.497v10.607a.625.625 0 0 0 1.005.496c1.93-1.477 4.469-1.518 6.433-.126zm1.1 12.075c1.964-1.392 4.503-1.35 6.433.126a.625.625 0 0 0 1.005-.497V5.332a.63.63 0 0 0-.246-.497C15.607 3.2 12.84 3 10.55 4.233z" />
  ),
};

export const bookFillIcon: LoadedIconFunction = createIcon(
  "bookFill",
  iconDefinition,
);
