// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v1.5H2.375zM15 6.55a.55.55 0 1 0 0-1.1h-1.437a.55.55 0 0 0 0 1.1zM2.375 8.75h15.25v2.5H2.375zM15.55 10a.55.55 0 0 0-.55-.55h-1.437a.55.55 0 0 0 0 1.1H15a.55.55 0 0 0 .55-.55M2.375 12.25v1.5c0 1.174.951 2.125 2.125 2.125h11a2.125 2.125 0 0 0 2.125-2.125v-1.5zM15 14.55h-1.437a.55.55 0 0 1 0-1.1H15a.55.55 0 1 1 0 1.1" />
  ),
};

export const serverRackFillIcon: LoadedIconFunction = createIcon(
  "serverRackFill",
  iconDefinition,
);
