// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.625 4.535a2.765 2.765 0 0 1 3.307-2.711l.07.014a3.26 3.26 0 0 1 2.01 1.297c.481-.66 1.2-1.14 2.044-1.309 1.706-.34 3.319.96 3.319 2.71 0 .558-.166 1.079-.451 1.514h.776c.87 0 1.575.705 1.575 1.575v1.9c0 .613-.35 1.144-.86 1.404V15.7c0 .87-.706 1.575-1.576 1.575H5.161c-.87 0-1.575-.705-1.575-1.575v-4.77a1.58 1.58 0 0 1-.861-1.405v-1.9c0-.87.705-1.575 1.575-1.575h.777a2.75 2.75 0 0 1-.452-1.515m6 2.765v2.55H15.7c.18 0 .325-.145.325-.325v-1.9A.325.325 0 0 0 15.7 7.3zm-1.25 0H4.3a.325.325 0 0 0-.325.325v1.9c0 .18.145.325.325.325h5.075zm0-1.25V5.038c0-.96-.677-1.786-1.618-1.974l-.07-.014a1.515 1.515 0 1 0-.297 3zm3.25 0c.83-.008 1.5-.683 1.5-1.515 0-.95-.882-1.671-1.824-1.483a2.084 2.084 0 0 0-1.676 2.035v.963zm-2 5.05v4.925h4.214c.18 0 .325-.145.325-.325v-4.6zm-1.25 0h-4.54v4.6c0 .18.146.325.326.325h4.214z" />
  ),
};

export const presentIcon: LoadedIconFunction = createIcon(
  "present",
  iconDefinition,
);
