// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9327_18494)">
        <path d="M5.863 3.985a.575.575 0 0 0-.575.575v.874L4.025 4.171a.575.575 0 0 0-.814.813l1.264 1.264H3.6a.575.575 0 1 0 0 1.15h2.263a.575.575 0 0 0 .575-.575V4.56a.575.575 0 0 0-.575-.575" />
        <path d="M2.8 1.935A1.825 1.825 0 0 0 .975 3.76v5.2c0 1.008.817 1.825 1.825 1.825h3.375v1.455c0 1.008.817 1.825 1.825 1.825h5.2a1.825 1.825 0 0 0 1.825-1.825v-3.4A1.825 1.825 0 0 0 13.2 7.015h-.575V3.76A1.825 1.825 0 0 0 10.8 1.935zM2.225 3.76c0-.318.258-.575.575-.575h8c.318 0 .575.257.575.575v3.255H8A1.825 1.825 0 0 0 6.175 8.84v.695H2.8a.575.575 0 0 1-.575-.575zm5.2 5.08c0-.318.257-.575.575-.575h5.2c.318 0 .575.257.575.575v3.4a.575.575 0 0 1-.575.575H8a.575.575 0 0 1-.575-.575z" />
      </g>
      <defs>
        <clipPath id="clip0_9327_18494">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const pipEnterSmallIcon: LoadedIconFunction = createIcon(
  "pipEnterSmall",
  iconDefinition,
);
