// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.5 4.125A2.125 2.125 0 0 0 2.375 6.25v7.5c0 1.174.951 2.125 2.125 2.125h11a2.125 2.125 0 0 0 2.125-2.125v-7.5A2.125 2.125 0 0 0 15.5 4.125zm5.708 8.804a.625.625 0 0 1 0-.884l1.42-1.42H6.65a.625.625 0 1 1 0-1.25h4.979l-1.42-1.42a.625.625 0 1 1 .883-.884l2.487 2.487a.625.625 0 0 1 0 .884l-2.487 2.487a.625.625 0 0 1-.884 0" />
  ),
};

export const arrowInRectangleRightFillIcon: LoadedIconFunction = createIcon(
  "arrowInRectangleRightFill",
  iconDefinition,
);
