// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M14.25 3.125c-.621 0-1.125.504-1.125 1.125v11.5c0 .621.504 1.125 1.125 1.125h1.5c.621 0 1.125-.504 1.125-1.125V4.25c0-.621-.504-1.125-1.125-1.125zm-5 6.5c-.621 0-1.125.504-1.125 1.125v5c0 .621.504 1.125 1.125 1.125h1.5c.621 0 1.125-.504 1.125-1.125v-5c0-.621-.504-1.125-1.125-1.125zm-5-4c-.621 0-1.125.504-1.125 1.125v9c0 .621.504 1.125 1.125 1.125h1.5c.621 0 1.125-.504 1.125-1.125v-9c0-.621-.504-1.125-1.125-1.125z" />
  ),
};

export const chartBarXAxisFillIcon: LoadedIconFunction = createIcon(
  "chartBarXAxisFill",
  iconDefinition,
);
