// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.756 2.987a.75.75 0 0 1 .257 1.029l-5.244 8.74a.75.75 0 0 1-1.212.102L3.06 8.78a.75.75 0 1 1 1.138-.976l2.82 3.289 4.708-7.848a.75.75 0 0 1 1.029-.257" />
  ),
};

export const checkmarkFillSmallIcon: LoadedIconFunction = createIcon(
  "checkmarkFillSmall",
  iconDefinition,
);
