// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.692 3.094a.625.625 0 0 0-.858.214l-4.798 7.997-2.931-3.42a.625.625 0 0 0-.95.813l3.496 4.079a.625.625 0 0 0 1.011-.085l5.244-8.74a.625.625 0 0 0-.214-.858" />
  ),
};

export const checkmarkSmallIcon: LoadedIconFunction = createIcon(
  "checkmarkSmall",
  iconDefinition,
);
