// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M5.5 11.031a.5.5 0 0 0-.5.5v1.219a.5.5 0 0 0 .5.5h2.011a.5.5 0 0 0 .5-.5v-1.219a.5.5 0 0 0-.5-.5z" />
      <path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v7.5a2.125 2.125 0 0 1-2.125 2.125h-11a2.125 2.125 0 0 1-2.125-2.125zM4.5 5.375a.875.875 0 0 0-.875.875v.825h12.75V6.25a.875.875 0 0 0-.875-.875zm-.875 8.375c0 .483.392.875.875.875h11a.875.875 0 0 0 .875-.875V8.175H3.625z" />
    </>
  ),
};

export const creditCardIcon: LoadedIconFunction = createIcon(
  "creditCard",
  iconDefinition,
);
