// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M4 9.225a.4.4 0 0 1 .4-.4h1.609a.4.4 0 0 1 .4.4v.975a.4.4 0 0 1-.4.4H4.4a.4.4 0 0 1-.4-.4z" />
      <path
        fillRule="evenodd"
        d="M4 3.45a1.8 1.8 0 0 0-1.8 1.8v5.5a1.8 1.8 0 0 0 1.8 1.8h8a1.8 1.8 0 0 0 1.8-1.8v-5.5a1.8 1.8 0 0 0-1.8-1.8zm-.7 1.8a.7.7 0 0 1 .7-.7h8a.7.7 0 0 1 .7.7v.41H3.3zm.7 6.2a.7.7 0 0 1-.7-.7V6.54h9.4v4.21a.7.7 0 0 1-.7.7z"
        clipRule="evenodd"
      />
    </>
  ),
};

export const creditCardSmallIcon: LoadedIconFunction = createIcon(
  "creditCardSmall",
  iconDefinition,
);
