// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.929 4.265a.875.875 0 0 0-1.457.97l2.762 4.143v3.147a.875.875 0 0 0 1.75 0v-3.24l2.7-4.05a.875.875 0 1 0-1.456-.97l-2.15 3.224zm-7.549.03a.875.875 0 1 0-1.422 1.02l2.4 3.35-2.4 3.35a.875.875 0 0 0 1.422 1.02l2.054-2.868 2.054 2.867a.875.875 0 1 0 1.423-1.019l-2.4-3.35 2.4-3.35a.875.875 0 1 0-1.423-1.02L6.434 7.162zm-2.13 10.08a.875.875 0 1 0 0 1.75h.005a.875.875 0 0 0 0-1.75zm1.933 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 0 0 0-1.75zm1.937 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 0 0 0-1.75zm1.938 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 0 0 0-1.75zm1.937 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 1 0 0-1.75zm1.938 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 1 0 0-1.75zm1.937 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 1 0 0-1.75zm1.938 0a.875.875 0 1 0 0 1.75h.01a.875.875 0 1 0 0-1.75zm1.937 0a.875.875 0 1 0 0 1.75h.005a.875.875 0 0 0 0-1.75z" />
  ),
};

export const textXYunderlineFillIcon: LoadedIconFunction = createIcon(
  "textXYunderlineFill",
  iconDefinition,
);
