// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M10.821 10.307 10 8.086l-.821 2.221z" />
      <path d="M5.25 3.125A2.125 2.125 0 0 0 3.125 5.25v9.5c0 1.174.951 2.125 2.125 2.125h9.5a2.125 2.125 0 0 0 2.125-2.125v-9.5a2.125 2.125 0 0 0-2.125-2.125zm6.033 8.432H8.717l-.63 1.707a.625.625 0 0 1-1.173-.433l2.29-6.2a.848.848 0 0 1 1.591 0l2.291 6.2a.625.625 0 0 1-1.172.433z" />
    </>
  ),
};

export const textColorFillIcon: LoadedIconFunction = createIcon(
  "textColorFill",
  iconDefinition,
);
