// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.45 4.25a1.8 1.8 0 0 1 1.8-1.8h7.5a1.8 1.8 0 0 1 1.8 1.8v7.5a1.8 1.8 0 0 1-1.8 1.8h-7.5a1.8 1.8 0 0 1-1.8-1.8zm7.872 2.133a.55.55 0 0 0-.944-.566L7.371 9.163 6.268 7.875a.55.55 0 1 0-.836.716l1.6 1.867a.55.55 0 0 0 .89-.075z" />
  ),
};

export const checkmarkSquareFillSmallIcon: LoadedIconFunction = createIcon(
  "checkmarkSquareFillSmall",
  iconDefinition,
);
