// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9660_12709)">
        <path d="M8.272 4.04a2.35 2.35 0 0 1 4.7 0v2.88a2.35 2.35 0 0 1-4.7 0z" />
        <path d="M6.382 8.545a.55.55 0 0 1 .765.14 4.22 4.22 0 0 0 3.475 1.825c1.44 0 2.713-.722 3.475-1.825a.55.55 0 0 1 .906.625 5.32 5.32 0 0 1-3.831 2.272v1.448h2.69a.55.55 0 0 1 0 1.1h-6.48a.55.55 0 1 1 0-1.1h2.69v-1.448a5.32 5.32 0 0 1-3.83-2.272.55.55 0 0 1 .14-.765m.993-5.295H1.8a.55.55 0 1 0 0 1.1h5.575zM1.8 8.85h3.378c.1.35.244.73.445 1.1H1.8a.55.55 0 0 1 0-1.1" />
        <path d="M1.8 11.65h5.111c-.455.225-.85.571-.96 1.1H1.8a.55.55 0 0 1 0-1.1m0-5.6h5.575v1.1H1.8a.55.55 0 0 1 0-1.1" />
      </g>
      <defs>
        <clipPath id="clip0_9660_12709">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const microphoneTextFillSmallIcon: LoadedIconFunction = createIcon(
  "microphoneTextFillSmall",
  iconDefinition,
);
