// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const microphoneTextIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "microphoneText",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneText" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneText" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneText" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneText" */
          "./fillSmall.icon"
        ),
    },
  },
  ["dictate", "record", "audio", "voice", "speak", "sound", "transcript"],
);
