// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9660_12711)">
        <path d="M10.622 1.615A2.425 2.425 0 0 0 8.197 4.04v2.88a2.425 2.425 0 1 0 4.85 0V4.04a2.425 2.425 0 0 0-2.425-2.425M9.447 4.04a1.175 1.175 0 0 1 2.35 0v2.88a1.175 1.175 0 1 1-2.35 0zM1.8 3.175a.625.625 0 1 0 0 1.25h5.65v-1.25zm0 2.8a.625.625 0 1 0 0 1.25h5.65v-1.25z" />
        <path d="M7.209 8.642a.625.625 0 0 0-1.029.71 5.4 5.4 0 0 0 3.817 2.297v1.306H7.382a.625.625 0 1 0 0 1.25h6.48a.625.625 0 0 0 0-1.25h-2.615v-1.306a5.4 5.4 0 0 0 3.817-2.297.625.625 0 1 0-1.028-.71 4.14 4.14 0 0 1-3.414 1.793A4.14 4.14 0 0 1 7.21 8.642m-5.41.133a.625.625 0 0 0 0 1.25h3.95l-.061-.11a5.4 5.4 0 0 1-.439-1.086l-.015-.054z" />
        <path d="M7.232 11.575H1.8a.625.625 0 1 0 0 1.25h4.212l.012-.06c.103-.496.476-.827.92-1.048z" />
      </g>
      <defs>
        <clipPath id="clip0_9660_12711">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const microphoneTextSmallIcon: LoadedIconFunction = createIcon(
  "microphoneTextSmall",
  iconDefinition,
);
