// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path
      fillRule="evenodd"
      d="M8 14.05a6.05 6.05 0 1 0 0-12.1 6.05 6.05 0 0 0 0 12.1m2.469-6.371a.55.55 0 0 1-.778 0L8.55 6.538v4.252a.55.55 0 0 1-1.1 0V6.538l-1.141 1.14a.55.55 0 1 1-.778-.777l2.08-2.08a.55.55 0 0 1 .778 0l2.08 2.08a.55.55 0 0 1 0 .778"
      clipRule="evenodd"
    />
  ),
};

export const arrowInCircleUpFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowInCircleUpFillSmall",
  iconDefinition,
);
