// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const magnifyingGlassIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "magnifyingGlass",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-magnifyingGlass" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-magnifyingGlass" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-magnifyingGlass" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-magnifyingGlass" */
          "./fillSmall.icon"
        ),
    },
  },
  ["magnifying", "glass", "search", "zoom", "explore"],
);
