// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 1.65a.75.75 0 0 1 .75.75v3.05h3.05a.75.75 0 1 1 0 1.5H8.75V10a.75.75 0 0 1-1.5 0V6.95H4.2a.75.75 0 1 1 0-1.5h3.05V2.4A.75.75 0 0 1 8 1.65m-3.8 11.2a.75.75 0 0 0 0 1.5h7.6a.75.75 0 0 0 0-1.5z" />
  ),
};

export const plusMinusFillSmallIcon: LoadedIconFunction = createIcon(
  "plusMinusFillSmall",
  iconDefinition,
);
