// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10 2.125c.483 0 .875.392.875.875v3.875h3.875a.875.875 0 0 1 0 1.75h-3.875V12.5a.875.875 0 0 1-1.75 0V8.625H5.25a.875.875 0 1 1 0-1.75h3.875V3c0-.483.392-.875.875-.875m-4.75 14a.875.875 0 0 0 0 1.75h9.5a.875.875 0 1 0 0-1.75z" />
  ),
};

export const plusMinusFillIcon: LoadedIconFunction = createIcon(
  "plusMinusFill",
  iconDefinition,
);
