// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 1.775a.625.625 0 0 0-.625.625v3.175H4.2a.625.625 0 1 0 0 1.25h3.175V10a.625.625 0 1 0 1.25 0V6.825H11.8a.625.625 0 1 0 0-1.25H8.625V2.4A.625.625 0 0 0 8 1.775m-3.8 11.2a.625.625 0 0 0 0 1.25h7.6a.625.625 0 0 0 0-1.25z" />
  ),
};

export const plusMinusSmallIcon: LoadedIconFunction = createIcon(
  "plusMinusSmall",
  iconDefinition,
);
