// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M13.22 4.54 8.3 1.82c-.19-.1-.42-.1-.6 0L2.78 4.53c-.2.11-.32.32-.32.55v5.82c0 .23.12.44.32.55l4.92 2.72c.09.05.2.08.3.08s.21-.03.3-.08l4.92-2.72c.2-.11.32-.32.32-.55V5.08c0-.23-.12-.44-.32-.55zM7.37 8.18v4.39L3.7 10.54V6.15zm4.26-3.09L8 7.09l-3.63-2 3.63-2zm.67 1.06v4.39l-3.67 2.03V8.18z" />
  ),
};

export const cubeSmallIcon: LoadedIconFunction = createIcon(
  "cubeSmall",
  iconDefinition,
);
