// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10.206 3.809a4.233 4.233 0 1 1 5.986 5.986l-2.81 2.81-5.986-5.987zM6.618 7.396l-2.81 2.81a4.233 4.233 0 0 0 5.987 5.986l2.81-2.81z" />
  ),
};

export const medicineFillIcon: LoadedIconFunction = createIcon(
  "medicineFill",
  iconDefinition,
);
