// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.076 2.959a3.511 3.511 0 1 1 4.966 4.965l-2.17 2.17L5.906 5.13zM5.128 5.906l-2.17 2.17a3.511 3.511 0 1 0 4.966 4.966l2.17-2.17z" />
  ),
};

export const medicineFillSmallIcon: LoadedIconFunction = createIcon(
  "medicineFillSmall",
  iconDefinition,
);
