// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M13.042 2.959a3.51 3.51 0 0 0-4.966 0L2.96 8.076a3.511 3.511 0 0 0 4.965 4.966l5.118-5.118a3.51 3.51 0 0 0 0-4.965m-4.082.884a2.261 2.261 0 1 1 3.198 3.198l-2.17 2.17L6.79 6.012zM6.012 6.79 9.21 9.988l-2.17 2.17A2.261 2.261 0 0 1 3.842 8.96z" />
  ),
};

export const medicineSmallIcon: LoadedIconFunction = createIcon(
  "medicineSmall",
  iconDefinition,
);
