// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowDiagonalDownLeftUpRightIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowDiagonalDownLeftUpRight",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeftUpRight" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeftUpRight" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeftUpRight" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowDiagonalDownLeftUpRight" */
          "./fillSmall.icon"
        ),
    },
  },
  ["arrows", "upright", "downleft", "diagonal", "directions"],
);
