// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.838 7.088v-2.19L6.67 7.73a.75.75 0 0 0 1.06-1.06L4.9 3.837h2.189a.75.75 0 1 0 0-1.5h-4a.75.75 0 0 0-.75.75v4a.75.75 0 1 0 1.5 0m7.262 5.075-2.829-2.83a.75.75 0 0 1 1.061-1.06l2.829 2.83v-2.19a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75h-4a.75.75 0 0 1 0-1.5z" />
  ),
};

export const arrowExpandDiagonalFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowExpandDiagonalFillSmall",
  iconDefinition,
);
