// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M7.25 2.375A2.125 2.125 0 0 0 5.125 4.5v11c0 1.174.951 2.125 2.125 2.125h5.5a2.125 2.125 0 0 0 2.125-2.125v-11a2.125 2.125 0 0 0-2.125-2.125zM7.375 15c0-.345.28-.625.625-.625h4a.625.625 0 1 1 0 1.25H8A.625.625 0 0 1 7.375 15M9 4.375h2a.625.625 0 1 1 0 1.25H9a.625.625 0 1 1 0-1.25" />
  ),
};

export const iPhoneFillIcon: LoadedIconFunction = createIcon(
  "iPhoneFill",
  iconDefinition,
);
