// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const iPhoneIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup("iPhone", {
  default: {
    loader: () =>
      import(
        /* webpackChunkName: "icon-iPhone" */
        "./default.icon"
      ),
  },
  small: {
    loader: () =>
      import(
        /* webpackChunkName: "icon-iPhone" */
        "./small.icon"
      ),
  },
  fill: {
    loader: () =>
      import(
        /* webpackChunkName: "icon-iPhone" */
        "./fill.icon"
      ),
  },
  fillSmall: {
    loader: () =>
      import(
        /* webpackChunkName: "icon-iPhone" */
        "./fillSmall.icon"
      ),
  },
});
