// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M1.75 4a2.25 2.25 0 1 1 3 2.122V10c0 .69.56 1.25 1.25 1.25h3.878a2.25 2.25 0 1 1 0 1.5H6A2.75 2.75 0 0 1 3.25 10V6.122A2.25 2.25 0 0 1 1.75 4M4 3.25a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5M11.25 12a.75.75 0 1 0 1.5 0 .75.75 0 0 0-1.5 0" />
  ),
};

export const nodeTopLeftBottomRightFillSmallIcon: LoadedIconFunction =
  createIcon("nodeTopLeftBottomRightFillSmall", iconDefinition);
