// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const nodeTopLeftBottomRightIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "nodeTopLeftBottomRight",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-nodeTopLeftBottomRight" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-nodeTopLeftBottomRight" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-nodeTopLeftBottomRight" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-nodeTopLeftBottomRight" */
          "./fillSmall.icon"
        ),
    },
  },
  ["parent", "child", "subtask", "task", "inherit"],
);
