// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 11.6A1.2 1.2 0 1 1 8 14a1.2 1.2 0 0 1 0-2.4m0-4.8a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4M8 2a1.2 1.2 0 1 1 0 2.4A1.2 1.2 0 0 1 8 2" />
  ),
};

export const ellipsisVerticalFillSmallIcon: LoadedIconFunction = createIcon(
  "ellipsisVerticalFillSmall",
  iconDefinition,
);
