// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10 14.375a1.625 1.625 0 1 1 0 3.25 1.625 1.625 0 0 1 0-3.25m0-6a1.625 1.625 0 1 1 0 3.25 1.625 1.625 0 0 1 0-3.25m0-6a1.625 1.625 0 1 1 0 3.25 1.625 1.625 0 0 1 0-3.25" />
  ),
};

export const ellipsisVerticalFillIcon: LoadedIconFunction = createIcon(
  "ellipsisVerticalFill",
  iconDefinition,
);
