// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.22 8.53a.75.75 0 0 1 0-1.06l4.32-4.32A.75.75 0 0 1 7.6 4.21L4.56 7.25h8.737c.388 0 .703.336.703.75s-.315.75-.703.75H4.56l3.04 3.04a.75.75 0 0 1-1.061 1.06z" />
  ),
};

export const arrowStraightLeftFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowStraightLeftFillSmall",
  iconDefinition,
);
