// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_10940_20701)">
        <path d="M12.625 11.225h.575A1.825 1.825 0 0 0 15.025 9.4V4.2A1.825 1.825 0 0 0 13.2 2.375h-8A1.825 1.825 0 0 0 3.375 4.2v.575H2.8A1.825 1.825 0 0 0 .975 6.6v2.89c.37-.288.792-.512 1.25-.655V6.6c0-.318.258-.575.575-.575h.575v2.632H3.4c.428 0 .84.068 1.225.194V4.2c0-.318.257-.575.575-.575h8c.318 0 .575.257.575.575v5.2a.575.575 0 0 1-.575.575H6.342c.324.363.582.786.755 1.25h4.278v.575a.575.575 0 0 1-.575.575H7.337a4 4 0 0 1-.129 1.25H10.8a1.825 1.825 0 0 0 1.825-1.825z" />
        <path d="M3.4 15.6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-1.667-3.5H2.9v-1.166a.5.5 0 0 1 1 0V12.1h1.166a.5.5 0 0 1 0 1H3.9v1.167a.5.5 0 0 1-1 0V13.1H1.733a.5.5 0 0 1 0-1" />
      </g>
      <defs>
        <clipPath id="clip0_10940_20701">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const rectangleOnRectanglePlusSmallIcon: LoadedIconFunction = createIcon(
  "rectangleOnRectanglePlusSmall",
  iconDefinition,
);
