// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_11285_16732)">
        <path d="M2.036 2.5a.625.625 0 0 0-.625.625c0 4.762 3.494 8.735 7.937 8.735h2.912a25 25 0 0 1 1.758 2.209.549.549 0 1 0 .89-.641c-.725-1.01-1.367-1.805-2.01-2.495C12.754 6.308 9.314 2.5 4.965 2.5zm9.453 7.077c-.943-.82-2.002-1.595-3.395-2.614l-.819-.6a.547.547 0 0 0-.767.118.553.553 0 0 0 .12.77l.81.593C8.95 8.951 10.04 9.75 11.001 10.61H9.348c-3.451 0-6.379-2.966-6.664-6.86h2.281c3.14 0 5.845 2.454 6.524 5.827" />
      </g>
      <defs>
        <clipPath id="clip0_11285_16732">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const leafSmallIcon: LoadedIconFunction = createIcon(
  "leafSmall",
  iconDefinition,
);
