// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.25 2.45a1.8 1.8 0 0 0-1.8 1.8v7.5a1.8 1.8 0 0 0 1.8 1.8h7.5a1.8 1.8 0 0 0 1.8-1.8v-7.5a1.8 1.8 0 0 0-1.8-1.8zM8 5.075a.55.55 0 0 1 .55.55V7.45h1.825a.55.55 0 1 1 0 1.1H8.55v1.825a.55.55 0 0 1-1.1 0V8.55H5.625a.55.55 0 0 1 0-1.1H7.45V5.625a.55.55 0 0 1 .55-.55" />
  ),
};

export const addSquareRoundedFillSmallIcon: LoadedIconFunction = createIcon(
  "addSquareRoundedFillSmall",
  iconDefinition,
);
