// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M6.5 12.7a.95.95 0 0 1-.95-.95v-6.5a.95.95 0 0 1 .95-.95h10a.95.95 0 0 1 .95.95v6.5a.95.95 0 0 1-.95.95z" />
      <path d="M4.45 11.75A2.05 2.05 0 0 0 6.5 13.8h7.95v.95a.95.95 0 0 1-.95.95h-10a.95.95 0 0 1-.95-.95v-6.5a.95.95 0 0 1 .95-.95h.95z" />
    </>
  ),
};

export const rectangleOnRectangleFillIcon: LoadedIconFunction = createIcon(
  "rectangleOnRectangleFill",
  iconDefinition,
);
