// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m17.619 9.381-5.4-5.4A.875.875 0 1 0 10.98 5.22l3.907 3.906H2.934c-.447 0-.809.392-.809.875s.362.875.809.875h11.954l-3.907 3.906a.875.875 0 1 0 1.238 1.238l5.4-5.4a.875.875 0 0 0 0-1.238" />
  ),
};

export const arrowStraightRightFillIcon: LoadedIconFunction = createIcon(
  "arrowStraightRightFill",
  iconDefinition,
);
