// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.4 2.25a.55.55 0 1 0 0 1.1h11.2a.55.55 0 1 0 0-1.1zm1.2 2A1.75 1.75 0 0 0 1.85 6v4c0 .966.784 1.75 1.75 1.75H8A1.75 1.75 0 0 0 9.75 10V6A1.75 1.75 0 0 0 8 4.25zM1.85 13.2a.55.55 0 0 1 .55-.55h11.2a.55.55 0 0 1 0 1.1H2.4a.55.55 0 0 1-.55-.55" />
  ),
};

export const alignLeftFillSmallIcon: LoadedIconFunction = createIcon(
  "alignLeftFillSmall",
  iconDefinition,
);
