// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_10821_27934)">
        <path d="M10.689 5.203c2.364 0 4.282 2.09 4.771 5.202.11.69.165 1.474.165 2.328 0 .171-.07.326-.18.44a.622.622 0 0 1-.994-.121c-1.337-2.33-3.548-2.269-3.776-2.258v2.342a.623.623 0 0 1-.625.625.62.62 0 0 1-.413-.156L3.88 8.528a.626.626 0 0 1-.005-.933L9.631 2.4a.626.626 0 0 1 1.044.464z" />
        <path d="m1.939 8.061 1.175 1.035.033.038q.047.058.103.11l4.13 3.643v.249a.624.624 0 0 1-1.039.469L.587 8.535a.623.623 0 0 1-.006-.932l5.754-5.195a.626.626 0 0 1 1.044.464v.274l-4.143 3.74-.009.01-.008.01z" />
      </g>
      <defs>
        <clipPath id="clip0_10821_27934">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const arrowShapeDoubleUpLeftFillSmallIcon: LoadedIconFunction =
  createIcon("arrowShapeDoubleUpLeftFillSmall", iconDefinition);
