// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowShapeDoubleUpLeftIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowShapeDoubleUpLeft",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowShapeDoubleUpLeft" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowShapeDoubleUpLeft" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowShapeDoubleUpLeft" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowShapeDoubleUpLeft" */
          "./fillSmall.icon"
        ),
    },
  },
  ["reply all", "reply", "all", "email", "respond"],
);
