// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M6.25 4.01a.75.75 0 0 0-1.06-1.06L1.67 6.47a.75.75 0 0 0 0 1.06l3.52 3.52a.75.75 0 1 0 1.06-1.06L4.01 7.75h7.19a1.85 1.85 0 1 1 0 3.7h-1.136a.75.75 0 1 0 0 1.5H11.2a3.35 3.35 0 0 0 0-6.7H4.01z" />
  ),
};

export const arrowUTurnUpLeftFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowUTurnUpLeftFillSmall",
  iconDefinition,
);
