// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.9 2a.5.5 0 0 0 0 1h4.2a.5.5 0 0 0 0-1zM4 4.25a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m.263 1.2a1.8 1.8 0 0 0-1.8 1.8v4.85a1.8 1.8 0 0 0 1.8 1.8h7.475a1.8 1.8 0 0 0 1.8-1.8V7.25a1.8 1.8 0 0 0-1.8-1.8z" />
  ),
};

export const stackFillSmallIcon: LoadedIconFunction = createIcon(
  "stackFillSmall",
  iconDefinition,
);
