// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M10.779 3.547a1.375 1.375 0 0 0-1.558 0L3.346 7.583c-.373.256-.596.68-.596 1.133v6.034c0 1.036.84 1.875 1.875 1.875h2.716c.759 0 1.375-.616 1.375-1.375v-4.19c0-.069.055-.125.125-.125h2.319c.069 0 .124.056.124.125v4.19c0 .76.616 1.375 1.375 1.375h2.716c1.035 0 1.875-.84 1.875-1.875V8.716c0-.453-.223-.877-.596-1.133z" />
  ),
};

export const homeFillIcon: LoadedIconFunction = createIcon(
  "homeFill",
  iconDefinition,
);
