// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.623 2.838a1.1 1.1 0 0 0-1.246 0l-4.7 3.228a1.1 1.1 0 0 0-.477.907v4.777c0 .856.694 1.55 1.55 1.55h2.172c.58 0 1.05-.47 1.05-1.05V8.848a.1.1 0 0 1 .1-.1h1.856a.1.1 0 0 1 .1.1v3.402c0 .58.47 1.05 1.05 1.05h2.172a1.55 1.55 0 0 0 1.55-1.55V6.973a1.1 1.1 0 0 0-.477-.907z" />
  ),
};

export const homeFillSmallIcon: LoadedIconFunction = createIcon(
  "homeFillSmall",
  iconDefinition,
);
