import type { GraphData } from "./types";

export const mockGraphData: GraphData = {
  nodes: [
    { id: "1", label: "Product Roadmap", link: "/product-roadmap" },
    { id: "2", label: "Q1 Goals", link: "/q1-goals" },
    { id: "3", label: "Q2 Goals", link: "/q2-goals" },
    { id: "4", label: "Design System", link: "/design-system" },
    { id: "5", label: "API Docs", link: "/api-docs" },
    { id: "6", label: "User Research", link: "/user-research" },
    { id: "7", label: "Feature Specs", link: "/feature-specs" },
    { id: "8", label: "Engineering Blog", link: "/engineering-blog" },
    { id: "9", label: "Team Handbook", link: "/team-handbook" },
    { id: "10", label: "Meeting Notes", link: "/meeting-notes" },
    { id: "11", label: "Sprint Planning", link: "/sprint-planning" },
    { id: "12", label: "Architecture", link: "/architecture" },
    { id: "13", label: "Testing Guide", link: "/testing-guide" },
    { id: "14", label: "Deploy Process", link: "/deploy-process" },
    { id: "15", label: "Onboarding", link: "/onboarding" },
  ],
  edges: [
    { source: "1", target: "2" },
    { source: "1", target: "3" },
    { source: "2", target: "7" },
    { source: "3", target: "7" },
    { source: "4", target: "7" },
    { source: "5", target: "12" },
    { source: "6", target: "7" },
    { source: "7", target: "11" },
    { source: "8", target: "5" },
    { source: "8", target: "12" },
    { source: "9", target: "15" },
    { source: "10", target: "11" },
    { source: "11", target: "14" },
    { source: "12", target: "13" },
    { source: "12", target: "14" },
    { source: "13", target: "14" },
    { source: "15", target: "9" },
  ],
};
