import type { GraphData } from "./types";

export const mockGraphData: GraphData = {
  nodes: [
    { id: "product-roadmap", label: "Product Roadmap", link: "/product-roadmap", type: "planning" },
    { id: "q1-goals", label: "Q1 Goals", link: "/q1-goals", type: "planning" },
    { id: "q2-goals", label: "Q2 Goals", link: "/q2-goals", type: "planning" },
    { id: "design-system", label: "Design System", link: "/design-system", type: "design" },
    { id: "api-docs", label: "API Documentation", link: "/api-docs", type: "technical" },
    { id: "user-research", label: "User Research", link: "/user-research", type: "research" },
    { id: "feature-auth", label: "Authentication Feature", link: "/feature-auth", type: "feature" },
    { id: "feature-dashboard", label: "Dashboard Feature", link: "/feature-dashboard", type: "feature" },
    { id: "feature-search", label: "Search Feature", link: "/feature-search", type: "feature" },
    { id: "tech-stack", label: "Tech Stack", link: "/tech-stack", type: "technical" },
    { id: "team-handbook", label: "Team Handbook", link: "/team-handbook", type: "documentation" },
    { id: "sprint-planning", label: "Sprint Planning", link: "/sprint-planning", type: "planning" },
    { id: "ux-guidelines", label: "UX Guidelines", link: "/ux-guidelines", type: "design" },
    { id: "performance-metrics", label: "Performance Metrics", link: "/performance-metrics", type: "analytics" },
    { id: "customer-feedback", label: "Customer Feedback", link: "/customer-feedback", type: "research" },
  ],
  edges: [
    { source: "product-roadmap", target: "q1-goals" },
    { source: "product-roadmap", target: "q2-goals" },
    { source: "q1-goals", target: "feature-auth" },
    { source: "q1-goals", target: "feature-dashboard" },
    { source: "q2-goals", target: "feature-search" },
    { source: "design-system", target: "ux-guidelines" },
    { source: "design-system", target: "feature-dashboard" },
    { source: "design-system", target: "feature-search" },
    { source: "api-docs", target: "feature-auth" },
    { source: "api-docs", target: "tech-stack" },
    { source: "user-research", target: "customer-feedback" },
    { source: "user-research", target: "ux-guidelines" },
    { source: "feature-auth", target: "tech-stack" },
    { source: "feature-dashboard", target: "performance-metrics" },
    { source: "sprint-planning", target: "q1-goals" },
    { source: "sprint-planning", target: "q2-goals" },
    { source: "team-handbook", target: "sprint-planning" },
  ],
};
