// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M12.25 2.25h-8a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h.5V8A3.25 3.25 0 0 1 8 4.75h6.25v-.5a2 2 0 0 0-2-2" />
      <path d="M8 6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2z" />
    </>
  ),
};

export const duplicateFillIcon: LoadedIconFunction = createIcon(
  "duplicateFill",
  iconDefinition,
);
