// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.74 2.45a1.29 1.29 0 0 0-1.29 1.29v8.52c0 .712.578 1.29 1.29 1.29h2.593a1.29 1.29 0 0 0 1.291-1.29V3.74a1.29 1.29 0 0 0-1.29-1.29zm5.927 0a1.29 1.29 0 0 0-1.291 1.29v2.593a1.29 1.29 0 0 0 1.29 1.291h2.593a1.29 1.29 0 0 0 1.29-1.29V3.74a1.29 1.29 0 0 0-1.29-1.291zm0 5.926a1.29 1.29 0 0 0-1.291 1.29v2.593a1.29 1.29 0 0 0 1.29 1.291h2.593a1.29 1.29 0 0 0 1.29-1.29V9.666a1.29 1.29 0 0 0-1.29-1.291z" />
  ),
};

export const layoutFillSmallIcon: LoadedIconFunction = createIcon(
  "layoutFillSmall",
  iconDefinition,
);
