// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.825 3.3c-.842 0-1.525.683-1.525 1.525v10.35c0 .842.683 1.525 1.525 1.525h3.15c.842 0 1.525-.683 1.525-1.525V4.825c0-.842-.683-1.525-1.525-1.525zm7.2 0c-.842 0-1.525.683-1.525 1.525v3.15c0 .842.683 1.525 1.525 1.525h3.15c.842 0 1.525-.683 1.525-1.525v-3.15c0-.842-.683-1.525-1.525-1.525zm0 7.2c-.842 0-1.525.683-1.525 1.525v3.15c0 .842.683 1.525 1.525 1.525h3.15c.842 0 1.525-.683 1.525-1.525v-3.15c0-.842-.683-1.525-1.525-1.525z" />
  ),
};

export const layoutFillIcon: LoadedIconFunction = createIcon(
  "layoutFill",
  iconDefinition,
);
