// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowChevronSingleDownIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowChevronSingleDown",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronSingleDown" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronSingleDown" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronSingleDown" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronSingleDown" */
          "./fillSmall.icon"
        ),
    },
  },
  ["chevron", "down", "arrow", "direction", "downward"],
);
