// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const keyboardDownIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "keyboardDown",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-keyboardDown" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-keyboardDown" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-keyboardDown" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-keyboardDown" */
          "./fillSmall.icon"
        ),
    },
  },
  ["type", "keys", "input", "computer", "hide", "unfocus"],
);
