// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const xMarkSealIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "xMarkSeal",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-xMarkSeal" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-xMarkSeal" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-xMarkSeal" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-xMarkSeal" */
          "./fillSmall.icon"
        ),
    },
  },
  ["x", "seal", "reject", "deny", "cancel"],
);
