// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M9.698 2.196a.68.68 0 0 1 .604 0l1.89.945a7.4 7.4 0 0 0 3.32.784h.788c.373 0 .675.302.675.675v6.933a5.18 5.18 0 0 1-3.136 4.756l-3.573 1.531a.68.68 0 0 1-.532 0l-3.572-1.53a5.18 5.18 0 0 1-3.137-4.757V4.6c0-.373.302-.675.675-.675h.788c1.153 0 2.29-.268 3.32-.784zm3.178 5.782a.625.625 0 0 0-1.072-.643L9.25 11.59 7.815 9.916a.625.625 0 0 0-.95.814l2 2.333a.625.625 0 0 0 1.011-.085z" />
  ),
};

export const checkmarkShieldFillIcon: LoadedIconFunction = createIcon(
  "checkmarkShieldFill",
  iconDefinition,
);
