// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.9 4.125a.875.875 0 1 0 0 1.75h14.2a.875.875 0 1 0 0-1.75zm0 3.333a.875.875 0 1 0 0 1.75h14.2a.875.875 0 0 0 0-1.75zM2.025 15c0-.483.392-.875.875-.875H10a.875.875 0 1 1 0 1.75H2.9A.875.875 0 0 1 2.025 15m.875-4.208a.875.875 0 1 0 0 1.75h14.2a.875.875 0 1 0 0-1.75z" />
  ),
};

export const textJustifyLeftFillIcon: LoadedIconFunction = createIcon(
  "textJustifyLeftFill",
  iconDefinition,
);
