// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const textH2ToggleIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "textH2Toggle",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textH2Toggle" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textH2Toggle" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textH2Toggle" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-textH2Toggle" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "format",
    "text",
    "heading",
    "subhead",
    "title",
    "headline",
    "large",
    "medium",
  ],
);
