// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9672_13864)">
        <path d="M4.956 3.695a.625.625 0 0 0-.625.625v7.36a.625.625 0 1 0 1.25 0V8.465h4.19v3.215a.625.625 0 0 0 1.25 0V4.32a.625.625 0 1 0-1.25 0v2.895h-4.19V4.32a.625.625 0 0 0-.625-.625m8.621 2.68c-.85 0-1.623.485-1.932 1.224a.575.575 0 0 0 1.061.443c.114-.272.442-.517.871-.517.575 0 .923.4.923.75 0 .156-.06.308-.178.439l-2.725 2.546a.575.575 0 0 0 .393.995h3.2a.575.575 0 0 0 0-1.15h-1.743l1.675-1.565.025-.025c.31-.328.503-.76.503-1.24 0-1.112-.998-1.9-2.073-1.9M2.786 7.535l-1.52-.913a.543.543 0 0 0-.822.466v1.824c0 .422.46.683.822.466l1.52-.913a.543.543 0 0 0 0-.93" />
      </g>
      <defs>
        <clipPath id="clip0_9672_13864">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const textH2ToggleSmallIcon: LoadedIconFunction = createIcon(
  "textH2ToggleSmall",
  iconDefinition,
);
