// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.375 5.413a4.5 4.5 0 0 1-.152-1.177c0-1.482.673-2.683 1.504-2.683.741 0 1.357.957 1.481 2.217.898-.62 1.846-.767 2.318-.296.471.472.323 1.42-.296 2.318 1.26.123 2.217.74 2.217 1.481 0 .83-1.202 1.504-2.683 1.504-.422 0-.822-.055-1.177-.152a3.23 3.23 0 0 1-1.378 3.606l-9.234 5.853c-1.345.852-2.912-.714-2.059-2.06L7.77 6.791a3.23 3.23 0 0 1 3.606-1.378m.517 1.708a1.976 1.976 0 0 0-3.067.339l-.175.276 1.232 1.232a.55.55 0 1 1-.778.778L8.046 8.688l-.466.736 1.306 1.307a.55.55 0 1 1-.778.778l-1.132-1.132-4.004 6.317a.23.23 0 0 0-.042.16.26.26 0 0 0 .075.14.26.26 0 0 0 .141.076c.038.005.09.002.16-.042l3.221-2.042-.561-.561a.55.55 0 1 1 .778-.778l.735.736 5.06-3.208a1.976 1.976 0 0 0 .34-3.067z" />
  ),
};

export const carrotIcon: LoadedIconFunction = createIcon(
  "carrot",
  iconDefinition,
);
