// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.223 4.236c0 .422.054.821.152 1.177A3.23 3.23 0 0 0 7.769 6.79l-.025.039 2.138 2.138a.55.55 0 1 1-.778.778L7.141 7.782l-.467.737 2.212 2.212a.55.55 0 1 1-.778.778L6.07 9.47l-4.154 6.553c-.853 1.346.714 2.912 2.06 2.06l3.457-2.192-1.467-1.467a.55.55 0 1 1 .778-.778l1.641 1.641 4.824-3.057a3.23 3.23 0 0 0 1.378-3.606c.355.097.755.152 1.177.152 1.481 0 2.683-.673 2.683-1.504 0-.741-.958-1.358-2.217-1.481.62-.898.767-1.846.296-2.318-.472-.471-1.42-.323-2.318.296-.124-1.26-.74-2.217-1.481-2.217-.83 0-1.504 1.201-1.504 2.683" />
  ),
};

export const carrotFillIcon: LoadedIconFunction = createIcon(
  "carrotFill",
  iconDefinition,
);
