// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const carrotIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "carrot",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-carrot" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-carrot" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-carrot" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-carrot" */
          "./fillSmall.icon"
        ),
    },
  },
  ["emoji", "picker", "food", "cuisine", "dining", "dinner", "vegetable"],
);
