// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.45 5.925a.625.625 0 0 0 0 .884l3.499 3.497a.625.625 0 1 0 .884-.883L5.402 6.992h10.705a.625.625 0 0 0 0-1.25H5.402l2.43-2.431a.625.625 0 0 0-.883-.884zm8.717 11.648a.625.625 0 0 1 0-.884l2.431-2.43H3.893a.625.625 0 1 1 0-1.25h10.705l-2.43-2.431a.625.625 0 0 1 .883-.884l3.498 3.497a.625.625 0 0 1 0 .884l-3.498 3.498a.625.625 0 0 1-.884 0" />
  ),
};

export const arrowLeftRightIcon: LoadedIconFunction = createIcon(
  "arrowLeftRight",
  iconDefinition,
);
