// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M11.075 11.657h-7.96a.75.75 0 0 1 0-1.5h7.96L9.557 8.639a.75.75 0 1 1 1.06-1.06l2.799 2.797a.75.75 0 0 1 0 1.061l-2.798 2.798a.75.75 0 0 1-1.06-1.06zM2.584 4.563a.75.75 0 0 0 0 1.06l2.798 2.799a.75.75 0 0 0 1.06-1.06l-1.516-1.52h7.96a.75.75 0 0 0 0-1.5h-7.96l1.518-1.517a.75.75 0 0 0-1.06-1.061z" />
  ),
};

export const arrowLeftRightFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowLeftRightFillSmall",
  iconDefinition,
);
