// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3.274 5.748a.875.875 0 0 0 0 1.237l3.498 3.498a.875.875 0 0 0 1.237-1.237L6.005 7.242h10.102a.875.875 0 0 0 0-1.75H6.005L8.01 3.488A.875.875 0 1 0 6.772 2.25zM11.99 17.75a.875.875 0 0 1 0-1.238l2.005-2.004H3.893a.875.875 0 0 1 0-1.75h10.102l-2.004-2.004a.875.875 0 1 1 1.237-1.237l3.498 3.498a.875.875 0 0 1 0 1.237l-3.498 3.498a.875.875 0 0 1-1.237 0" />
  ),
};

export const arrowLeftRightFillIcon: LoadedIconFunction = createIcon(
  "arrowLeftRightFill",
  iconDefinition,
);
