// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const browserClickIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "browserClick",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserClick" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserClick" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserClick" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserClick" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "browser",
    "chrome",
    "safari",
    "pointer",
    "cursor",
    "firefox",
    "windows",
    "mac",
  ],
);
