// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.2 5.25A1.8 1.8 0 0 1 4 3.45h8a1.8 1.8 0 0 1 1.8 1.8v5.5a1.8 1.8 0 0 1-1.8 1.8H4a1.8 1.8 0 0 1-1.8-1.8zM5.3 6.3a.25.25 0 0 0-.25.25v2.9c0 .138.112.25.25.25h5.4a.25.25 0 0 0 .25-.25v-2.9a.25.25 0 0 0-.25-.25z" />
  ),
};

export const peekCenterFillSmallIcon: LoadedIconFunction = createIcon(
  "peekCenterFillSmall",
  iconDefinition,
);
