// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M13.869 10.619a.875.875 0 0 0 0-1.238l-5.4-5.4A.875.875 0 0 0 7.23 5.22L12.012 10 7.23 14.782a.875.875 0 0 0 1.24 1.238z" />
  ),
};

export const arrowChevronSingleRightFillIcon: LoadedIconFunction = createIcon(
  "arrowChevronSingleRightFill",
  iconDefinition,
);
