// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v7.5a2.125 2.125 0 0 1-2.125 2.125h-11a2.125 2.125 0 0 1-2.125-2.125zm3.125.725a.55.55 0 1 0 0 1.1h5.85a.55.55 0 0 0 0-1.1zM6.525 10c0 .304.246.55.55.55h5.85a.55.55 0 1 0 0-1.1h-5.85a.55.55 0 0 0-.55.55m1.9 1.925a.55.55 0 1 0 0 1.1h5.85a.55.55 0 0 0 0-1.1z" />
  ),
};

export const viewTimelineFillIcon: LoadedIconFunction = createIcon(
  "viewTimelineFill",
  iconDefinition,
);
