// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <g clipPath="url(#clip0_9041_11326)">
        <path d="M6.25 2.375A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125h4.923a4.75 4.75 0 0 1 4.702-7.741V4.5a2.125 2.125 0 0 0-2.125-2.125zM6.7 5.75a.55.55 0 0 1 .55-.55h5.5a.55.55 0 0 1 0 1.1h-5.5a.55.55 0 0 1-.55-.55m.55 3.05a.55.55 0 1 1 0-1.1h5.5a.55.55 0 0 1 0 1.1z" />
        <path d="M11.125 14.5a3.625 3.625 0 1 1 6.576 2.105l1.27 1.483a.625.625 0 1 1-.941.823l-1.222-1.427a3.625 3.625 0 0 1-5.683-2.984m3.625-2.375a2.375 2.375 0 1 0 0 4.75 2.375 2.375 0 0 0 0-4.75" />
      </g>
      <defs>
        <clipPath id="clip0_9041_11326">
          <path d="M0 0h20v20H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const docTextMagnifyingGlassFillIcon: LoadedIconFunction = createIcon(
  "docTextMagnifyingGlassFill",
  iconDefinition,
);
