// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M12.541 6.125a2.376 2.376 0 1 0 0-1.75H6.313a3.25 3.25 0 1 0 0 6.5h7.562a1.5 1.5 0 0 1 0 3H7.459a2.376 2.376 0 1 0 0 1.75h6.416a3.25 3.25 0 0 0 0-6.5H6.313a1.5 1.5 0 1 1 0-3zm1.584-.875a.625.625 0 1 1 1.25 0 .625.625 0 0 1-1.25 0" />
  ),
};

export const pathRoundEndsFillIcon: LoadedIconFunction = createIcon(
  "pathRoundEndsFill",
  iconDefinition,
);
