// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const pathRoundEndsIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "pathRoundEnds",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-pathRoundEnds" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-pathRoundEnds" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-pathRoundEnds" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-pathRoundEnds" */
          "./fillSmall.icon"
        ),
    },
  },
  ["workflow", "connection", "sync", "route", "process"],
);
