// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const waveformSlashIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "waveformSlash",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-waveformSlash" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-waveformSlash" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-waveformSlash" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-waveformSlash" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "wave",
    "form",
    "signal",
    "audio",
    "visualization",
    "soundwave",
    "mute",
    "volume",
  ],
);
