// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.442 1.158a.625.625 0 0 0-.884 0l-4.2 4.2a.625.625 0 0 0 .884.884L8 2.484l3.758 3.758a.625.625 0 0 0 .884-.884L8.445 1.16zm4.2 8.6a.625.625 0 0 0-.884 0L8 13.516 4.242 9.758a.625.625 0 1 0-.884.884l4.2 4.2c.244.244.64.244.884 0l.005-.005 4.195-4.195a.625.625 0 0 0 0-.884" />
  ),
};

export const arrowChevronDoubleUpAndDownSmallIcon: LoadedIconFunction =
  createIcon("arrowChevronDoubleUpAndDownSmall", iconDefinition);
