// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M2.4 3.65a.75.75 0 0 0 0 1.5h11.2a.75.75 0 0 0 0-1.5zm1.7 5.094h7.8a.75.75 0 0 0 0-1.5H4.1a.75.75 0 0 0 0 1.5m.95 2.856a.75.75 0 0 1 .75-.75h4.4a.75.75 0 0 1 0 1.5H5.8a.75.75 0 0 1-.75-.75" />
  ),
};

export const filterFillSmallIcon: LoadedIconFunction = createIcon(
  "filterFillSmall",
  iconDefinition,
);
