// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M3 4.625a.875.875 0 1 0 0 1.75h14a.875.875 0 0 0 0-1.75zm2.125 6.242h9.75a.875.875 0 0 0 0-1.75h-9.75a.875.875 0 1 0 0 1.75m1.25 3.633c0-.483.392-.875.875-.875h5.5a.875.875 0 0 1 0 1.75h-5.5a.875.875 0 0 1-.875-.875" />
  ),
};

export const filterFillIcon: LoadedIconFunction = createIcon(
  "filterFill",
  iconDefinition,
);
