// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4 2.975c-1.036 0-1.875.84-1.875 1.875v5.5c0 1.036.84 1.875 1.875 1.875h2.325v.75H5.2a.625.625 0 1 0 0 1.25h5.6a.625.625 0 1 0 0-1.25H9.675v-.75H12c1.036 0 1.875-.84 1.875-1.875v-5.5c0-1.035-.84-1.875-1.875-1.875zM3.375 4.85c0-.345.28-.625.625-.625h8c.345 0 .625.28.625.625v5.5c0 .345-.28.625-.625.625H4a.625.625 0 0 1-.625-.625z" />
  ),
};

export const displaySmallIcon: LoadedIconFunction = createIcon(
  "displaySmall",
  iconDefinition,
);
