// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.597 2.125a.625.625 0 1 0 0 1.25h8.806a.625.625 0 1 0 0-1.25zm4.845 2.046a.625.625 0 0 0-.884 0L4.493 7.235a.625.625 0 1 0 .884.884l1.998-1.997v7.128a.625.625 0 1 0 1.25 0V6.122l1.997 1.997a.625.625 0 0 0 .884-.884z" />
  ),
};

export const arrowLineUpSmallIcon: LoadedIconFunction = createIcon(
  "arrowLineUpSmall",
  iconDefinition,
);
