// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <g clipPath="url(#clip0_9208_17166)">
        <path d="M8.125 14.75c0-.345.28-.625.625-.625h10.1a.625.625 0 0 1 0 1.25H8.75a.625.625 0 0 1-.625-.625M7 9.375a.625.625 0 1 0 0 1.25h10.1a.625.625 0 1 0 0-1.25zm-1.75-4.75a.625.625 0 0 0 0 1.25h10.1a.625.625 0 1 0 0-1.25zM2.9 9.375a.625.625 0 1 0 0 1.25h1.5a.625.625 0 1 0 0-1.25zM.525 5.25c0-.345.28-.625.625-.625h1.5a.625.625 0 0 1 0 1.25h-1.5a.625.625 0 0 1-.625-.625m4.125 8.875a.625.625 0 0 0 0 1.25h1.5a.625.625 0 1 0 0-1.25z" />
      </g>
      <defs>
        <clipPath id="clip0_9208_17166">
          <path d="M0 0h20v20H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const tableOfContentsIcon: LoadedIconFunction = createIcon(
  "tableOfContents",
  iconDefinition,
);
