// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9208_17163)">
        <path d="M6.55 11.69a.75.75 0 0 1 .75-.75h7.8a.75.75 0 0 1 0 1.5H7.3a.75.75 0 0 1-.75-.75M5.6 7.26a.75.75 0 1 0 0 1.5h7.8a.75.75 0 1 0 0-1.5zm-1.7-3.7a.75.75 0 0 0 0 1.5h7.8a.75.75 0 0 0 0-1.5zm-1.3 3.7a.75.75 0 1 0 0 1.5h1a.75.75 0 0 0 0-1.5zM.15 4.31a.75.75 0 0 1 .75-.75h1a.75.75 0 0 1 0 1.5h-1a.75.75 0 0 1-.75-.75m4.15 6.63a.75.75 0 0 0 0 1.5h1a.75.75 0 0 0 0-1.5z" />
      </g>
      <defs>
        <clipPath id="clip0_9208_17163">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const tableOfContentsFillSmallIcon: LoadedIconFunction = createIcon(
  "tableOfContentsFillSmall",
  iconDefinition,
);
