// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <g clipPath="url(#clip0_9208_17164)">
        <path d="M7.875 14.75c0-.483.392-.875.875-.875h10.1a.875.875 0 0 1 0 1.75H8.75a.875.875 0 0 1-.875-.875M7 9.125a.875.875 0 1 0 0 1.75h10.1a.875.875 0 1 0 0-1.75zm-1.75-4.75a.875.875 0 1 0 0 1.75h10.1a.875.875 0 0 0 0-1.75zM2.9 9.125a.875.875 0 1 0 0 1.75h1.5a.875.875 0 1 0 0-1.75zM.275 5.25c0-.483.392-.875.875-.875h1.5a.875.875 0 1 1 0 1.75h-1.5a.875.875 0 0 1-.875-.875m4.375 8.625a.875.875 0 0 0 0 1.75h1.5a.875.875 0 0 0 0-1.75z" />
      </g>
      <defs>
        <clipPath id="clip0_9208_17164">
          <path d="M0 0h20v20H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const tableOfContentsFillIcon: LoadedIconFunction = createIcon(
  "tableOfContentsFill",
  iconDefinition,
);
