// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M1.95 8a6.05 6.05 0 1 1 12.1 0 6.05 6.05 0 0 1-12.1 0m5-1.425a.55.55 0 0 0 0 1.1h.5v2.4h-.5a.55.55 0 1 0 0 1.1h2.1a.55.55 0 0 0 0-1.1h-.5v-2.95a.55.55 0 0 0-.55-.55zM8.6 5.2a.7.7 0 1 0-1.4 0 .7.7 0 0 0 1.4 0" />
  ),
};

export const infoCircleFillSmallIcon: LoadedIconFunction = createIcon(
  "infoCircleFillSmall",
  iconDefinition,
);
