// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const displayAndArrowDownIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "displayAndArrowDown",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-displayAndArrowDown" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-displayAndArrowDown" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-displayAndArrowDown" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-displayAndArrowDown" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "monitor",
    "down arrow",
    "computer",
    "download",
    "screen",
    "desktop",
    "device",
    "downward",
  ],
);
