// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M6.8 3.035a2.245 2.245 0 0 1 2.553.106l4.442 3.355c.936.707.995 2.07.176 2.858l-.176.15-4.442 3.354c-.8.605-1.905.605-2.705 0L2.205 9.504a1.885 1.885 0 0 1 0-3.008L6.648 3.14z" />
  ),
};

export const layerSingleFillSmallIcon: LoadedIconFunction = createIcon(
  "layerSingleFillSmall",
  iconDefinition,
);
