// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M8.403 4.052a2.65 2.65 0 0 1 3.193 0l5.553 4.192.106.085a2.2 2.2 0 0 1-.106 3.427l-5.553 4.192a2.65 2.65 0 0 1-3.193 0L2.85 11.756a2.2 2.2 0 0 1 0-3.512z" />
  ),
};

export const layerSingleFillIcon: LoadedIconFunction = createIcon(
  "layerSingleFill",
  iconDefinition,
);
