// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M6.8 3.035a2.245 2.245 0 0 1 2.553.107l4.442 3.354c.936.707.995 2.07.176 2.858l-.176.15-4.442 3.354a2.244 2.244 0 0 1-2.706 0L2.205 9.504a1.884 1.884 0 0 1 0-3.008l4.442-3.354zM8.6 4.14a.995.995 0 0 0-1.2 0L2.958 7.493a.635.635 0 0 0 0 1.014L7.4 11.86a.995.995 0 0 0 1.2 0l4.442-3.354.059-.051a.635.635 0 0 0-.059-.963z" />
  ),
};

export const layerSingleSmallIcon: LoadedIconFunction = createIcon(
  "layerSingleSmall",
  iconDefinition,
);
