// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.14 4.485h3.491l-4.073 4.073a.625.625 0 0 0 .884.884l4.073-4.073v3.49a.625.625 0 1 0 1.25 0v-5a.625.625 0 0 0-.625-.624h-5a.625.625 0 1 0 0 1.25M4.485 14.631l4.07-4.07a.625.625 0 0 1 .884.884l-4.07 4.07h3.49a.625.625 0 1 1 0 1.25h-5a.625.625 0 0 1-.624-.625v-5a.625.625 0 1 1 1.25 0z" />
  ),
};

export const arrowExpandDiagonalBottomLeftToTopRightIcon: LoadedIconFunction =
  createIcon("arrowExpandDiagonalBottomLeftToTopRight", iconDefinition);
