// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.912 3.838h2.19L8.27 6.669A.75.75 0 0 0 9.33 7.73l2.832-2.83v2.189a.75.75 0 0 0 1.5 0v-4a.75.75 0 0 0-.75-.75h-4a.75.75 0 1 0 0 1.5m-5.074 7.262 2.829-2.829a.75.75 0 0 1 1.06 1.06L4.9 12.163h2.189a.75.75 0 0 1 0 1.5h-4a.75.75 0 0 1-.75-.75v-4a.75.75 0 1 1 1.5 0z" />
  ),
};

export const arrowExpandDiagonalBottomLeftToTopRightFillSmallIcon: LoadedIconFunction =
  createIcon(
    "arrowExpandDiagonalBottomLeftToTopRightFillSmall",
    iconDefinition,
  );
