// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8.75 2.676C8.75 2.303 8.414 2 8 2s-.75.303-.75.676v8.763L4.21 8.4a.75.75 0 0 0-1.06 1.06l4.32 4.32a.75.75 0 0 0 1.06 0l4.32-4.32a.75.75 0 1 0-1.06-1.06l-3.04 3.04z" />
  ),
};

export const arrowStraightDownFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowStraightDownFillSmall",
  iconDefinition,
);
