// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9672_13859)">
        <path d="M5.207 3.57a.75.75 0 0 1 .75.75v2.77h3.94V4.32a.75.75 0 1 1 1.5 0v7.36a.75.75 0 0 1-1.5 0V8.59h-3.94v3.09a.75.75 0 0 1-1.5 0V4.32a.75.75 0 0 1 .75-.75m9.903 3.586a.625.625 0 0 0-.923-.595l-1.76.96a.625.625 0 0 0 .599 1.098l.836-.456v3.517a.625.625 0 1 0 1.25 0V7.2q0-.023-.002-.044M1.515 9.536a.65.65 0 0 1-.984-.558V7.022a.65.65 0 0 1 .984-.558l1.631.978a.65.65 0 0 1 0 1.116z" />
      </g>
      <defs>
        <clipPath id="clip0_9672_13859">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const textH1ToggleFillSmallIcon: LoadedIconFunction = createIcon(
  "textH1ToggleFillSmall",
  iconDefinition,
);
