// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_9672_13855)">
        <path d="M5.207 3.695a.625.625 0 0 0-.625.625v7.36a.625.625 0 1 0 1.25 0V8.465h4.19v3.215a.625.625 0 0 0 1.25 0V4.32a.625.625 0 1 0-1.25 0v2.895h-4.19V4.32a.625.625 0 0 0-.625-.625m9.785 3.14a.575.575 0 0 0-.78-.23l-1.76.96a.575.575 0 1 0 .55 1.01l.91-.496v3.601a.575.575 0 0 0 1.15 0V7.2q0-.023-.002-.044a.57.57 0 0 0-.069-.32m-11.955.699-1.52-.913a.543.543 0 0 0-.822.466v1.824c0 .422.46.683.822.466l1.52-.913a.543.543 0 0 0 0-.93" />
      </g>
      <defs>
        <clipPath id="clip0_9672_13855">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const textH1ToggleSmallIcon: LoadedIconFunction = createIcon(
  "textH1ToggleSmall",
  iconDefinition,
);
