// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M11.955 2.426c-2.816-.788-4.873-.47-6.007.873-.887 1.05-1.016 2.513-.723 3.95h-1.38a.75.75 0 1 0 0 1.5h1.807c.348 1.252.217 1.999-.076 2.478-.344.563-1.042.978-2.172 1.302A.75.75 0 0 0 3.611 14h8.61a.75.75 0 0 0 0-1.5H6.489q.203-.225.367-.49c.535-.876.636-1.958.342-3.261h3.6a.75.75 0 0 0 0-1.5H6.763c-.335-1.307-.189-2.367.33-2.982.554-.655 1.826-1.133 4.458-.397a.75.75 0 0 0 .404-1.444" />
  ),
};

export const poundSignFillSmallIcon: LoadedIconFunction = createIcon(
  "poundSignFillSmall",
  iconDefinition,
);
