// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <g clipPath="url(#clip0_10430_11058)">
        <path d="M18.541 4.528a3.83 3.83 0 0 0-5.255 1.319l-5.275 8.809a.873.873 0 0 0 .61 1.31l4.582.743a.873.873 0 0 0 .28-1.724l-3.312-.537 4.614-7.704a2.084 2.084 0 0 1 3.587.018.873.873 0 1 0 1.509-.88 3.8 3.8 0 0 0-1.34-1.354" />
        <path d="M15.5 10.084a1.164 1.164 0 1 0 .372-2.298 1.164 1.164 0 0 0-.373 2.298m-7.736-6.14a3.83 3.83 0 0 1 5.45.348.873.873 0 1 1-1.32 1.144 2.086 2.086 0 0 0-2.965-.19.873.873 0 1 1-1.165-1.302M9.92 9.18a1.164 1.164 0 1 0 .372-2.299A1.164 1.164 0 0 0 9.92 9.18M.873 10.79H8.58l-1.046 1.747H.874a.873.873 0 0 1 0-1.747M.873 7.463h6.76A2.53 2.53 0 0 0 7.86 9.21H.873a.873.873 0 1 1 0-1.747m5.731 6.654H.874a.873.873 0 1 0 0 1.747h5.64a2.37 2.37 0 0 1 .09-1.747m-.25-8.235a2.37 2.37 0 0 1-.334-1.747H.873a.873.873 0 1 0 0 1.747z" />
      </g>
      <defs>
        <clipPath id="clip0_10430_11058">
          <path d="M0 0h20v20H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const aiDescriptionFillIcon: LoadedIconFunction = createIcon(
  "aiDescriptionFill",
  iconDefinition,
);
