// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_10430_11057)">
        <path d="M14.816 3.607a3.096 3.096 0 0 0-4.246 1.065l-4.194 7.003a.744.744 0 0 0 .519 1.117l3.644.59a.744.744 0 1 0 .238-1.468l-2.561-.415 3.63-6.062a1.608 1.608 0 0 1 2.767.013.744.744 0 1 0 1.285-.75 3.1 3.1 0 0 0-1.082-1.093" />
        <path d="M12.372 8.066a.926.926 0 1 0 .297-1.827.926.926 0 0 0-.297 1.827M6.189 3.148a3.097 3.097 0 0 1 4.403.281.744.744 0 0 1-1.124.975 1.61 1.61 0 0 0-2.287-.146.744.744 0 1 1-.992-1.11m1.747 4.199a.926.926 0 1 0 .296-1.828.926.926 0 0 0-.296 1.828M.744 8.578H6.93l-.891 1.488H.744a.744.744 0 1 1 0-1.488m0-2.646H6.13a2 2 0 0 0 .195 1.488H.744a.744.744 0 1 1 0-1.488m4.608 5.291H.744a.744.744 0 1 0 0 1.488h4.529a1.86 1.86 0 0 1 .079-1.488m-.187-6.448a1.86 1.86 0 0 1-.293-1.488H.744a.744.744 0 0 0 0 1.488z" />
      </g>
      <defs>
        <clipPath id="clip0_10430_11057">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const aiDescriptionFillSmallIcon: LoadedIconFunction = createIcon(
  "aiDescriptionFillSmall",
  iconDefinition,
);
