// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.375 4.75a.625.625 0 1 0-1.25 0v5c0 1.174.951 2.125 2.125 2.125h10.491l-3.333 3.333a.625.625 0 0 0 .884.884l4.4-4.4a.625.625 0 0 0 0-.884l-4.4-4.4a.625.625 0 0 0-.884.884l3.333 3.333H5.25a.875.875 0 0 1-.875-.875z" />
  ),
};

export const arrowTurnDownRightIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownRight",
  iconDefinition,
);
