// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.75 3.8a.75.75 0 0 0-1.5 0v4A1.95 1.95 0 0 0 4.2 9.75h7.79l-2.24 2.24a.75.75 0 1 0 1.06 1.06l3.52-3.52a.75.75 0 0 0 0-1.06l-3.52-3.52a.75.75 0 0 0-1.06 1.06l2.24 2.24H4.2a.45.45 0 0 1-.45-.45z" />
  ),
};

export const arrowTurnDownRightFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownRightFillSmall",
  iconDefinition,
);
