// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.625 4.75a.875.875 0 1 0-1.75 0v5a2.375 2.375 0 0 0 2.375 2.375h9.888l-2.907 2.906a.875.875 0 1 0 1.238 1.238l4.4-4.4a.875.875 0 0 0 0-1.238l-4.4-4.4A.875.875 0 1 0 12.23 7.47l2.906 2.906H5.25a.625.625 0 0 1-.625-.625z" />
  ),
};

export const arrowTurnDownRightFillIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownRightFill",
  iconDefinition,
);
