// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3 3.175a.625.625 0 0 0-.625.625v4c0 1.008.817 1.825 1.825 1.825h8.091l-2.453 2.453a.625.625 0 0 0 .884.884l3.52-3.52a.625.625 0 0 0 0-.884l-3.52-3.52a.625.625 0 0 0-.884.884l2.453 2.453H4.2a.575.575 0 0 1-.575-.575v-4A.625.625 0 0 0 3 3.175" />
  ),
};

export const arrowTurnDownRightSmallIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownRightSmall",
  iconDefinition,
);
