// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M6.25 2.375A2.125 2.125 0 0 0 4.125 4.5v11c0 1.174.951 2.125 2.125 2.125h7.5a2.125 2.125 0 0 0 2.125-2.125v-1.062h-1.25V15.5a.875.875 0 0 1-.875.875h-7.5a.875.875 0 0 1-.875-.875v-11c0-.483.392-.875.875-.875h7.5c.483 0 .875.392.875.875v1.125h1.25V4.5a2.125 2.125 0 0 0-2.125-2.125z" />
      <path d="M17.942 9.558a.625.625 0 0 1 0 .884l-2.5 2.5a.625.625 0 1 1-.884-.884l1.408-1.408H10a.625.625 0 1 1 0-1.25h6.016l-1.458-1.458a.625.625 0 1 1 .884-.884z" />
    </>
  ),
};

export const arrowRightFromRectangleIcon: LoadedIconFunction = createIcon(
  "arrowRightFromRectangle",
  iconDefinition,
);
