// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const microphoneMuteIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "microphoneMute",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneMute" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneMute" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneMute" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-microphoneMute" */
          "./fillSmall.icon"
        ),
    },
  },
  [
    "microphone",
    "dictate",
    "record",
    "audio",
    "voice",
    "speak",
    "sound",
    "mute",
    "off",
    "quiet",
  ],
);
