// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M4.25 2.45a1.8 1.8 0 0 0-1.8 1.8v7.5a1.8 1.8 0 0 0 1.8 1.8h7.5a1.8 1.8 0 0 0 1.8-1.8v-7.5a1.8 1.8 0 0 0-1.8-1.8zm.85 4.217a.5.5 0 0 1 .5-.5h4.8a.5.5 0 1 1 0 1H5.6a.5.5 0 0 1-.5-.5m.5 2.166h4.8a.5.5 0 0 1 0 1H5.6a.5.5 0 0 1 0-1" />
  ),
};

export const equalSquareFillSmallIcon: LoadedIconFunction = createIcon(
  "equalSquareFillSmall",
  iconDefinition,
);
