// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const exclamationMarkCircleIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "exclamationMarkCircle",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationMarkCircle" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationMarkCircle" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationMarkCircle" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-exclamationMarkCircle" */
          "./fillSmall.icon"
        ),
    },
  },
  ["exclamation", "circle", "alert", "warning", "attention"],
);
