// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M4.665 17.22a.625.625 0 0 0 .805.365 7.96 7.96 0 0 0 4.528-4.353 7.94 7.94 0 0 0 4.532 4.353.625.625 0 0 0 .44-1.17 6.69 6.69 0 0 1-4.345-6.268V4.509l2.683 2.683a.625.625 0 0 0 .884-.884l-3.75-3.75a.625.625 0 0 0-.884 0l-3.75 3.75a.625.625 0 1 0 .884.884l2.683-2.683v5.625a6.71 6.71 0 0 1-4.345 6.281.625.625 0 0 0-.365.805" />
  ),
};

export const arrowMergeUpIcon: LoadedIconFunction = createIcon(
  "arrowMergeUp",
  iconDefinition,
);
