// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowMergeUpIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowMergeUp",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowMergeUp" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowMergeUp" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowMergeUp" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowMergeUp" */
          "./fillSmall.icon"
        ),
    },
  },
  ["arrow", "merge", "combine", "unify", "integrate", "join"],
);
