// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="m5.669 16.019 5.4-5.4a.875.875 0 0 0 0-1.238l-5.4-5.4A.875.875 0 1 0 4.43 5.22L9.213 10 4.43 14.781a.875.875 0 1 0 1.24 1.239" />
      <path d="M16.569 9.381a.875.875 0 0 1 0 1.238l-5.4 5.4A.875.875 0 0 1 9.93 14.78L14.712 10 9.93 5.218a.875.875 0 1 1 1.24-1.238z" />
    </>
  ),
};

export const arrowChevronDoubleForwardFillIcon: LoadedIconFunction = createIcon(
  "arrowChevronDoubleForwardFill",
  iconDefinition,
);
