// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowChevronDoubleForwardIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowChevronDoubleForward",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronDoubleForward" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronDoubleForward" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronDoubleForward" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowChevronDoubleForward" */
          "./fillSmall.icon"
        ),
    },
  },
  ["double", "chevron", "right", "arrows", "direction"],
);
