// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M3.14 2.3a.5.5 0 1 0 0 1h9.72a.5.5 0 0 0 0-1zm0 6.213a.5.5 0 1 0 0 1h9.72a.5.5 0 0 0 0-1zm.36-4.186a.86.86 0 0 0-.86.86v1.44c0 .475.385.86.86.86h1.44a.86.86 0 0 0 .86-.86v-1.44a.86.86 0 0 0-.86-.86zm3.78 0a.86.86 0 0 0-.86.86v1.44c0 .475.385.86.86.86h1.44a.86.86 0 0 0 .86-.86v-1.44a.86.86 0 0 0-.86-.86zm3.78 0a.86.86 0 0 0-.86.86v1.44c0 .475.385.86.86.86h1.44a.86.86 0 0 0 .86-.86v-1.44a.86.86 0 0 0-.86-.86zM3.5 10.54a.86.86 0 0 0-.86.86v1.44c0 .475.385.86.86.86h1.44a.86.86 0 0 0 .86-.86V11.4a.86.86 0 0 0-.86-.86zm3.78 0a.86.86 0 0 0-.86.86v1.44c0 .475.385.86.86.86h1.44a.86.86 0 0 0 .86-.86V11.4a.86.86 0 0 0-.86-.86zm3.78 0a.86.86 0 0 0-.86.86v1.44c0 .475.385.86.86.86h1.44a.86.86 0 0 0 .86-.86V11.4a.86.86 0 0 0-.86-.86z" />
  ),
};

export const squareGridBelowLinesFillSmallIcon: LoadedIconFunction = createIcon(
  "squareGridBelowLinesFillSmall",
  iconDefinition,
);
