// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M13.8 4.85a1.8 1.8 0 0 0-1.8-1.8H4a1.8 1.8 0 0 0-1.8 1.8v5.5a1.8 1.8 0 0 0 1.8 1.8h.54v1.897a.55.55 0 0 0 .898.427l2.86-2.324H12a1.8 1.8 0 0 0 1.8-1.8zM5.53 8.3a.7.7 0 1 1 0-1.4.7.7 0 0 1 0 1.4m3.3-.7a.7.7 0 1 1-1.4 0 .7.7 0 0 1 1.4 0m1.9.7a.7.7 0 1 1 0-1.4.7.7 0 0 1 0 1.4" />
  ),
};

export const bubbleEllipsesFillSmallIcon: LoadedIconFunction = createIcon(
  "bubbleEllipsesFillSmall",
  iconDefinition,
);
