// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M14.154 5.57a.875.875 0 0 1-1.237 0l-2.042-2.042v5.058a.875.875 0 1 1-1.75 0V3.528L7.083 5.57a.875.875 0 1 1-1.237-1.238L9.38.797a.875.875 0 0 1 1.238 0l3.535 3.535a.875.875 0 0 1 0 1.238m-3.278 5.849a.875.875 0 1 0-1.75 0v5.044l-2.042-2.042a.875.875 0 0 0-1.237 1.238l3.535 3.535a.875.875 0 0 0 1.238 0l3.535-3.535a.875.875 0 1 0-1.237-1.238l-2.042 2.042z" />
  ),
};

export const arrowUpDownStackedFillIcon: LoadedIconFunction = createIcon(
  "arrowUpDownStackedFill",
  iconDefinition,
);
