// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowUpDownStackedIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowUpDownStacked",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpDownStacked" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpDownStacked" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpDownStacked" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowUpDownStacked" */
          "./fillSmall.icon"
        ),
    },
  },
  ["arrows", "more", "arrange", "organize", "order", "categorize"],
);
