// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.618 2.595a1.096 1.096 0 1 0 0 2.192 1.096 1.096 0 0 0 0-2.192m4.764 0a1.096 1.096 0 1 0 0 2.192 1.096 1.096 0 0 0 0-2.192M1.939 4.95a.575.575 0 0 0-.127 1.142q1.273.143 2.55.225v.532a27.4 27.4 0 0 1-.442 4.796l-.229 1.259a.575.575 0 0 0 1.132.206l.229-1.26q.18-1.001.292-2.011h.548q.11 1.01.293 2.012l.228 1.259a.575.575 0 0 0 1.132-.206l-.229-1.26a27.4 27.4 0 0 1-.442-4.905v-.315q1.125.022 2.252 0v.625a25 25 0 0 1-.405 4.395l-.266 1.46a.575.575 0 0 0 1.132.206l.265-1.46q.164-.902.265-1.811h.54q.11 1.01.291 2.012l.23 1.259a.575.575 0 0 0 1.13-.206l-.228-1.26a27.4 27.4 0 0 1-.442-4.905v-.422a56 56 0 0 0 2.55-.225.575.575 0 1 0-.126-1.143 55 55 0 0 1-12.123 0" />
  ),
};

export const figure2SmallIcon: LoadedIconFunction = createIcon(
  "figure2Small",
  iconDefinition,
);
