// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.39 6.45 2.557 3.618a.75.75 0 1 1 1.06-1.06L6.45 5.389V3.2a.75.75 0 1 1 1.5 0v4a.75.75 0 0 1-.75.75h-4a.75.75 0 0 1 0-1.5zm4.163 4.163v2.19a.75.75 0 0 1-1.5 0v-4a.75.75 0 0 1 .75-.75h4a.75.75 0 0 1 0 1.5h-2.19l2.83 2.829a.75.75 0 0 1-1.061 1.06z" />
  ),
};

export const arrowCollapseFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowCollapseFillSmall",
  iconDefinition,
);
