// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 1.95a6.05 6.05 0 1 0 0 12.1 6.05 6.05 0 0 0 0-12.1M5.531 8.32a.55.55 0 0 1 .778 0L7.45 9.462V5.21a.55.55 0 1 1 1.1 0v4.252l1.141-1.14a.55.55 0 0 1 .778.777l-2.08 2.08a.55.55 0 0 1-.778 0l-2.08-2.08a.55.55 0 0 1 0-.778" />
  ),
};

export const arrowInCircleDownFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowInCircleDownFillSmall",
  iconDefinition,
);
