// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M8 4.585a.625.625 0 0 0-.625.625v4.071L6.362 8.268a.625.625 0 1 0-.884.884l2.08 2.08a.625.625 0 0 0 .884 0l2.08-2.08a.625.625 0 1 0-.884-.884L8.625 9.281v-4.07A.625.625 0 0 0 8 4.584" />
      <path d="M8 1.875a6.125 6.125 0 1 0 0 12.25 6.125 6.125 0 0 0 0-12.25M3.125 8a4.875 4.875 0 1 1 9.75 0 4.875 4.875 0 0 1-9.75 0" />
    </>
  ),
};

export const arrowInCircleDownSmallIcon: LoadedIconFunction = createIcon(
  "arrowInCircleDownSmall",
  iconDefinition,
);
