// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 2.21a.75.75 0 0 1 .75.75v3.741l3.24-1.87a.75.75 0 0 1 .75 1.298L9.5 8l3.24 1.871a.75.75 0 0 1-.75 1.3L8.75 9.298v3.741a.75.75 0 0 1-1.5 0v-3.74l-3.24 1.87a.75.75 0 1 1-.75-1.299L6.5 8 3.26 6.13a.75.75 0 1 1 .75-1.3L7.25 6.7V2.96A.75.75 0 0 1 8 2.21" />
  ),
};

export const asteriskFillSmallIcon: LoadedIconFunction = createIcon(
  "asteriskFillSmall",
  iconDefinition,
);
