// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v7.5a2.125 2.125 0 0 1-2.125 2.125h-11a2.125 2.125 0 0 1-2.125-2.125zm14 2.625h-5.75v2.25h5.75zm0 3.5h-5.75v2.25H15.5a.875.875 0 0 0 .875-.875zm-7-3.5h-5.75v2.25h5.75zm0 3.5h-5.75v1.375c0 .483.392.875.875.875h4.875z" />
  ),
};

export const tableHeaderRowIcon: LoadedIconFunction = createIcon(
  "tableHeaderRow",
  iconDefinition,
);
