// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v1.375H2.375zm8.25 2.625h7v2.75h-7zm-1.25 2.75v-2.75h-7v2.75zm-7 1.25h7v3H4.5a2.125 2.125 0 0 1-2.125-2.125zm8.25 0h7v.875a2.125 2.125 0 0 1-2.125 2.125h-4.875z" />
  ),
};

export const tableHeaderRowFillIcon: LoadedIconFunction = createIcon(
  "tableHeaderRowFill",
  iconDefinition,
);
