// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.575 5.05a.625.625 0 0 0-.625-.625H7.313a.625.625 0 1 0 0 1.25h6.128L4.596 14.52a.617.617 0 0 0 .012.872c.244.244.635.25.872.012l8.845-8.845v6.128a.625.625 0 1 0 1.25 0z" />
  ),
};

export const arrowDiagonalUpRightIcon: LoadedIconFunction = createIcon(
  "arrowDiagonalUpRight",
  iconDefinition,
);
