// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M6.7 3.115a1.828 1.828 0 0 0-2.558 2.151 1.828 1.828 0 0 0-.882 2.93l.084.1a1.827 1.827 0 0 0-.724 2.876l3.616 4.298a6.291 6.291 0 0 0 10.73-6.193l-1.762-4.868a1.863 1.863 0 0 0-3.612.54L9.737 2.747a1.828 1.828 0 0 0-3.038.369m-1.174 1.2a.58.58 0 0 1 .814.07L9.17 7.748a.625.625 0 0 0 .956-.805L7.897 4.295a.578.578 0 0 1 .884-.744l3.73 4.431a.625.625 0 0 0 1.07-.598l-.71-2.149a.612.612 0 0 1 1.158-.4l1.762 4.867a5.042 5.042 0 0 1-8.598 4.963l-3.617-4.297a.577.577 0 1 1 .885-.744l1.627 1.934a.625.625 0 0 0 .957-.805L4.216 7.392a.578.578 0 0 1 .884-.744l2.228 2.648a.625.625 0 0 0 .957-.805L5.456 5.13a.58.58 0 0 1 .07-.814" />
  ),
};

export const handWaveIcon: LoadedIconFunction = createIcon(
  "handWave",
  iconDefinition,
);
