// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 6.25c0-1.174.951-2.125 2.125-2.125h11c1.174 0 2.125.951 2.125 2.125v7.5a2.125 2.125 0 0 1-2.125 2.125h-11a2.125 2.125 0 0 1-2.125-2.125zm8.555 2.875a.5.5 0 0 0-.5.5v3.75a.5.5 0 0 0 .5.5h4.145a.5.5 0 0 0 .5-.5v-3.75a.5.5 0 0 0-.5-.5z" />
  ),
};

export const peekCornerFillIcon: LoadedIconFunction = createIcon(
  "peekCornerFill",
  iconDefinition,
);
