// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M2.375 10a7.625 7.625 0 1 1 15.25 0 7.625 7.625 0 0 1-15.25 0m4.769-1.046 2.236 3.834a.718.718 0 0 0 1.24 0l2.236-3.834a.718.718 0 0 0-.62-1.079H7.764c-.554 0-.899.6-.62 1.08" />
  ),
};

export const arrowTriangleDownCircleFillIcon: LoadedIconFunction = createIcon(
  "arrowTriangleDownCircleFill",
  iconDefinition,
);
