// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M6.211 6.225c-.5 0-.813.543-.56.976l1.788 3.067a.65.65 0 0 0 1.122 0l1.789-3.067a.649.649 0 0 0-.561-.976z" />
      <path d="M8 1.875a6.125 6.125 0 1 0 0 12.25 6.125 6.125 0 0 0 0-12.25M3.125 8a4.875 4.875 0 1 1 9.75 0 4.875 4.875 0 0 1-9.75 0" />
    </>
  ),
};

export const arrowTriangleDownCircleSmallIcon: LoadedIconFunction = createIcon(
  "arrowTriangleDownCircleSmall",
  iconDefinition,
);
