// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <g clipPath="url(#clip0_10576_6471)">
        <path d="M4.5 4.125A2.125 2.125 0 0 0 2.375 6.25V7.5h15.25V6.25A2.125 2.125 0 0 0 15.5 4.125zm.133 1.059a.625.625 0 1 1 0 1.25.625.625 0 0 1 0-1.25m2.625.625a.625.625 0 1 1-1.25 0 .625.625 0 0 1 1.25 0m1.375-.625a.625.625 0 1 1 0 1.25.625.625 0 0 1 0-1.25M2.375 13.75V8.6h15.25v2.119a4.75 4.75 0 0 0-7.423 5.156H4.5a2.125 2.125 0 0 1-2.125-2.125" />
        <path d="M17.703 16.603a3.625 3.625 0 1 0-.892.88l1.219 1.429a.625.625 0 0 0 .94-.824zM12.375 14.5a2.375 2.375 0 1 1 4.75 0 2.375 2.375 0 0 1-4.75 0" />
      </g>
      <defs>
        <clipPath id="clip0_10576_6471">
          <path d="M0 0h20v20H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const browserMagnifyingGlassFillIcon: LoadedIconFunction = createIcon(
  "browserMagnifyingGlassFill",
  iconDefinition,
);
