// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const browserMagnifyingGlassIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "browserMagnifyingGlass",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserMagnifyingGlass" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserMagnifyingGlass" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserMagnifyingGlass" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-browserMagnifyingGlass" */
          "./fillSmall.icon"
        ),
    },
  },
  ["chrome", "safari", "firefox", "windows", "mac", "search", "find", "web"],
);
