// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M10.75 2.2a1.8 1.8 0 0 1 1.8 1.8v3.45h-9.1V4a1.8 1.8 0 0 1 1.8-1.8zm-7.3 6.35V12a1.8 1.8 0 0 0 1.8 1.8h5.5a1.8 1.8 0 0 0 1.8-1.8V8.55z" />
  ),
};

export const rectangleSplit2VerticalFillSmallIcon: LoadedIconFunction =
  createIcon("rectangleSplit2VerticalFillSmall", iconDefinition);
