// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M9.219 8.002a1.22 1.22 0 1 1-2.439 0 1.22 1.22 0 0 1 2.439 0" />
      <path d="M.914 7.44a1.21 1.21 0 0 0 0 1.128c1.282 2.442 3.987 4.1 7.086 4.1s5.804-1.658 7.086-4.1a1.21 1.21 0 0 0 0-1.128C13.804 4.997 11.099 3.34 8 3.34S2.196 4.997.914 7.44M8 10.628a2.626 2.626 0 1 1 .001-5.251A2.626 2.626 0 0 1 8 10.627" />
    </>
  ),
};

export const eyeFillSmallIcon: LoadedIconFunction = createIcon(
  "eyeFillSmall",
  iconDefinition,
);
