// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M10.625 8.002a2.626 2.626 0 1 1-5.251 0 2.626 2.626 0 0 1 5.251 0M8 8.878a.876.876 0 1 0-.001-1.751A.876.876 0 0 0 8 8.878" />
      <path d="M.914 7.44C2.196 4.997 4.901 3.34 8 3.34s5.804 1.657 7.086 4.1c.185.353.185.774 0 1.128-1.282 2.442-3.987 4.1-7.086 4.1S2.196 11.01.914 8.567a1.21 1.21 0 0 1 0-1.128M8 4.44c-2.71 0-5.03 1.448-6.112 3.51a.11.11 0 0 0 0 .107c1.083 2.062 3.401 3.51 6.112 3.51 2.71 0 5.03-1.448 6.111-3.51a.11.11 0 0 0 0-.106C13.03 5.888 10.711 4.44 8 4.44" />
    </>
  ),
};

export const eyeSmallIcon: LoadedIconFunction = createIcon(
  "eyeSmall",
  iconDefinition,
);
