// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M9.558 3.608a.625.625 0 0 1 .884 0l5.4 5.4a.625.625 0 1 1-.884.884L10 4.934 5.042 9.892a.625.625 0 0 1-.884-.884z" />
      <path d="m4.158 14.508 5.4-5.4a.625.625 0 0 1 .884 0l5.4 5.4a.625.625 0 1 1-.884.884L10 10.434l-4.958 4.958a.625.625 0 1 1-.884-.884" />
    </>
  ),
};

export const arrowChevronDoubleUpwardIcon: LoadedIconFunction = createIcon(
  "arrowChevronDoubleUpward",
  iconDefinition,
);
