// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M9.381 3.431a.875.875 0 0 1 1.238 0l5.4 5.4a.875.875 0 0 1-1.238 1.238l-4.78-4.782-4.782 4.782A.875.875 0 0 1 3.98 8.83z" />
      <path d="m3.981 14.331 5.4-5.4a.875.875 0 0 1 1.238 0l5.4 5.4a.875.875 0 0 1-1.238 1.238l-4.78-4.782-4.782 4.782A.875.875 0 1 1 3.98 14.33" />
    </>
  ),
};

export const arrowChevronDoubleUpwardFillIcon: LoadedIconFunction = createIcon(
  "arrowChevronDoubleUpwardFill",
  iconDefinition,
);
