// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M7.47 2.71a.75.75 0 0 1 1.06 0l4.32 4.32a.75.75 0 1 1-1.06 1.06L8 4.3 4.21 8.09a.75.75 0 0 1-1.06-1.06z" />
      <path d="m3.15 11.43 4.32-4.32a.75.75 0 0 1 1.06 0l4.32 4.32a.75.75 0 1 1-1.06 1.06L8 8.7l-3.79 3.79a.75.75 0 0 1-1.06-1.06" />
    </>
  ),
};

export const arrowChevronDoubleUpwardFillSmallIcon: LoadedIconFunction =
  createIcon("arrowChevronDoubleUpwardFillSmall", iconDefinition);
