// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M8.442 2.798a.625.625 0 0 0-.884 0l-4.32 4.32a.625.625 0 1 0 .884.884L8 4.124l3.878 3.878a.625.625 0 0 0 .884-.884z" />
      <path d="m7.558 7.198-4.32 4.32a.625.625 0 0 0 .884.884L8 8.524l3.878 3.878a.625.625 0 0 0 .884-.884l-4.32-4.32a.625.625 0 0 0-.884 0" />
    </>
  ),
};

export const arrowChevronDoubleUpwardSmallIcon: LoadedIconFunction = createIcon(
  "arrowChevronDoubleUpwardSmall",
  iconDefinition,
);
