// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m18.441 10.443-5.249 5.249a.625.625 0 0 1-.884-.884L17.116 10l-4.808-4.808a.625.625 0 1 1 .884-.884l5.245 5.245.005.005a.625.625 0 0 1 0 .885M2.884 10l4.808-4.808a.625.625 0 1 0-.884-.884L1.561 9.555l-.003.003a.625.625 0 0 0 0 .884l5.25 5.25a.625.625 0 1 0 .884-.884z" />
  ),
};

export const arrowChevronDoubleLeftAndRightIcon: LoadedIconFunction =
  createIcon("arrowChevronDoubleLeftAndRight", iconDefinition);
