// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="m14.93 8.53-4.2 4.2a.75.75 0 1 1-1.06-1.06L13.34 8 9.67 4.33a.75.75 0 1 1 1.06-1.06l4.195 4.195.005.005a.75.75 0 0 1 .014 1.047M2.66 8l3.67-3.67a.75.75 0 1 0-1.06-1.06L1.072 7.467l-.002.003a.75.75 0 0 0 0 1.06l4.2 4.2a.75.75 0 1 0 1.06-1.06z" />
  ),
};

export const arrowChevronDoubleLeftAndRightFillSmallIcon: LoadedIconFunction =
  createIcon("arrowChevronDoubleLeftAndRightFillSmall", iconDefinition);
