// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M5.25 1.7a1.8 1.8 0 0 0-1.8 1.8v9.75a.8.8 0 0 0 1.28.64L8 11.437l3.27 2.453a.8.8 0 0 0 1.28-.64V3.5a1.8 1.8 0 0 0-1.8-1.8z" />
  ),
};

export const bookmarkFillSmallIcon: LoadedIconFunction = createIcon(
  "bookmarkFillSmall",
  iconDefinition,
);
