// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M14.183 2.899a1.125 1.125 0 0 1 1.692.972V16.13c0 .868-.942 1.409-1.692.971l-10.507-6.13a1.125 1.125 0 0 1 0-1.943zm.442 1.19L4.491 10l10.134 5.912z" />
  ),
};

export const arrowCaretLeftIcon: LoadedIconFunction = createIcon(
  "arrowCaretLeft",
  iconDefinition,
);
