// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.75 2.835a.8.8 0 0 0-1.203-.69L2.693 7.308a.8.8 0 0 0 0 1.382l8.854 5.165a.8.8 0 0 0 1.203-.691z" />
  ),
};

export const arrowCaretLeftFillSmallIcon: LoadedIconFunction = createIcon(
  "arrowCaretLeftFillSmall",
  iconDefinition,
);
