// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.825 2.835a.875.875 0 0 0-1.316-.756L2.655 7.245a.875.875 0 0 0 0 1.512l8.854 5.165a.875.875 0 0 0 1.316-.756zM3.84 8l7.735-4.512v9.024z" />
  ),
};

export const arrowCaretLeftSmallIcon: LoadedIconFunction = createIcon(
  "arrowCaretLeftSmall",
  iconDefinition,
);
