// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M10.722 3.038a.625.625 0 0 0-.884.884l2.453 2.453H4.2A1.825 1.825 0 0 0 2.375 8.2v4a.625.625 0 1 0 1.25 0v-4c0-.318.257-.575.575-.575h8.091l-2.453 2.453a.625.625 0 0 0 .884.884l3.52-3.52a.625.625 0 0 0 0-.884z" />
  ),
};

export const arrowTurnUpRightSmallIcon: LoadedIconFunction = createIcon(
  "arrowTurnUpRightSmall",
  iconDefinition,
);
