// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M10.75 13.8a1.8 1.8 0 0 0 1.8-1.8V4a1.8 1.8 0 0 0-1.8-1.8h-5.5A1.8 1.8 0 0 0 3.45 4v8a1.8 1.8 0 0 0 1.8 1.8zM5.435 5.927c0-.839.68-1.519 1.52-1.519h.174a.3.3 0 0 1 0 .6h-.174a.92.92 0 0 0-.907.766.997.997 0 1 1 .732 1.673 1.345 1.345 0 0 1-1.345-1.345zm2.787 0c0-.839.68-1.519 1.52-1.519h.174a.3.3 0 0 1 0 .6h-.174a.92.92 0 0 0-.907.766.997.997 0 1 1 .732 1.673 1.345 1.345 0 0 1-1.345-1.345zM8.5 11.25a.5.5 0 0 1-.5.5H5.75a.5.5 0 1 1 0-1H8a.5.5 0 0 1 .5.5m1.75-1.5h-4.5a.5.5 0 0 1 0-1h4.5a.5.5 0 0 1 0 1" />
  ),
};

export const docWithQuotationMarksFillSmallIcon: LoadedIconFunction =
  createIcon("docWithQuotationMarksFillSmall", iconDefinition);
