// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M11.709 4.125H8.292v11.75h3.417zm1.25 11.75H15.5a2.125 2.125 0 0 0 2.125-2.125v-7.5A2.125 2.125 0 0 0 15.5 4.125h-2.541zM4.5 4.125h2.542v11.75H4.5a2.125 2.125 0 0 1-2.125-2.125v-7.5c0-1.174.951-2.125 2.125-2.125" />
  ),
};

export const viewBoardFillIcon: LoadedIconFunction = createIcon(
  "viewBoardFill",
  iconDefinition,
);
