// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const arrowCircleLoopSlashIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "arrowCircleLoopSlash",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowCircleLoopSlash" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowCircleLoopSlash" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowCircleLoopSlash" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-arrowCircleLoopSlash" */
          "./fillSmall.icon"
        ),
    },
  },
  ["refresh", "reload", "update", "sync", "circular"],
);
