// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M9.538 10.331c0 2.171-1.657 3.931-3.7 3.931s-3.7-1.76-3.7-3.93a4 4 0 0 1 .05-.657h-.513a.5.5 0 0 1 0-1h.806C3.069 7.33 4.351 6.4 5.838 6.4c1.362 0 2.553.782 3.195 1.948a2.5 2.5 0 0 1 1.935 0C11.61 7.182 12.8 6.4 14.163 6.4c1.486 0 2.768.931 3.356 2.275h.806a.5.5 0 1 1 0 1h-.514q.052.32.052.656c0 2.171-1.657 3.931-3.7 3.931s-3.7-1.76-3.7-3.93q.001-.55.134-1.055a1.5 1.5 0 0 0-1.194 0q.133.505.135 1.054m-1.25 0c0-1.553-1.168-2.681-2.45-2.681s-2.45 1.128-2.45 2.681 1.167 2.681 2.45 2.681c1.282 0 2.45-1.128 2.45-2.68m8.325 0c0-1.553-1.168-2.681-2.45-2.681s-2.45 1.128-2.45 2.681 1.167 2.681 2.45 2.681c1.282 0 2.45-1.128 2.45-2.68" />
  ),
};

export const eyeglassesIcon: LoadedIconFunction = createIcon(
  "eyeglasses",
  iconDefinition,
);
