// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="m13.304 6.72.933-.934v-.023a1.16 1.16 0 0 0-.073-1.553 1.16 1.16 0 0 0-1.634 0l-.868.868zm-8.573 8.572 8.091-8.09-1.642-1.643-8.098 8.084c-.156.156-.264.36-.333.549l-.339 1.093-.002.01c-.105.392.257.815.686.667l1.073-.332q.319-.092.564-.338M17 16.125H5.666l1.75-1.75H17a.875.875 0 1 1 0 1.75" />
  ),
};

export const pencilLineFillIcon: LoadedIconFunction = createIcon(
  "pencilLineFill",
  iconDefinition,
);
