// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M8 1.95a6.05 6.05 0 1 0 0 12.1 6.05 6.05 0 0 0 0-12.1m0 3.5a.55.55 0 0 1 .55.55v1.45H10a.55.55 0 1 1 0 1.1H8.55V10a.55.55 0 1 1-1.1 0V8.55H6a.55.55 0 1 1 0-1.1h1.45V6A.55.55 0 0 1 8 5.45" />
  ),
};

export const plusCircleFillSmallIcon: LoadedIconFunction = createIcon(
  "plusCircleFillSmall",
  iconDefinition,
);
