// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <path d="M10.208 2.225a.75.75 0 1 0 0 1.5h1.05v9h-1.05a.75.75 0 1 0 0 1.5h3.6a.75.75 0 0 0 0-1.5h-1.05v-9h1.05a.75.75 0 0 0 0-1.5z" />
      <path d="m8.013 12.4-.839-2.27h-3.44l-.839 2.27a.75.75 0 0 1-1.407-.52l2.99-8.09a1.04 1.04 0 0 1 1.953 0l2.99 8.09a.75.75 0 0 1-1.408.52M5.454 5.476 4.29 8.63h2.33z" />
    </>
  ),
};

export const textCursorIBeamFillSmallIcon: LoadedIconFunction = createIcon(
  "textCursorIBeamFillSmall",
  iconDefinition,
);
