// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M13.166 2.216a2.05 2.05 0 0 1 1.74.58l2.298 2.299c.456.456.671 1.1.58 1.74l-.383 2.68a2.05 2.05 0 0 1-.58 1.16l-6.529 6.53c-.8.8-2.098.8-2.899 0l-4.597-4.598c-.8-.8-.8-2.099 0-2.9L9.324 3.18a2.05 2.05 0 0 1 1.16-.58zm-.828 5.446a1.188 1.188 0 1 0 1.68-1.68 1.188 1.188 0 0 0-1.68 1.68" />
  ),
};

export const priceTagFillIcon: LoadedIconFunction = createIcon(
  "priceTagFill",
  iconDefinition,
);
