// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const priceTagIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "priceTag",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-priceTag" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-priceTag" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-priceTag" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-priceTag" */
          "./fillSmall.icon"
        ),
    },
  },
  ["cost", "sale", "bargain", "tag", "discount"],
);
