// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import type { IconGroup } from "../../iconUtils";
import { createIconGroup } from "../../iconUtils";

export const squareDashedIconGroup: IconGroup<
  "default" | "small" | "fill" | "fillSmall"
> = createIconGroup(
  "squareDashed",
  {
    default: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareDashed" */
          "./default.icon"
        ),
    },
    small: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareDashed" */
          "./small.icon"
        ),
    },
    fill: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareDashed" */
          "./fill.icon"
        ),
    },
    fillSmall: {
      loader: () =>
        import(
          /* webpackChunkName: "icon-squareDashed" */
          "./fillSmall.icon"
        ),
    },
  },
  ["copy", "duplicate", "stacked", "squares", "overlap", "geometry", "layers"],
);
