// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.63 4.75a.625.625 0 1 1 1.25 0v5a2.125 2.125 0 0 1-2.125 2.125H4.264l3.333 3.333a.625.625 0 0 1-.884.884l-4.4-4.4a.625.625 0 0 1 0-.884l4.4-4.4a.625.625 0 0 1 .884.884l-3.333 3.333h10.49a.875.875 0 0 0 .876-.875z" />
  ),
};

export const arrowTurnDownLeftIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownLeft",
  iconDefinition,
);
