// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <path d="M15.38 4.75a.875.875 0 1 1 1.75 0v5a2.375 2.375 0 0 1-2.375 2.375H4.867l2.907 2.906a.875.875 0 1 1-1.238 1.238l-4.4-4.4a.875.875 0 0 1 0-1.238l4.4-4.4A.875.875 0 0 1 7.774 7.47l-2.907 2.906h9.888c.345 0 .625-.28.625-.625z" />
  ),
};

export const arrowTurnDownLeftFillIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownLeftFill",
  iconDefinition,
);
