// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <path d="M12.995 3.175c.345 0 .625.28.625.625v4a1.825 1.825 0 0 1-1.825 1.825H3.704l2.453 2.453a.625.625 0 0 1-.884.884l-3.52-3.52a.625.625 0 0 1 0-.884l3.52-3.52a.625.625 0 1 1 .884.884L3.704 8.375h8.091a.575.575 0 0 0 .575-.575v-4c0-.345.28-.625.625-.625" />
  ),
};

export const arrowTurnDownLeftSmallIcon: LoadedIconFunction = createIcon(
  "arrowTurnDownLeftSmall",
  iconDefinition,
);
