// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 20 20",
  svg: (
    <>
      <path d="M13.114 3.494 3.202 4.815A1.5 1.5 0 0 0 1.913 6.5l.859 6.443a1.5 1.5 0 0 0 1.685 1.289l.204-.027V8.8c0-1.174.951-2.125 2.125-2.125h8.265L14.8 4.782a1.5 1.5 0 0 0-1.685-1.288" />
      <path d="M5.91 8.8c0-.483.392-.875.876-.875h10c.483 0 .874.392.874.875v6.5a.875.875 0 0 1-.875.875h-10a.875.875 0 0 1-.874-.875z" />
    </>
  ),
};

export const rectangleOnRectangleTiltFillIcon: LoadedIconFunction = createIcon(
  "rectangleOnRectangleTiltFill",
  iconDefinition,
);
