// This file is generated by `notion figma import-icons`.
// See src/cli/commands/figma/import-icons.ts for more information.
import React from "react";

import {
  createIcon,
  type IconDefinition,
  type LoadedIconFunction,
} from "../../iconUtils";

export const iconDefinition: IconDefinition = {
  viewBox: "0 0 16 16",
  svg: (
    <>
      <g clipPath="url(#clip0_10858_21647)">
        <path d="M1.035 5.266a1.7 1.7 0 0 1 1.46-1.91l7.93-1.057a1.7 1.7 0 0 1 1.91 1.46l.21 1.581h.883a1.7 1.7 0 0 1 1.7 1.7v5.2a1.7 1.7 0 0 1-1.7 1.7h-8a1.7 1.7 0 0 1-1.7-1.7v-.372l-.096.013a1.7 1.7 0 0 1-1.91-1.46zm2.693 5.593V7.04a1.7 1.7 0 0 1 1.7-1.7h6.109l-.193-1.448a.7.7 0 0 0-.787-.601l-7.93 1.057a.7.7 0 0 0-.6.786l.686 5.154a.7.7 0 0 0 .787.602zm1-3.819v5.2a.7.7 0 0 0 .7.7h8a.7.7 0 0 0 .7-.7v-5.2a.7.7 0 0 0-.7-.7h-8a.7.7 0 0 0-.7.7" />
      </g>
      <defs>
        <clipPath id="clip0_10858_21647">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </>
  ),
};

export const rectangleOnRectangleTiltSmallIcon: LoadedIconFunction = createIcon(
  "rectangleOnRectangleTiltSmall",
  iconDefinition,
);
